// ── Module 01 — Introduction to Networking · expansion pool ─────────────────
QUESTIONS["01"].push(
  {
    q: "Which OSI layer converts data into signals and places them on the physical medium?",
    options: ["Data Link", "Physical", "Network", "Transport"],
    answer: 1,
    explain: "The Physical layer (Layer 1) transmits raw bits as electrical, optical, or radio signals over the medium (cables, connectors, NIC hardware).",
  },
  {
    q: "At which OSI layer does error detection via a frame check sequence (FCS) occur?",
    options: ["Physical", "Data Link", "Network", "Session"],
    answer: 1,
    explain: "The Data Link layer (Layer 2) adds a trailer containing an FCS so the receiver can detect corrupted frames.",
  },
  {
    q: "Which organization publishes the 802 family of networking standards (Ethernet, Wi-Fi)?",
    options: ["IETF", "IEEE", "ICANN", "ISO"],
    answer: 1,
    explain: "The IEEE (Institute of Electrical and Electronics Engineers) maintains the 802 standards — 802.3 Ethernet, 802.11 Wi-Fi, 802.1Q VLANs, and more.",
  },
  {
    q: "Which body publishes RFC documents that define Internet protocols?",
    options: ["IEEE", "IETF", "TIA", "IANA"],
    answer: 1,
    explain: "The IETF (Internet Engineering Task Force) publishes RFCs (Requests for Comments) that define protocols like TCP, IP, HTTP, and DNS.",
  },
  {
    q: "A transmission that sends data in both directions simultaneously is called...",
    options: ["Simplex", "Half-duplex", "Full-duplex", "Multiplex"],
    answer: 2,
    explain: "Full-duplex allows simultaneous two-way communication (like a phone call). Half-duplex is one direction at a time; simplex is one direction only.",
  },
  {
    q: "A walkie-talkie, where only one party transmits at a time, is an example of...",
    options: ["Full-duplex", "Half-duplex", "Simplex", "Broadcast"],
    answer: 1,
    explain: "Half-duplex permits communication in both directions but only one direction at a time — you must stop transmitting to receive.",
  },
  {
    q: "Which transmission type sends a single frame to every device in a broadcast domain?",
    options: ["Unicast", "Multicast", "Broadcast", "Anycast"],
    answer: 2,
    explain: "A broadcast is delivered to all hosts on the local network. Unicast is one-to-one; multicast is one-to-a-group.",
  },
  {
    q: "One-to-one communication between a single sender and a single receiver is called...",
    options: ["Broadcast", "Unicast", "Multicast", "Flood"],
    answer: 1,
    explain: "Unicast traffic is addressed to a single specific destination — the most common type of network communication.",
  },
  {
    q: "In the client-server model, the software that requests a service is the...",
    options: ["Server", "Client", "Gateway", "Host process"],
    answer: 1,
    explain: "The client initiates requests (e.g., a web browser); the server responds to them (e.g., a web server). This is the basis of most network applications.",
  },
  {
    q: "Which topology is easiest to troubleshoot because each device has its own dedicated cable to a central point?",
    options: ["Bus", "Ring", "Star", "Mesh"],
    answer: 2,
    explain: "In a star, each node's cable is independent, so a single cable fault affects only that node and is easy to isolate — a key reason stars dominate modern LANs.",
  },
  {
    q: "What is the main disadvantage of a bus topology?",
    options: [
      "It needs a switch at the center",
      "A single break in the backbone can bring down the whole segment",
      "It uses too many cables",
      "It cannot carry data",
    ],
    answer: 1,
    explain: "In a bus, all devices share one backbone cable; a break or bad terminator disrupts the entire segment. This fragility is why bus topologies are obsolete.",
  },
  {
    q: "Which best describes 'throughput' vs 'bandwidth'?",
    options: [
      "They are identical",
      "Bandwidth is the maximum capacity; throughput is the actual data rate achieved",
      "Throughput is always higher than bandwidth",
      "Bandwidth is measured in milliseconds",
    ],
    answer: 1,
    explain: "Bandwidth is the theoretical maximum; throughput is what's actually achieved after overhead, congestion, and errors — always ≤ bandwidth.",
  },
  {
    q: "Which device would you use to extend a network by connecting multiple switches and separating broadcast domains?",
    options: ["Hub", "Router", "Repeater", "Media converter"],
    answer: 1,
    explain: "A router connects networks and does not forward broadcasts, so it separates broadcast domains — the tool for segmenting and interconnecting LANs.",
  },
  {
    q: "The process a receiving host uses to strip headers as data moves up the OSI stack is called...",
    options: ["Encapsulation", "Decapsulation", "Fragmentation", "Modulation"],
    answer: 1,
    explain: "Decapsulation is the reverse of encapsulation — each layer removes and processes its header as the PDU moves up from Physical to Application.",
  },
  {
    q: "Which layer of the OSI model is responsible for path determination and logical addressing?",
    options: ["Data Link", "Network", "Transport", "Session"],
    answer: 1,
    explain: "The Network layer (Layer 3) assigns logical (IP) addresses and determines the best path (routing) between networks.",
  },
  {
    q: "A group of computers and devices in a single building sharing a switch is best described as a...",
    options: ["WAN", "LAN", "MAN", "PAN"],
    answer: 1,
    explain: "A LAN (Local Area Network) covers a limited area such as a building or campus and is typically privately owned.",
  },
  {
    q: "Which two devices are most associated with breaking up collision domains and broadcast domains, respectively?",
    options: [
      "Hub and repeater",
      "Switch and router",
      "Router and hub",
      "Bridge and hub",
    ],
    answer: 1,
    explain: "A switch creates a separate collision domain per port; a router separates broadcast domains. Together they structure a modern network.",
  },
  {
    q: "What does a 'protocol suite' such as TCP/IP refer to?",
    options: [
      "A single protocol",
      "A collection of related protocols that work together",
      "A brand of hardware",
      "A type of cable",
    ],
    answer: 1,
    explain: "A protocol suite is a set of cooperating protocols (e.g., TCP/IP includes IP, TCP, UDP, ICMP, ARP) that together provide end-to-end communication.",
  },
  {
    q: "In the troubleshooting model, after implementing a solution you should next...",
    options: [
      "Document immediately and stop",
      "Verify full system functionality and implement preventive measures",
      "Establish a new theory",
      "Escalate to the vendor",
    ],
    answer: 1,
    explain: "Step 6 is to verify full functionality (and add preventive measures) before the final documentation step.",
  },
  {
    q: "Which is an example of a logical (not physical) network component?",
    options: ["A switch", "An IP subnet / VLAN", "A patch cable", "A NIC"],
    answer: 1,
    explain: "IP subnets and VLANs are logical constructs defined in software/configuration, whereas switches, cables, and NICs are physical components.",
  },
  {
    q: "Which OSI layer would encryption via TLS most closely be associated with?",
    options: ["Physical", "Presentation", "Network", "Data Link"],
    answer: 1,
    explain: "Encryption, compression, and format translation are Presentation-layer (Layer 6) functions; TLS is commonly mapped here (spanning Session/Presentation).",
  },
  {
    q: "A network administrator wants a design where the failure of any single link never isolates a site. Which topology best fits?",
    options: ["Bus", "Star", "Mesh", "Ring"],
    answer: 2,
    explain: "A mesh provides multiple redundant paths, so any single link failure leaves alternate routes — maximizing fault tolerance (common in WAN cores).",
  },
  {
    q: "Which statement about switches is TRUE?",
    options: [
      "They forward all frames out every port like a hub",
      "They learn MAC addresses and forward frames only out the correct port",
      "They operate at Layer 3 using IP addresses",
      "They cannot separate collision domains",
    ],
    answer: 1,
    explain: "A switch builds a MAC address table and forwards each frame only out the port where the destination lives, reducing collisions.",
  },
  {
    q: "Which best describes the role of the Session layer?",
    options: [
      "Encrypts data",
      "Sets up, manages, and tears down dialogs between applications",
      "Routes packets",
      "Places bits on the wire",
    ],
    answer: 1,
    explain: "The Session layer (Layer 5) establishes, maintains, and terminates communication sessions between applications.",
  },
  {
    q: "What is the primary purpose of a default gateway from a host's perspective?",
    options: [
      "To resolve hostnames",
      "To reach destinations outside the local subnet",
      "To assign IP addresses",
      "To provide DNS",
    ],
    answer: 1,
    explain: "A host sends traffic destined for other networks to its default gateway (a router interface), which forwards it toward the destination.",
  },
  {
    q: "Which pair correctly matches an application to its typical role?",
    options: [
      "Web browser = server, web server = client",
      "Web browser = client, web server = server",
      "Both are servers",
      "Both are clients",
    ],
    answer: 1,
    explain: "The browser is the client (requests pages); the web server responds. Client/server roles are defined by who initiates the request.",
  },
  {
    q: "A technician replaces a faulty cable and the link comes up. Which final step should not be skipped?",
    options: [
      "Reboot every device",
      "Document the findings, actions, and outcome",
      "Change all IP addresses",
      "Disable the port",
    ],
    answer: 1,
    explain: "Documentation (the last troubleshooting step) records what was wrong and how it was fixed, aiding future troubleshooting and knowledge sharing.",
  },
  {
    q: "Which is a Layer 4 (Transport) responsibility?",
    options: [
      "Assigning MAC addresses",
      "End-to-end delivery, segmentation, and using port numbers",
      "Routing between networks",
      "Encoding bits on the medium",
    ],
    answer: 1,
    explain: "The Transport layer handles end-to-end delivery, segments data, and uses ports (TCP/UDP) to direct data to the right application.",
  },
  {
    q: "Which of the following is NOT typically a benefit of networking?",
    options: [
      "Sharing files and printers",
      "Centralized management",
      "Communication between users",
      "Eliminating the need for any security",
    ],
    answer: 3,
    explain: "Networking increases the need for security (more attack surface), it doesn't eliminate it. The other options are genuine benefits.",
  },
  {
    q: "What does a repeater do?",
    options: [
      "Routes packets between networks",
      "Regenerates/amplifies a signal to extend its distance",
      "Assigns IP addresses",
      "Filters traffic by port",
    ],
    answer: 1,
    explain: "A repeater (a Layer 1 device) boosts a weakening signal so it can travel farther, extending a segment beyond normal distance limits.",
  },
  {
    q: "Which OSI layer would you associate with a Layer 3 switch's routing capability?",
    options: ["Layer 2", "Layer 3", "Layer 4", "Layer 7"],
    answer: 1,
    explain: "A Layer 3 (multilayer) switch performs routing at Layer 3 (using IP) in addition to Layer 2 switching, enabling fast inter-VLAN routing.",
  },
  {
    q: "In which model is there no dedicated server and each host can act as both client and server?",
    options: ["Client-server", "Peer-to-peer", "Three-tier", "Mainframe"],
    answer: 1,
    explain: "In peer-to-peer, each host can share resources (server role) and request them (client role) without a central server.",
  },
  {
    q: "Which best describes the Internet?",
    options: [
      "A single large LAN",
      "A global interconnection of many networks (a network of networks)",
      "A wireless PAN",
      "A private corporate network",
    ],
    answer: 1,
    explain: "The Internet is a worldwide collection of interconnected networks — literally an 'inter-network' — communicating via TCP/IP.",
  },
  {
    q: "The seven-step troubleshooting model's step 4 is to...",
    options: [
      "Identify the problem",
      "Establish a plan of action to resolve the problem and identify potential effects",
      "Document findings",
      "Test the theory",
    ],
    answer: 1,
    explain: "After confirming the cause (step 3), step 4 is to establish a plan of action and consider potential effects before implementing.",
  },
  {
    q: "Which cabling/medium is completely immune to electromagnetic interference?",
    options: ["UTP copper", "Coaxial", "Fiber optic", "STP copper"],
    answer: 2,
    explain: "Fiber carries light rather than electrical signals, making it immune to EMI/RFI — useful in electrically noisy environments and long runs.",
  },
  {
    q: "Which OSI layer's PDU would contain both source and destination IP addresses?",
    options: ["Frame (L2)", "Packet (L3)", "Segment (L4)", "Bits (L1)"],
    answer: 1,
    explain: "The Network-layer PDU is the packet, whose header carries source and destination IP (logical) addresses.",
  },
  {
    q: "A company wants employees to authenticate once to a central directory for all resources. Which model supports this best?",
    options: ["Peer-to-peer", "Client-server (with a directory/NOS)", "Ad hoc", "Bus"],
    answer: 1,
    explain: "Client-server with a directory service (e.g., Active Directory) centralizes authentication and resource control — impractical in peer-to-peer.",
  },
  {
    q: "Which statement about hubs is correct?",
    options: [
      "They create one collision domain shared by all ports",
      "They forward frames only to the destination port",
      "They operate at Layer 3",
      "They separate broadcast domains",
    ],
    answer: 0,
    explain: "A hub repeats every signal out all ports, so all ports share a single collision domain — causing collisions as the network grows. Switches fixed this.",
  },
  {
    q: "The main reason modern LANs use switches instead of hubs is...",
    options: [
      "Switches are cheaper",
      "Switches reduce collisions by giving each port its own collision domain",
      "Hubs are more secure",
      "Switches don't need power",
    ],
    answer: 1,
    explain: "Switches forward frames intelligently and isolate collision domains per port, dramatically improving performance over shared-media hubs.",
  },
  {
    q: "Which OSI layers are sometimes grouped as the 'upper layers' that deal with application data?",
    options: ["1–3", "5–7", "3–4", "1–2"],
    answer: 1,
    explain: "Layers 5–7 (Session, Presentation, Application) are the 'upper layers,' handling application data; the TCP/IP model merges them into one Application layer.",
  },
  {
    q: "A firewall that also inspects application-layer content operates up to which OSI layer?",
    options: ["Layer 2", "Layer 3", "Layer 4", "Layer 7"],
    answer: 3,
    explain: "A next-generation/application-layer firewall inspects up to Layer 7 (application), enabling app-aware filtering beyond simple IP/port rules.",
  },
  {
    q: "Which of these correctly lists PDUs from Layer 4 down to Layer 1?",
    options: [
      "Segment, Packet, Frame, Bits",
      "Packet, Segment, Bits, Frame",
      "Frame, Packet, Segment, Bits",
      "Bits, Frame, Packet, Segment",
    ],
    answer: 0,
    explain: "Layer 4 = segment, Layer 3 = packet, Layer 2 = frame, Layer 1 = bits.",
  },
  {
    q: "What is a key characteristic of a WAN compared to a LAN?",
    options: [
      "It is always faster",
      "It spans large geographic distances and is usually provided by a service provider",
      "It never uses IP",
      "It is always wireless",
    ],
    answer: 1,
    explain: "WANs cross wide geographic areas and are typically leased/operated by telcos, whereas LANs are local and privately owned.",
  },
  {
    q: "Which term describes the physical or logical arrangement of a network?",
    options: ["Protocol", "Topology", "Encapsulation", "Bandwidth"],
    answer: 1,
    explain: "Topology describes how the network's parts are arranged and connected — physically (cabling/devices) or logically (data flow).",
  },
  {
    q: "Which is the BEST first action when a single user cannot access any network resource but others can?",
    options: [
      "Replace the core switch",
      "Check that user's cable/link, NIC, and IP configuration",
      "Reboot the router",
      "Reinstall the server OS",
    ],
    answer: 1,
    explain: "When only one user is affected, start locally (their cable, NIC, link light, and IP settings) rather than touching shared infrastructure.",
  },
  {
    q: "Which safety practice reduces the risk of electric shock when servicing equipment?",
    options: [
      "Work with the device powered on",
      "Power down and unplug the device before opening it",
      "Wear rubber gloves only",
      "Increase the voltage",
    ],
    answer: 1,
    explain: "Always power off and disconnect equipment before servicing (and be mindful of stored charge in power supplies) to avoid shock.",
  },
  {
    q: "Which describes 'anycast' addressing?",
    options: [
      "One-to-all delivery",
      "One-to-nearest delivery among a group sharing the same address",
      "One-to-one delivery",
      "One-to-group delivery",
    ],
    answer: 1,
    explain: "Anycast routes a request to the topologically nearest of several servers sharing an address — common for DNS root servers and CDNs.",
  },
  {
    q: "Which component gives a computer its network connection and MAC address?",
    options: ["CPU", "NIC", "GPU", "PSU"],
    answer: 1,
    explain: "The NIC (Network Interface Card) provides the physical/data-link connection and holds the burned-in MAC address.",
  },
  {
    q: "The OSI model was developed primarily to...",
    options: [
      "Sell networking hardware",
      "Provide a standard reference framework so different systems can interoperate",
      "Replace TCP/IP",
      "Define cable colors",
    ],
    answer: 1,
    explain: "OSI is a vendor-neutral reference model that standardizes networking functions into layers, promoting interoperability and structured troubleshooting.",
  },
  {
    q: "Which of the following is a Layer 2 address?",
    options: ["IPv4 address", "MAC address", "Port number", "Domain name"],
    answer: 1,
    explain: "The MAC address is a Layer 2 (Data Link) physical address. IP is Layer 3, ports are Layer 4, and domain names are Layer 7 constructs.",
  },
  {
    q: "A star topology's central point of failure can be mitigated by...",
    options: [
      "Removing the switch",
      "Adding a redundant/second core switch and links",
      "Using a bus instead",
      "Disabling STP",
    ],
    answer: 1,
    explain: "Because the central device is a single point of failure, adding a redundant core switch and links (with STP/link aggregation) improves resilience.",
  },
  {
    q: "Which layer ensures data from the sender is readable by the receiver by handling format/character-set translation?",
    options: ["Application", "Presentation", "Transport", "Network"],
    answer: 1,
    explain: "The Presentation layer translates data formats and character sets (and handles encryption/compression) so the Application layer receives usable data.",
  },
  {
    q: "Which describes the relationship between the OSI and TCP/IP models?",
    options: [
      "They are unrelated",
      "TCP/IP is a practical 4-layer model that maps onto the 7-layer OSI reference model",
      "OSI replaced TCP/IP",
      "TCP/IP has more layers than OSI",
    ],
    answer: 1,
    explain: "TCP/IP is the practical model the Internet runs on; its four layers map onto OSI's seven (OSI 5–7 → Application; OSI 1–2 → Link).",
  },
  {
    q: "What is the benefit of describing networks in layers?",
    options: [
      "It makes networks slower",
      "It modularizes functions so each layer can be developed and troubleshot independently",
      "It removes the need for protocols",
      "It eliminates hardware",
    ],
    answer: 1,
    explain: "Layering separates concerns: each layer has a defined role and interface, so changes or faults in one layer don't require reworking the others.",
  }
);
