// ── Module 11 — Network Performance & Recovery · expansion pool ─────────────
QUESTIONS["11"].push(
  {
    q: "QoS is used to...",
    options: [
      "Encrypt traffic",
      "Prioritize certain traffic (e.g., voice/video) to guarantee performance",
      "Assign IP addresses",
      "Provide Wi-Fi",
    ],
    answer: 1,
    explain: "QoS classifies and prioritizes traffic so latency-sensitive apps get preferential treatment during congestion.",
  },
  {
    q: "Latency is best defined as...",
    options: [
      "The amount of data per second",
      "The time delay for data to travel from source to destination",
      "The number of dropped packets",
      "Signal loss over distance",
    ],
    answer: 1,
    explain: "Latency is delay — how long a packet takes to reach its destination, often measured as round-trip time.",
  },
  {
    q: "Jitter refers to...",
    options: [
      "Total bandwidth",
      "Variation in packet delay over time",
      "The number of hops",
      "Cable attenuation",
    ],
    answer: 1,
    explain: "Jitter is inconsistency in latency between packets; high jitter disrupts VoIP/video. Jitter buffers and QoS help.",
  },
  {
    q: "Throughput differs from bandwidth in that throughput is...",
    options: [
      "The theoretical maximum",
      "The actual data rate achieved under real conditions",
      "The cable length",
      "The number of VLANs",
    ],
    answer: 1,
    explain: "Bandwidth is the theoretical max; throughput is the real achieved rate, lower due to overhead, congestion, and errors.",
  },
  {
    q: "Which QoS marking is applied at Layer 3 in the IP header?",
    options: ["DSCP", "MAC", "SSID", "TTL"],
    answer: 0,
    explain: "DSCP (in the IP ToS field) marks packets at Layer 3 for classification; CoS (802.1p) marks at Layer 2.",
  },
  {
    q: "Which QoS approach buffers excess traffic to conform to a rate?",
    options: ["Policing", "Shaping", "Dropping", "Flooding"],
    answer: 1,
    explain: "Traffic shaping buffers/delays excess to a defined rate; policing instead drops (or remarks) traffic that exceeds the rate.",
  },
  {
    q: "Which protocol polls device metrics and receives traps for monitoring?",
    options: ["SNMP", "SMTP", "ARP", "RDP"],
    answer: 0,
    explain: "SNMP polls agents for metrics (CPU, interface stats) and receives traps on events; use SNMPv3 for security.",
  },
  {
    q: "NetFlow/IPFIX is primarily used for...",
    options: [
      "Encrypting traffic",
      "Analyzing traffic flows — who talks to whom, how much, on what ports",
      "Assigning DHCP",
      "Cabling",
    ],
    answer: 1,
    explain: "Flow technologies export conversation metadata, giving visibility into bandwidth consumers and traffic patterns.",
  },
  {
    q: "Syslog is used to...",
    options: [
      "Centralize log messages from devices to a collector",
      "Route packets",
      "Assign VLANs",
      "Terminate fiber",
    ],
    answer: 0,
    explain: "Syslog sends event/log messages from devices to a central server for aggregation, retention, and analysis (often feeding a SIEM).",
  },
  {
    q: "Port mirroring (SPAN) is used to...",
    options: [
      "Copy traffic to a monitoring port for analysis",
      "Double network speed",
      "Assign IPs",
      "Provide PoE",
    ],
    answer: 0,
    explain: "A SPAN/mirror port duplicates traffic to a port where a sniffer or IDS can analyze it without disrupting the flow.",
  },
  {
    q: "A First-Hop Redundancy Protocol like HSRP/VRRP provides...",
    options: [
      "Faster DNS",
      "A virtual/redundant default gateway so hosts keep connectivity if a router fails",
      "More IP addresses",
      "Wi-Fi roaming",
    ],
    answer: 1,
    explain: "FHRPs share a virtual gateway IP/MAC across routers; if the active router fails, a standby takes over transparently.",
  },
  {
    q: "Spanning Tree Protocol prevents...",
    options: [
      "IP conflicts",
      "Layer 2 switching loops (and broadcast storms) in redundant topologies",
      "Wi-Fi interference",
      "DNS poisoning",
    ],
    answer: 1,
    explain: "STP blocks redundant paths to prevent loops/broadcast storms while keeping a backup path ready if the active link fails.",
  },
  {
    q: "Link aggregation (LACP/EtherChannel) provides...",
    options: [
      "One logical link with more bandwidth and redundancy from multiple physical links",
      "One link split into many VLANs",
      "Encryption",
      "IP assignment",
    ],
    answer: 0,
    explain: "Link aggregation bundles several physical links into one logical channel, increasing throughput and adding redundancy.",
  },
  {
    q: "A UPS provides...",
    options: [
      "Permanent power for weeks",
      "Battery backup for short outages and time for graceful shutdown or generator start",
      "Cooling",
      "Internet access",
    ],
    answer: 1,
    explain: "A UPS supplies battery power during brief outages and conditions power, bridging until a generator starts or systems shut down cleanly.",
  },
  {
    q: "RAID 1 uses which method?",
    options: ["Striping (no redundancy)", "Mirroring", "Double parity", "Compression"],
    answer: 1,
    explain: "RAID 1 mirrors identical data on two drives; either can fail without data loss (usable capacity is half the raw total).",
  },
  {
    q: "RAID 5 provides fault tolerance via...",
    options: [
      "Mirroring only",
      "Striping with distributed parity (survives one drive failure, needs 3+ drives)",
      "No redundancy",
      "Double parity",
    ],
    answer: 1,
    explain: "RAID 5 stripes data with distributed parity; it tolerates one drive failure and requires at least three drives.",
  },
  {
    q: "Which statement about RAID is TRUE?",
    options: [
      "RAID is a backup",
      "RAID protects against drive failure but is not a substitute for backups",
      "RAID prevents ransomware",
      "RAID encrypts data",
    ],
    answer: 1,
    explain: "RAID guards against hardware drive failure, but deletion, corruption, and ransomware are written to all disks — backups are still required.",
  },
  {
    q: "A 'hot site' in disaster recovery is...",
    options: [
      "An empty building with power only",
      "A fully equipped, running duplicate ready for near-immediate failover",
      "A backup tape",
      "A cloud region with no data",
    ],
    answer: 1,
    explain: "A hot site is fully operational with hardware, current data, and connectivity — fastest recovery at the highest cost.",
  },
  {
    q: "A 'cold site' is...",
    options: [
      "Fully running with current data",
      "Space, power, and connectivity only; equipment and data must be brought in",
      "A firewall",
      "A backup rotation",
    ],
    answer: 1,
    explain: "A cold site provides the facility but no ready systems or data — cheapest but slowest to activate after a disaster.",
  },
  {
    q: "A differential backup copies...",
    options: [
      "Only changes since the last full backup",
      "Only changes since the last backup of any type",
      "Everything each time",
      "Nothing",
    ],
    answer: 0,
    explain: "A differential backs up all changes since the last full; restore needs the full + the latest differential (simpler than incrementals).",
  },
  {
    q: "An incremental backup copies...",
    options: [
      "Only changes since the last backup of any type",
      "Only changes since the last full",
      "Everything each time",
      "Nothing",
    ],
    answer: 0,
    explain: "An incremental backs up changes since the last backup (full or incremental); restore needs the full + all incrementals in order.",
  },
  {
    q: "Traffic shaping is used to...",
    options: [
      "Drop all traffic",
      "Smooth traffic to a defined rate (buffering bursts) to manage bandwidth and QoS",
      "Encrypt packets",
      "Assign VLANs",
    ],
    answer: 1,
    explain: "Shaping delays/buffers excess traffic to conform to a rate, smoothing bursts (policing drops rather than buffers).",
  },
  {
    q: "A network bottleneck is...",
    options: [
      "A security policy",
      "The point of least capacity that limits overall performance",
      "A backup type",
      "A DNS record",
    ],
    answer: 1,
    explain: "A bottleneck is the constrained resource (slow link, overloaded router/server) that caps end-to-end performance.",
  },
  {
    q: "'Five nines' availability allows roughly how much downtime per year?",
    options: ["~3.65 days", "~8.76 hours", "~5 minutes", "~1 hour"],
    answer: 2,
    explain: "99.999% ('five nines') permits about 5.26 minutes of downtime per year, requiring significant redundancy and fast failover.",
  },
  {
    q: "Load balancing improves performance and availability by...",
    options: [
      "Sending all traffic to one server",
      "Distributing traffic across multiple servers/paths",
      "Encrypting traffic",
      "Disabling redundancy",
    ],
    answer: 1,
    explain: "A load balancer spreads requests across a server pool, improving throughput and letting a failed server drop out without outage.",
  },
  {
    q: "A broadcast storm most directly degrades performance by...",
    options: [
      "Encrypting traffic",
      "Flooding segments with broadcasts (often from a Layer 2 loop), saturating links/CPU",
      "Assigning duplicate IPs",
      "Improving throughput",
    ],
    answer: 1,
    explain: "A broadcast storm — often from a loop without STP — floods segments with broadcasts until connectivity fails.",
  },
  {
    q: "Which metric indicates a link is a congestion bottleneck?",
    options: [
      "Zero utilization",
      "Sustained ~90–100% utilization with rising output drops",
      "A small MAC table",
      "A short DNS TTL",
    ],
    answer: 1,
    explain: "Consistently high utilization with increasing drops/queue depth signals congestion — the link needs more bandwidth, aggregation, or QoS.",
  },
  {
    q: "Which best describes 'failover'?",
    options: [
      "Manually rebuilding a server",
      "Automatic switch to a standby system when the primary fails",
      "Deleting data",
      "Encrypting a link",
    ],
    answer: 1,
    explain: "Failover automatically shifts operation to a redundant component/system on failure, minimizing downtime.",
  },
  {
    q: "In an active-passive cluster, the passive node...",
    options: [
      "Handles half the load",
      "Stands by and takes over if the active node fails",
      "Is powered off permanently",
      "Serves DNS only",
    ],
    answer: 1,
    explain: "Active-passive keeps one node serving while a passive standby monitors and takes over on failure, providing HA.",
  },
  {
    q: "The main reason to test backups (restore drills) is to...",
    options: [
      "Fill disk space",
      "Verify backups are actually recoverable before you need them",
      "Increase bandwidth",
      "Assign IPs",
    ],
    answer: 1,
    explain: "An untested backup may be corrupt or incomplete; periodic restore testing confirms recoverability and validates RTO/RPO.",
  },
  {
    q: "MTTR measures...",
    options: [
      "Average time between failures",
      "Average time to repair/restore a failed component or service",
      "Bandwidth",
      "Number of users",
    ],
    answer: 1,
    explain: "MTTR (Mean Time To Repair) is the average time to diagnose, repair, and restore service; lower MTTR = faster recovery.",
  },
  {
    q: "Which best improves availability by removing single points of failure?",
    options: [
      "One power supply and one uplink",
      "Redundant power supplies, dual uplinks, and redundant devices",
      "Removing monitoring",
      "Using one core switch",
    ],
    answer: 1,
    explain: "Redundant components (PSUs, links, devices) eliminate SPOFs so one failure doesn't cause an outage — a core HA practice.",
  },
  {
    q: "VoIP call quality is most sensitive to...",
    options: [
      "Cable color",
      "Latency, jitter, and packet loss",
      "The number of VLANs",
      "DNS TTL",
    ],
    answer: 1,
    explain: "Real-time voice degrades with latency, jitter, and loss; QoS prioritization and adequate bandwidth keep calls clear.",
  },
  {
    q: "Which QoS mechanism gives voice strict priority over other traffic?",
    options: [
      "Best-effort only",
      "A priority/low-latency queue serviced ahead of other classes",
      "Randomly dropping voice",
      "Disabling QoS",
    ],
    answer: 1,
    explain: "A strict-priority (low-latency) queue services voice first, minimizing its delay/jitter; other classes share remaining bandwidth.",
  },
  {
    q: "Caching (proxy/CDN) improves performance by...",
    options: [
      "Encrypting traffic",
      "Serving frequently requested content locally, cutting latency and upstream bandwidth",
      "Assigning IPs",
      "Replacing backups",
    ],
    answer: 1,
    explain: "Caching stores popular content closer to users (proxy/CDN) so repeat requests are faster and use less WAN bandwidth.",
  },
  {
    q: "Geographic (multi-site) redundancy protects against...",
    options: [
      "A single-site disaster taking down the whole service",
      "Weak passwords",
      "Crosstalk",
      "DNS typos",
    ],
    answer: 0,
    explain: "Distributing systems/data across separate sites ensures a localized disaster doesn't cause total outage — the basis of DR resilience.",
  },
  {
    q: "Which is NOT a valid way to improve availability?",
    options: [
      "Redundant hardware and links",
      "Clustering and failover",
      "Tested backups",
      "Removing all monitoring and logging",
    ],
    answer: 3,
    explain: "Redundancy, clustering, and tested backups improve availability; removing monitoring reduces visibility and hurts prevention/recovery.",
  },
  {
    q: "RPO of 1 hour requires that...",
    options: [
      "Recovery takes exactly 1 hour",
      "Backups/replication run at least hourly (max 1 hour of data loss)",
      "Only one backup ever exists",
      "The site is cold",
    ],
    answer: 1,
    explain: "An RPO of 1 hour means no more than an hour of data may be lost, so backups/replication must occur at least every hour.",
  },
  {
    q: "Which tool continuously graphs interface utilization over time?",
    options: [
      "An SNMP-based NMS (e.g., PRTG, Zabbix, LibreNMS)",
      "A punch-down tool",
      "An OTDR",
      "A crimper",
    ],
    answer: 0,
    explain: "SNMP-based monitoring platforms poll counters and graph utilization/errors/availability — essential for baselining and trend spotting.",
  },
  {
    q: "Cold, warm, and hot spares differ by...",
    options: [
      "Backup site temperature",
      "How ready standby hardware is to replace a failed component",
      "RAID level",
      "QoS class",
    ],
    answer: 1,
    explain: "Spare readiness ranges from cold (on the shelf) to warm (installed, needs activation) to hot (online, auto-takeover), trading cost for speed.",
  },
  {
    q: "Which best describes 'convergence' in a redundant Layer 2 network?",
    options: [
      "Merging VLANs",
      "The time STP takes to recompute a loop-free topology after a change",
      "Encrypting frames",
      "Assigning IPs",
    ],
    answer: 1,
    explain: "STP convergence is the time to reach a stable, loop-free topology after a change; RSTP converges faster than classic STP.",
  },
  {
    q: "A baseline is valuable for performance management because it...",
    options: [
      "Encrypts data",
      "Captures normal metrics so deviations/anomalies stand out",
      "Assigns IPs",
      "Replaces monitoring",
    ],
    answer: 1,
    explain: "A baseline records normal utilization/latency/errors so current performance can be compared to spot anomalies and plan capacity.",
  },
  {
    q: "A generator differs from a UPS in that a generator...",
    options: [
      "Provides instantaneous but brief power",
      "Provides sustained power during extended outages (but takes time to start)",
      "Cools the room",
      "Filters packets",
    ],
    answer: 1,
    explain: "A UPS covers the gap instantly for short outages; a generator provides long-term power but needs seconds to start (the UPS bridges that).",
  },
  {
    q: "Which is a benefit of active-active clustering over active-passive?",
    options: [
      "Standby node sits idle",
      "All nodes handle load, improving utilization and scaling (with failover)",
      "It removes redundancy",
      "It disables monitoring",
    ],
    answer: 1,
    explain: "Active-active uses all nodes for load (better utilization and scale) while still failing over; active-passive keeps a node idle as standby.",
  },
  {
    q: "Which describes 'quality of service' class prioritization order for typical traffic?",
    options: [
      "Bulk data first, voice last",
      "Real-time voice/video prioritized over best-effort bulk data",
      "All traffic equal always",
      "Voice dropped first",
    ],
    answer: 1,
    explain: "QoS prioritizes latency-sensitive voice/video over best-effort bulk traffic (like backups/downloads) during congestion.",
  },
  {
    q: "Which is the FIRST thing to do when a change causes a major outage?",
    options: [
      "Delete the logs",
      "Execute the rollback plan to restore service, then investigate",
      "Blame the vendor",
      "Wait for the next maintenance window",
    ],
    answer: 1,
    explain: "Restore service first via the rollback/back-out plan, then perform root-cause analysis once users are back online.",
  },
  {
    q: "Redundant links between two switches require STP (or similar) to...",
    options: [
      "Increase collisions",
      "Prevent a loop while keeping a backup path ready",
      "Assign VLANs",
      "Encrypt frames",
    ],
    answer: 1,
    explain: "Without STP, redundant Layer 2 links form a loop/broadcast storm; STP blocks one path and activates it if the primary fails.",
  },
  {
    q: "Which metric pair is used together to describe recovery objectives?",
    options: [
      "RTO and RPO",
      "MTU and TTL",
      "SSID and BSSID",
      "AH and ESP",
    ],
    answer: 0,
    explain: "RTO (how fast to restore) and RPO (how much data loss is acceptable) together define disaster-recovery targets.",
  }
);
