// ── Module 10 — Security in Network Design (45) ─────────────────────────────
QUESTIONS["10"] = [
  {
    q: "The primary purpose of a firewall is to...",
    options: [
      "Assign IP addresses",
      "Filter traffic between networks based on a rule set (policy)",
      "Resolve domain names",
      "Boost Wi-Fi signal",
    ],
    answer: 1,
    explain: "A firewall enforces a security policy by permitting or denying traffic between network zones based on rules (addresses, ports, protocols, and more).",
  },
  {
    q: "A stateful firewall differs from a stateless (packet-filter) firewall because it...",
    options: [
      "Only checks each packet in isolation",
      "Tracks the state of connections and allows return traffic for established sessions",
      "Cannot use ports",
      "Works only at Layer 1",
    ],
    answer: 1,
    explain: "A stateful firewall maintains a connection table, so it understands sessions and automatically permits legitimate return traffic — smarter than a stateless per-packet filter.",
  },
  {
    q: "An NGFW (Next-Generation Firewall) adds which capabilities over a traditional firewall?",
    options: [
      "Only faster ports",
      "Application awareness, deep packet inspection, IPS, and user/identity-based rules",
      "DHCP only",
      "Cable testing",
    ],
    answer: 1,
    explain: "NGFWs combine stateful filtering with deep packet inspection, application/user awareness, integrated IPS, and threat intelligence for granular, identity-based control.",
  },
  {
    q: "An ACL (Access Control List) on a router/firewall is used to...",
    options: [
      "Encrypt all traffic",
      "Permit or deny traffic based on criteria like source/destination IP, port, and protocol",
      "Assign VLANs",
      "Provide DNS",
    ],
    answer: 1,
    explain: "ACLs are ordered rule lists that filter packets by matching fields (addresses, ports, protocols), permitting or denying them — applied inbound or outbound on interfaces.",
  },
  {
    q: "In an ACL, what typically happens to traffic that matches no explicit rule?",
    options: [
      "It is always permitted",
      "It hits the implicit 'deny all' at the end and is dropped",
      "It is encrypted",
      "It is logged and forwarded",
    ],
    answer: 1,
    explain: "Most ACLs end with an implicit deny-all: traffic not explicitly permitted is denied. Rule order matters because the first match wins.",
  },
  {
    q: "What is the difference between an IDS and an IPS?",
    options: [
      "An IDS blocks traffic; an IPS only alerts",
      "An IDS detects/alerts (passive); an IPS detects and actively blocks (inline)",
      "They are the same",
      "An IPS only works on Wi-Fi",
    ],
    answer: 1,
    explain: "An IDS monitors and alerts on suspicious activity (out-of-band, passive). An IPS sits inline and can actively drop/block malicious traffic in real time.",
  },
  {
    q: "A signature-based detection engine identifies threats by...",
    options: [
      "Matching traffic against known attack patterns",
      "Learning normal behavior and flagging deviations",
      "Encrypting packets",
      "Assigning IPs",
    ],
    answer: 0,
    explain: "Signature-based detection compares activity to a database of known attack patterns — effective for known threats but blind to novel (zero-day) attacks.",
  },
  {
    q: "Anomaly/behavior-based detection is better than signature-based at...",
    options: [
      "Detecting brand-new/unknown attacks by spotting deviations from a baseline",
      "Being 100% free of false positives",
      "Encrypting traffic",
      "Routing packets",
    ],
    answer: 0,
    explain: "Behavior/anomaly detection baselines 'normal' and flags deviations, so it can catch novel attacks — at the cost of more false positives than signature matching.",
  },
  {
    q: "A DMZ (screened subnet) is used to...",
    options: [
      "Store the most sensitive internal data",
      "Host public-facing servers in a segment isolated from the internal LAN",
      "Replace the firewall",
      "Provide DHCP to guests",
    ],
    answer: 1,
    explain: "A DMZ/screened subnet places Internet-facing services (web, mail, DNS) between the outside and the internal network, so a compromise there doesn't directly expose the LAN.",
  },
  {
    q: "NAC (Network Access Control) enforces...",
    options: [
      "Only physical locks",
      "Policy checks (identity, posture/health) before granting a device network access",
      "Faster switching",
      "DNS resolution",
    ],
    answer: 1,
    explain: "NAC verifies who/what is connecting and whether the device meets health/posture requirements (patches, AV) before allowing access — often via 802.1X, quarantining noncompliant devices.",
  },
  {
    q: "The 'AAA' framework stands for...",
    options: [
      "Access, Authorization, Availability",
      "Authentication, Authorization, Accounting",
      "Auditing, Access, Alerting",
      "Authentication, Availability, Auditing",
    ],
    answer: 1,
    explain: "AAA = Authentication (who are you?), Authorization (what may you do?), and Accounting (what did you do?) — the model behind RADIUS and TACACS+.",
  },
  {
    q: "RADIUS and TACACS+ differ in that TACACS+...",
    options: [
      "Uses UDP and encrypts only the password",
      "Uses TCP, encrypts the entire payload, and separates authentication/authorization (favored for device admin)",
      "Is only for Wi-Fi",
      "Provides no accounting",
    ],
    answer: 1,
    explain: "TACACS+ (Cisco) uses TCP 49, encrypts the whole packet, and separates AAA functions — great for granular device administration. RADIUS (UDP) encrypts only the password and is common for network access/802.1X.",
  },
  {
    q: "802.1X provides...",
    options: [
      "Port-based network access control requiring authentication before a port is opened",
      "IP addressing",
      "Route summarization",
      "Cable testing",
    ],
    answer: 0,
    explain: "802.1X authenticates a device/user (supplicant) via an authenticator (switch/AP) to a RADIUS server before allowing traffic on the port — foundational for wired/wireless NAC.",
  },
  {
    q: "Port security on a switch is used to...",
    options: [
      "Encrypt the port",
      "Limit which/how many MAC addresses can use a port, mitigating MAC flooding and rogue devices",
      "Assign IP addresses",
      "Increase speed",
    ],
    answer: 1,
    explain: "Port security restricts a port to specific or a maximum number of MAC addresses, taking action (shutdown/restrict) on violations — defending against MAC flooding and unauthorized devices.",
  },
  {
    q: "DHCP snooping protects against...",
    options: [
      "Fiber attenuation",
      "Rogue/unauthorized DHCP servers by trusting only designated ports",
      "Slow DNS",
      "Weak Wi-Fi",
    ],
    answer: 1,
    explain: "DHCP snooping marks uplink ports 'trusted' and drops DHCP server responses from 'untrusted' access ports, blocking rogue DHCP servers and building a binding table used by DAI/IPSG.",
  },
  {
    q: "Dynamic ARP Inspection (DAI) mitigates...",
    options: [
      "ARP spoofing/poisoning (MITM)",
      "DNS tunneling",
      "Wi-Fi jamming",
      "Cable crosstalk",
    ],
    answer: 0,
    explain: "DAI validates ARP packets against the DHCP snooping binding table, dropping forged ARP replies — preventing ARP-poisoning man-in-the-middle attacks.",
  },
  {
    q: "A proxy server (forward proxy) provides...",
    options: [
      "Routing between VLANs",
      "Content filtering, caching, and anonymity for internal clients accessing the Internet",
      "DHCP leases",
      "Physical security",
    ],
    answer: 1,
    explain: "A forward proxy sits between clients and the Internet, enabling URL/content filtering, caching, logging, and hiding internal client addresses.",
  },
  {
    q: "A SIEM system is used to...",
    options: [
      "Assign IP addresses",
      "Aggregate, correlate, and analyze logs/events from many sources for security monitoring and alerting",
      "Terminate fiber",
      "Provide Wi-Fi",
    ],
    answer: 1,
    explain: "A SIEM (Security Information and Event Management) centralizes logs, correlates events across systems, and generates alerts/dashboards for detection, investigation, and compliance.",
  },
  {
    q: "The 'zero trust' security model is based on...",
    options: [
      "Trusting everything inside the perimeter",
      "'Never trust, always verify' — authenticate/authorize every request regardless of location",
      "Removing all authentication",
      "Using one shared password",
    ],
    answer: 1,
    explain: "Zero trust assumes no implicit trust based on network location; every access is continuously verified (identity, device posture, least privilege), shrinking lateral-movement risk.",
  },
  {
    q: "Segmenting the network for security (e.g., separating IoT, guests, and servers) primarily...",
    options: [
      "Speeds up DNS",
      "Contains breaches and limits lateral movement between zones",
      "Removes the need for a firewall",
      "Increases broadcast domains uselessly",
    ],
    answer: 1,
    explain: "Security segmentation isolates sensitive systems and risky devices, so a compromise in one zone (e.g., IoT) can't freely reach others — reducing lateral movement.",
  },
  {
    q: "A UTM (Unified Threat Management) appliance combines...",
    options: [
      "Only a switch and router",
      "Multiple security functions (firewall, IPS, antivirus, content filter, VPN) in one device",
      "Only Wi-Fi and DHCP",
      "Cabling tools",
    ],
    answer: 1,
    explain: "UTM consolidates several security features into a single appliance — convenient for smaller organizations, though it can become a single point of failure/bottleneck.",
  },
  {
    q: "Disabling unused switch ports is a hardening step that...",
    options: [
      "Increases speed",
      "Prevents unauthorized devices from simply plugging in and gaining access",
      "Improves DNS",
      "Adds VLANs",
    ],
    answer: 1,
    explain: "Shutting down unused ports (and placing them in an unused VLAN) stops an intruder from connecting to a live port in a lobby or empty office to reach the network.",
  },
  {
    q: "A jump box/bastion host in a secure design is used to...",
    options: [
      "Serve public web pages",
      "Provide a single hardened, audited entry point for administering internal systems",
      "Store backups",
      "Assign IP addresses",
    ],
    answer: 1,
    explain: "Admins connect to a hardened, monitored jump box first, then reach internal management interfaces — concentrating and logging privileged access through one controlled chokepoint.",
  },
  {
    q: "Which practice reduces the risk of default-credential attacks on network devices?",
    options: [
      "Leaving factory passwords in place",
      "Changing default usernames/passwords and disabling unused default accounts",
      "Publishing the credentials",
      "Using 'admin/admin' everywhere",
    ],
    answer: 1,
    explain: "Default credentials are publicly known and heavily targeted. Changing them (and disabling unused accounts/services) is a fundamental hardening step.",
  },
  {
    q: "A screened subnet typically uses how many firewall boundaries to isolate public servers?",
    options: [
      "None",
      "Firewalls/interfaces separating the Internet, the DMZ, and the internal network",
      "Only a hub",
      "Only wireless",
    ],
    answer: 1,
    explain: "A screened subnet (DMZ) sits behind firewall interfaces so traffic from the Internet reaches DMZ servers but not the internal LAN, and internal-to-DMZ access is also controlled.",
  },
  {
    q: "Which attack does STP BPDU Guard help prevent?",
    options: [
      "A rogue switch injecting BPDUs to manipulate the spanning tree",
      "DNS poisoning",
      "Wi-Fi deauth",
      "SQL injection",
    ],
    answer: 0,
    explain: "BPDU Guard disables an access (PortFast) port that receives a BPDU, stopping an unauthorized switch from participating in/hijacking the spanning tree topology.",
  },
  {
    q: "MAC filtering as a security control is...",
    options: [
      "Unbreakable",
      "A weak control since MACs can be spoofed, but useful as a minor layer",
      "The strongest possible defense",
      "Only for fiber",
    ],
    answer: 1,
    explain: "MAC filtering allows/denies specific hardware addresses, but attackers can spoof an allowed MAC. It's a minor layer, not a substitute for 802.1X or encryption.",
  },
  {
    q: "A honeynet is...",
    options: [
      "A production network",
      "A network of honeypots designed to attract and analyze attackers",
      "A backup site",
      "A guest Wi-Fi",
    ],
    answer: 1,
    explain: "A honeynet is a whole decoy network of honeypots used to study attacker behavior and detect intrusions, kept isolated from real production systems.",
  },
  {
    q: "The main security benefit of NAT (as a side effect) is...",
    options: [
      "Encryption of traffic",
      "Hiding internal private addresses from the public Internet",
      "Faster routing",
      "Automatic patching",
    ],
    answer: 1,
    explain: "NAT masks internal private IPs behind a public address, providing a degree of obscurity/inbound-blocking. It is not a substitute for a real firewall, though.",
  },
  {
    q: "Content/URL filtering is typically used to...",
    options: [
      "Speed up the CPU",
      "Block access to malicious or policy-violating websites/categories",
      "Assign VLANs",
      "Resolve MAC addresses",
    ],
    answer: 1,
    explain: "URL/content filters (often on a proxy or NGFW) block categories of sites (malware, phishing, inappropriate content), enforcing acceptable-use policy and reducing web-borne threats.",
  },
  {
    q: "Which is the BEST practice for administrative access to network devices?",
    options: [
      "Telnet with shared passwords",
      "SSH with individual accounts, MFA where possible, and role-based authorization via AAA",
      "HTTP web console open to the Internet",
      "No authentication on the LAN",
    ],
    answer: 1,
    explain: "Use encrypted SSH, unique per-admin accounts, MFA, and centralized AAA (TACACS+/RADIUS) with least-privilege roles and logging — never plaintext Telnet or shared logins.",
  },
  {
    q: "A WAF (Web Application Firewall) specifically protects against...",
    options: [
      "Physical theft",
      "Application-layer web attacks like SQL injection and XSS",
      "Cable faults",
      "Wi-Fi interference",
    ],
    answer: 1,
    explain: "A WAF inspects HTTP/HTTPS traffic to a web app and blocks application-layer attacks (SQLi, XSS, CSRF) that a traditional network firewall wouldn't catch.",
  },
  {
    q: "Placing IoT/OT devices on their own VLAN with restricted ACLs is an example of...",
    options: [
      "Reducing security",
      "Microsegmentation/isolation to limit exposure of vulnerable devices",
      "Route summarization",
      "DNS caching",
    ],
    answer: 1,
    explain: "Isolating often-insecure IoT/OT devices on dedicated segments with tight ACLs limits what they can reach (and what can reach them), containing their inherent risk.",
  },
  {
    q: "The purpose of logging and monitoring in a secure design is to...",
    options: [
      "Slow the network",
      "Enable detection, investigation, and accountability for security events",
      "Replace firewalls",
      "Assign IPs",
    ],
    answer: 1,
    explain: "Comprehensive logging (feeding a SIEM) provides visibility to detect attacks, investigate incidents, and hold accounts accountable — you can't defend what you can't see.",
  },
  {
    q: "Geofencing/geo-IP blocking is used to...",
    options: [
      "Improve cable quality",
      "Restrict access based on geographic location of the source",
      "Assign subnet masks",
      "Encrypt DNS",
    ],
    answer: 1,
    explain: "Geo-blocking denies or allows traffic based on the source country/region, reducing exposure to regions with no legitimate business need — one layer among many.",
  },
  {
    q: "A 'security posture assessment' evaluates...",
    options: [
      "The color of the cables",
      "The overall state of an organization's security controls and readiness",
      "Only Wi-Fi channels",
      "The DNS TTL",
    ],
    answer: 1,
    explain: "A posture assessment reviews policies, controls, configurations, and practices to gauge overall security maturity and identify gaps to remediate.",
  },
  {
    q: "Egress filtering on a firewall is used to...",
    options: [
      "Block only inbound traffic",
      "Control/inspect outbound traffic (e.g., stop data exfiltration and block malware call-home)",
      "Assign VLANs",
      "Provide PoE",
    ],
    answer: 1,
    explain: "Egress filtering restricts outbound traffic to expected destinations/ports, helping detect and stop data exfiltration, malware command-and-control, and spoofed source addresses.",
  },
  {
    q: "Which control most directly prevents rogue access points on the corporate LAN?",
    options: [
      "Wireless intrusion prevention (WIPS) plus 802.1X on switch ports",
      "Longer DHCP leases",
      "Bigger subnets",
      "Disabling logging",
    ],
    answer: 0,
    explain: "WIPS detects/contains unauthorized APs over the air, while 802.1X/port security stops an unauthorized AP plugged into a wired port from gaining network access.",
  },
  {
    q: "Which is an example of a 'detective' control (vs preventive)?",
    options: [
      "A locked door",
      "Security camera footage / IDS alerts that identify an incident after it occurs",
      "A firewall rule",
      "Encryption",
    ],
    answer: 1,
    explain: "Detective controls (cameras, IDS, log review, audits) reveal that an event happened. Preventive controls (locks, firewalls, encryption) stop it from happening in the first place.",
  },
  {
    q: "IP Source Guard on a switch prevents...",
    options: [
      "IP address spoofing by validating source IP/MAC against the DHCP snooping table",
      "Fiber loss",
      "Wi-Fi jamming",
      "Slow DNS",
    ],
    answer: 0,
    explain: "IP Source Guard uses the DHCP snooping binding table to permit only traffic whose source IP/MAC matches a legitimate binding, blocking IP-spoofing on access ports.",
  },
  {
    q: "A key reason to place the management interfaces of network devices in a separate, restricted VLAN/subnet is to...",
    options: [
      "Improve Wi-Fi range",
      "Prevent unauthorized users from reaching device administration, reducing attack surface",
      "Increase broadcast traffic",
      "Speed up file transfers",
    ],
    answer: 1,
    explain: "An isolated management network limits who can even attempt to reach device admin interfaces, containing that highly sensitive access to authorized admins only.",
  },
  {
    q: "Which combination BEST embodies 'defense in depth' at the network edge?",
    options: [
      "A single ACL",
      "Perimeter firewall + IPS + DMZ segmentation + secure remote access (VPN/MFA) + monitoring",
      "Only antivirus on one PC",
      "Only a strong Wi-Fi password",
    ],
    answer: 1,
    explain: "Layering firewall, IPS, DMZ segmentation, hardened/MFA remote access, and monitoring means no single control failure exposes the whole network — the essence of defense in depth.",
  },
  {
    q: "The role of a VPN concentrator in secure network design is to...",
    options: [
      "Assign DHCP",
      "Terminate and manage many encrypted VPN tunnels for remote users/sites",
      "Filter web content",
      "Provide Wi-Fi",
    ],
    answer: 1,
    explain: "A VPN concentrator (often a firewall feature) centralizes termination of numerous VPN tunnels, handling their authentication and encryption at the network edge.",
  },
  {
    q: "Which is TRUE about an IPS placement relative to an IDS?",
    options: [
      "An IPS is placed out-of-band via a SPAN/mirror port",
      "An IPS is placed inline so it can block traffic; an IDS is often out-of-band (mirror/tap) and only alerts",
      "Both must be out-of-band",
      "Neither can block",
    ],
    answer: 1,
    explain: "Because an IPS must actively drop malicious packets, it sits inline in the traffic path. An IDS can watch a copy of traffic (SPAN/tap) out-of-band since it only alerts.",
  },
  {
    q: "Which principle says a system should default to denying access unless explicitly permitted?",
    options: [
      "Implicit allow",
      "Default deny (deny by default / fail-closed)",
      "Open access",
      "Least astonishment",
    ],
    answer: 1,
    explain: "Default deny (fail-closed) blocks everything not explicitly allowed — the safe posture behind firewall rule design and the implicit deny at the end of an ACL. It minimizes accidental exposure.",
  },
];
