// ── Module 04 — Network Protocols · expansion pool ──────────────────────────
QUESTIONS["04"].push(
  {
    q: "Which layer of the TCP/IP model contains HTTP, DNS, and SMTP?",
    options: ["Transport", "Internet", "Application", "Link"],
    answer: 2,
    explain: "In the four-layer TCP/IP model, HTTP, DNS, and SMTP are Application-layer protocols (mapping to OSI layers 5–7).",
  },
  {
    q: "Which field in the IPv4 header prevents packets from looping forever?",
    options: ["Checksum", "TTL (Time To Live)", "Protocol", "Flags"],
    answer: 1,
    explain: "Each router decrements TTL; at zero the packet is dropped and an ICMP 'time exceeded' is returned — traceroute exploits this.",
  },
  {
    q: "Which IPv4 header field identifies whether the payload is TCP, UDP, or ICMP?",
    options: ["Protocol", "TTL", "Options", "Version"],
    answer: 0,
    explain: "The Protocol field (e.g., 6=TCP, 17=UDP, 1=ICMP) tells the receiver which upper-layer handler to pass the payload to.",
  },
  {
    q: "What does the TCP window size control?",
    options: [
      "The MTU",
      "How much unacknowledged data a sender may have in flight (flow control)",
      "The TTL",
      "The port number",
    ],
    answer: 1,
    explain: "The advertised window (flow control) limits outstanding unacknowledged data so the receiver isn't overwhelmed.",
  },
  {
    q: "Which protocol provides connectionless, best-effort datagram delivery?",
    options: ["TCP", "UDP", "SCTP", "HTTP"],
    answer: 1,
    explain: "UDP is connectionless and best-effort — no handshake, sequencing, or acknowledgments — favoring low latency.",
  },
  {
    q: "Which application would most likely use TCP rather than UDP?",
    options: ["Live VoIP audio", "DNS lookup", "Downloading a software update", "Video streaming"],
    answer: 2,
    explain: "A software download requires every byte in order, so TCP's reliability is essential; the others favor UDP's speed.",
  },
  {
    q: "SNMP uses which ports for polling and traps respectively?",
    options: ["161 and 162", "80 and 443", "20 and 21", "137 and 138"],
    answer: 0,
    explain: "SNMP managers poll agents on UDP 161; agents send traps to the manager on UDP 162.",
  },
  {
    q: "Which SNMP version should be used for authentication and encryption?",
    options: ["SNMPv1", "SNMPv2c", "SNMPv3", "SNMPv0"],
    answer: 2,
    explain: "SNMPv3 adds authentication, integrity, and encryption; v1 and v2c rely on plaintext community strings.",
  },
  {
    q: "Which protocol securely tunnels traffic at Layer 3 to build VPNs?",
    options: ["IPsec", "HTTP", "ARP", "STP"],
    answer: 0,
    explain: "IPsec authenticates and encrypts IP packets at Layer 3, forming the basis of many site-to-site and remote-access VPNs.",
  },
  {
    q: "In IPsec, which component provides confidentiality (encryption) of the payload?",
    options: ["AH", "ESP", "IKE only", "GRE"],
    answer: 1,
    explain: "ESP (Encapsulating Security Payload) encrypts (and can authenticate) the payload; AH provides integrity/authentication without encryption.",
  },
  {
    q: "Which key-exchange protocol negotiates IPsec security associations?",
    options: ["IKE", "ARP", "ICMP", "LDAP"],
    answer: 0,
    explain: "IKE (Internet Key Exchange) negotiates keys and security associations used by IPsec's AH/ESP.",
  },
  {
    q: "Which protocol is used to synchronize device clocks?",
    options: ["NTP", "SNMP", "SMTP", "TFTP"],
    answer: 0,
    explain: "NTP (UDP 123) keeps clocks aligned — critical for logging, certificate validation, and Kerberos.",
  },
  {
    q: "Kerberos, the default authentication protocol in Active Directory, uses which port?",
    options: ["88", "389", "443", "53"],
    answer: 0,
    explain: "Kerberos uses port 88 (UDP/TCP) for ticket-based mutual authentication in Windows domains.",
  },
  {
    q: "Which statement about QUIC is TRUE?",
    options: [
      "It runs over TCP",
      "It runs over UDP and underpins HTTP/3 with low-latency, encrypted connections",
      "It is unencrypted",
      "It replaces IP",
    ],
    answer: 1,
    explain: "QUIC runs over UDP, multiplexes streams, and is encrypted by default; HTTP/3 is built on it, cutting handshake latency vs TCP+TLS.",
  },
  {
    q: "Which protocol maps IPv4 addresses to MAC addresses on a local segment?",
    options: ["ARP", "DNS", "DHCP", "ICMP"],
    answer: 0,
    explain: "ARP broadcasts a request for the MAC that owns an IP; the owner replies. It stays within the local broadcast domain.",
  },
  {
    q: "Which protocol/message type does ping rely on?",
    options: ["TCP SYN", "ICMP Echo Request/Reply", "UDP datagram", "ARP request"],
    answer: 1,
    explain: "ping sends ICMP Echo Requests and expects Echo Replies to test reachability and measure round-trip time.",
  },
  {
    q: "Which secure protocol replaces Telnet for encrypted remote CLI access?",
    options: ["SSH", "FTP", "SNMP", "SMTP"],
    answer: 0,
    explain: "SSH (TCP 22) encrypts the entire session, replacing the plaintext Telnet (23).",
  },
  {
    q: "SFTP differs from FTPS in that SFTP...",
    options: [
      "Uses SSH as its transport",
      "Uses TLS over classic FTP",
      "Is unencrypted",
      "Uses UDP",
    ],
    answer: 0,
    explain: "SFTP is a distinct protocol running over SSH, while FTPS is traditional FTP wrapped in TLS. Both encrypt transfers but differ mechanically.",
  },
  {
    q: "Which lightweight, unauthenticated protocol is often used to transfer router/switch configs on a trusted LAN?",
    options: ["TFTP", "HTTPS", "SFTP", "SMTP"],
    answer: 0,
    explain: "TFTP (UDP 69) is simple and connectionless with no authentication, common for IOS images/configs on protected networks.",
  },
  {
    q: "Which protocol carries email between mail servers?",
    options: ["POP3", "IMAP", "SMTP", "SNMP"],
    answer: 2,
    explain: "SMTP sends and relays mail between servers; POP3/IMAP retrieve mail to a client.",
  },
  {
    q: "Which retrieval protocol keeps messages on the server and synchronizes across devices?",
    options: ["POP3", "IMAP", "SMTP", "TFTP"],
    answer: 1,
    explain: "IMAP keeps mail server-side and syncs state (read/unread, folders) across multiple devices; POP3 typically downloads and removes it.",
  },
  {
    q: "Which protocol provides a full graphical remote desktop to a Windows host?",
    options: ["SSH", "RDP", "VNC over SSH", "Telnet"],
    answer: 1,
    explain: "RDP (TCP 3389) delivers a remote graphical Windows session; it should be protected behind a VPN/gateway with MFA.",
  },
  {
    q: "Which TCP flag combination indicates the start of a connection request?",
    options: ["SYN only", "SYN-ACK", "ACK only", "FIN"],
    answer: 0,
    explain: "The client sends a segment with only the SYN flag set to begin the three-way handshake.",
  },
  {
    q: "What does an RST (reset) segment indicate?",
    options: [
      "A graceful close",
      "An abrupt termination of the connection",
      "A retransmission",
      "A keepalive",
    ],
    answer: 1,
    explain: "RST abruptly aborts a connection — often sent when a port is closed or an unexpected segment arrives.",
  },
  {
    q: "Which pairing is correct?",
    options: [
      "HTTP → 443, HTTPS → 80",
      "HTTP → 80, HTTPS → 443",
      "HTTP → 8080 only, HTTPS → 22",
      "HTTP → 21, HTTPS → 20",
    ],
    answer: 1,
    explain: "HTTP uses TCP 80; HTTPS (HTTP over TLS) uses TCP 443.",
  },
  {
    q: "Which protocol lets you query and modify directory objects like users and groups?",
    options: ["LDAP", "SNMP", "SMTP", "ICMP"],
    answer: 0,
    explain: "LDAP (389; LDAPS 636) accesses directory services such as Active Directory or OpenLDAP.",
  },
  {
    q: "A reverse proxy sits in front of...",
    options: [
      "Clients, to filter their web access",
      "Servers, handling requests, load balancing, and TLS termination",
      "Switches only",
      "DNS resolvers",
    ],
    answer: 1,
    explain: "A reverse proxy fronts servers — distributing load, terminating TLS, caching. A forward proxy fronts clients.",
  },
  {
    q: "Which tool captures and decodes packets layer by layer for protocol analysis?",
    options: ["Wireshark", "ipconfig", "ping", "arp"],
    answer: 0,
    explain: "Wireshark (and tcpdump) capture frames and decode each layer, invaluable for troubleshooting and security analysis.",
  },
  {
    q: "The purpose of TLS certificates is to...",
    options: [
      "Speed up the connection",
      "Authenticate the server (and optionally client) and enable encrypted sessions",
      "Assign IP addresses",
      "Route packets",
    ],
    answer: 1,
    explain: "TLS certificates bind a public key to an identity, letting clients verify the server and establish an encrypted session.",
  },
  {
    q: "In a full-tunnel VPN, which traffic goes through the tunnel?",
    options: [
      "Only corporate-bound traffic",
      "All of the client's traffic",
      "Only DNS",
      "None",
    ],
    answer: 1,
    explain: "Full tunnel routes all client traffic through the VPN (more secure, more load); split tunnel sends only corporate traffic through it.",
  },
  {
    q: "Which protocol number identifies ICMP in the IPv4 header?",
    options: ["1", "6", "17", "47"],
    answer: 0,
    explain: "ICMP is protocol number 1; TCP is 6, UDP is 17, and GRE is 47.",
  },
  {
    q: "What does 'connection-oriented' mean?",
    options: [
      "No session is established",
      "A session is established and maintained with acknowledgments before/while data flows",
      "Data is never acknowledged",
      "It always uses UDP",
    ],
    answer: 1,
    explain: "Connection-oriented protocols (TCP) set up a verified session and track delivery, unlike connectionless UDP.",
  },
  {
    q: "Which two ports does active-mode FTP use?",
    options: ["20 (data) and 21 (control)", "22 and 23", "80 and 443", "67 and 68"],
    answer: 0,
    explain: "FTP uses TCP 21 for control and TCP 20 for data in active mode. Both are unencrypted, so SFTP/FTPS are preferred.",
  },
  {
    q: "Which best describes a socket?",
    options: [
      "A physical port on a switch",
      "The combination of an IP address and a port number",
      "A DNS record",
      "A MAC address",
    ],
    answer: 1,
    explain: "A socket is an endpoint identified by IP:port; a pair of sockets uniquely defines a connection.",
  },
  {
    q: "Which protocol would you use to securely manage a router's CLI over the network?",
    options: ["Telnet", "SSH", "HTTP", "TFTP"],
    answer: 1,
    explain: "SSH provides an encrypted CLI session with key-based authentication — the secure standard for device administration.",
  },
  {
    q: "Which is TRUE about UDP headers compared to TCP headers?",
    options: [
      "UDP headers are larger",
      "UDP headers are smaller/simpler (no sequence/ACK/window fields)",
      "UDP has no ports",
      "UDP includes a handshake field",
    ],
    answer: 1,
    explain: "UDP's 8-byte header carries only source/destination ports, length, and checksum — far simpler than TCP's, giving lower overhead.",
  },
  {
    q: "What is the purpose of a TCP keepalive?",
    options: [
      "To encrypt the session",
      "To verify an idle connection is still alive and free stale connections",
      "To increase MTU",
      "To assign a new port",
    ],
    answer: 1,
    explain: "Keepalives probe idle connections so the stack can detect and clean up dead peers.",
  },
  {
    q: "Which protocol dynamically discovers the IPv6 default gateway via Router Advertisements?",
    options: ["ICMPv6/NDP", "ARP", "DHCPv4", "RIP"],
    answer: 0,
    explain: "Routers send ICMPv6 Router Advertisements (part of NDP) so hosts learn the gateway and prefix, enabling SLAAC.",
  },
  {
    q: "Which of these is an application-layer protocol?",
    options: ["IP", "TCP", "DNS", "Ethernet"],
    answer: 2,
    explain: "DNS is an application-layer protocol. IP is Layer 3, TCP is Layer 4, and Ethernet is Layers 1–2.",
  },
  {
    q: "Which port does Syslog typically use to receive log messages?",
    options: ["514", "123", "161", "636"],
    answer: 0,
    explain: "Syslog commonly uses UDP 514 to receive event/log messages from network devices at a central collector.",
  },
  {
    q: "Why is Telnet considered insecure?",
    options: [
      "It is too slow",
      "It transmits credentials and data in clear text",
      "It uses too much bandwidth",
      "It only works on fiber",
    ],
    answer: 1,
    explain: "Telnet sends everything, including passwords, in plaintext — easily captured by a sniffer. Use SSH instead.",
  },
  {
    q: "A WAF specifically protects against...",
    options: [
      "Cable faults",
      "Application-layer web attacks like SQL injection and XSS",
      "Wi-Fi interference",
      "Power outages",
    ],
    answer: 1,
    explain: "A Web Application Firewall inspects HTTP(S) traffic and blocks app-layer attacks a traditional firewall would miss.",
  },
  {
    q: "Which describes the DNS query flow for an uncached name?",
    options: [
      "Client → authoritative only",
      "Client → recursive resolver → root → TLD → authoritative → answer (then cached)",
      "Client → switch → done",
      "Client → DHCP → done",
    ],
    answer: 1,
    explain: "A recursive resolver walks the hierarchy (root → TLD → authoritative) and caches the result per its TTL.",
  },
  {
    q: "What does encapsulation add at the Transport layer?",
    options: [
      "Source/destination MAC addresses",
      "Source/destination port numbers",
      "The FCS trailer",
      "The preamble",
    ],
    answer: 1,
    explain: "The Transport-layer header adds port numbers (plus sequence/ACK for TCP) to direct data to the correct application.",
  },
  {
    q: "Which is a reason to choose UDP for DNS queries?",
    options: [
      "Guaranteed delivery",
      "Low overhead and fast single-packet request/response",
      "Built-in encryption",
      "Ordered byte stream",
    ],
    answer: 1,
    explain: "Most DNS lookups fit in one small packet; UDP's low overhead makes it faster than establishing a TCP connection.",
  },
  {
    q: "Which best describes GRE?",
    options: [
      "An encryption cipher",
      "A tunneling protocol that encapsulates various protocols inside IP (often paired with IPsec)",
      "A routing protocol",
      "A DNS record",
    ],
    answer: 1,
    explain: "GRE (Generic Routing Encapsulation) tunnels arbitrary payloads over IP; it lacks encryption, so it's often combined with IPsec.",
  },
  {
    q: "Which statement about ports is correct?",
    options: [
      "Ports identify the physical jack",
      "Well-known ports are 0–1023 and identify standard services",
      "All ports are encrypted",
      "Ports are Layer 2 identifiers",
    ],
    answer: 1,
    explain: "Well-known ports (0–1023) map to standard services (HTTP 80, HTTPS 443, DNS 53). Ports are Transport-layer (Layer 4) identifiers.",
  },
  {
    q: "Which utility tests whether a specific TCP port is open on a remote host?",
    options: [
      "ping",
      "telnet/nc to that port, or nmap",
      "arp",
      "ipconfig",
    ],
    answer: 1,
    explain: "You can probe a TCP port with telnet, netcat (nc), or a scanner like nmap. ping only tests ICMP reachability.",
  },
  {
    q: "Which describes the relationship between HTTP and HTTPS?",
    options: [
      "HTTPS is HTTP without a server",
      "HTTPS is HTTP carried inside a TLS-encrypted session",
      "HTTP is faster because it is encrypted",
      "They use the same port",
    ],
    answer: 1,
    explain: "HTTPS runs HTTP over a TLS session, adding encryption, integrity, and server authentication (port 443 vs HTTP's 80).",
  },
  {
    q: "Which protocol would an admin disable in favor of SNMPv3 to avoid plaintext community strings?",
    options: ["SNMPv2c", "NTP", "DNS", "TFTP"],
    answer: 0,
    explain: "SNMPv1/v2c send community strings in clear text; SNMPv3 replaces them with authenticated, encrypted access.",
  }
);
