// ── Module 03 — Addressing (54) ─────────────────────────────────────────────
QUESTIONS["03"] = [
  {
    q: "How many bits is a MAC address?",
    options: ["32 bits", "48 bits", "64 bits", "128 bits"],
    answer: 1,
    explain: "A MAC address is 48 bits, written as six pairs of hexadecimal digits (e.g., 00:1A:2B:3C:4D:5E). It's a Layer 2 physical address burned into the NIC.",
  },
  {
    q: "In a MAC address, what does the first half (first 24 bits / OUI) identify?",
    options: ["The host serial number", "The manufacturer (vendor) of the NIC", "The IP subnet", "The VLAN ID"],
    answer: 1,
    explain: "The first 24 bits are the OUI (Organizationally Unique Identifier) assigned to the NIC manufacturer. The last 24 bits are the device-specific portion.",
  },
  {
    q: "How many bits is an IPv4 address?",
    options: ["16 bits", "32 bits", "64 bits", "128 bits"],
    answer: 1,
    explain: "IPv4 addresses are 32 bits, written as four decimal octets (0–255) separated by dots, e.g., 192.168.1.10.",
  },
  {
    q: "How many bits is an IPv6 address?",
    options: ["32 bits", "48 bits", "64 bits", "128 bits"],
    answer: 3,
    explain: "IPv6 addresses are 128 bits, written as eight groups of four hex digits separated by colons, e.g., 2001:0db8:85a3::8a2e:0370:7334.",
  },
  {
    q: "The largest value a single IPv4 octet can hold is...",
    options: ["127", "128", "255", "256"],
    answer: 2,
    explain: "Each octet is 8 bits. 8 ones (11111111) = 255. So each octet ranges 0–255, giving 256 possible values per octet.",
  },
  {
    q: "What is the purpose of a default gateway?",
    options: [
      "To resolve domain names",
      "To forward traffic destined for other networks (off-subnet)",
      "To assign IP addresses",
      "To store MAC addresses",
    ],
    answer: 1,
    explain: "The default gateway is the router interface a host sends packets to when the destination is on a different network. It's the exit point from the local subnet.",
  },
  {
    q: "Which protocol resolves an IP address to a MAC address on a local network?",
    options: ["DNS", "ARP", "DHCP", "ICMP"],
    answer: 1,
    explain: "ARP (Address Resolution Protocol) maps a known IPv4 address to its MAC address within the same broadcast domain so frames can be delivered at Layer 2.",
  },
  {
    q: "Which protocol automatically assigns IP addresses, subnet masks, gateways, and DNS to clients?",
    options: ["DNS", "ARP", "DHCP", "SNMP"],
    answer: 2,
    explain: "DHCP (Dynamic Host Configuration Protocol) leases IP configuration to clients automatically, eliminating manual (static) assignment on each host.",
  },
  {
    q: "What are the four DHCP messages, in order?",
    options: [
      "Discover, Offer, Request, Acknowledge (DORA)",
      "Request, Reply, Renew, Release",
      "Sync, Ack, Push, Fin",
      "Hello, Update, Confirm, Close",
    ],
    answer: 0,
    explain: "The DHCP process is DORA: client broadcasts Discover, server sends Offer, client sends Request, server sends Acknowledge (ACK) to finalize the lease.",
  },
  {
    q: "What service translates a domain name like www.example.com into an IP address?",
    options: ["DHCP", "DNS", "NAT", "ARP"],
    answer: 1,
    explain: "DNS (Domain Name System) resolves human-friendly names (FQDNs) to IP addresses so hosts can be reached without memorizing numeric addresses.",
  },
  {
    q: "A fully qualified domain name (FQDN) includes...",
    options: [
      "Only the host name",
      "The host name plus the complete domain path up to the root",
      "Only the IP address",
      "The MAC address",
    ],
    answer: 1,
    explain: "An FQDN specifies the exact location in the DNS hierarchy, e.g., server1.sales.example.com. — host + domain + TLD (and the implied root).",
  },
  {
    q: "Which DNS record maps a hostname to an IPv4 address?",
    options: ["A record", "AAAA record", "MX record", "CNAME record"],
    answer: 0,
    explain: "An A record maps a name to an IPv4 address. AAAA maps to IPv6, MX identifies mail servers, and CNAME creates an alias to another name.",
  },
  {
    q: "Which DNS record maps a hostname to an IPv6 address?",
    options: ["A", "AAAA", "PTR", "TXT"],
    answer: 1,
    explain: "The AAAA ('quad-A') record maps a hostname to a 128-bit IPv6 address, analogous to the A record for IPv4.",
  },
  {
    q: "Which DNS record type is used to identify a domain's mail servers?",
    options: ["MX", "NS", "A", "SRV"],
    answer: 0,
    explain: "The MX (Mail Exchanger) record specifies the mail server(s) responsible for accepting email for a domain, along with priority values.",
  },
  {
    q: "A PTR record is used for...",
    options: [
      "Forward lookups (name to IP)",
      "Reverse lookups (IP to name)",
      "Mail routing",
      "Aliasing",
    ],
    answer: 1,
    explain: "A PTR (pointer) record performs reverse DNS — mapping an IP address back to a hostname, often used in anti-spam checks.",
  },
  {
    q: "Well-known ports fall in which range?",
    options: ["0–1023", "1024–49151", "49152–65535", "0–255"],
    answer: 0,
    explain: "Well-known ports are 0–1023 (e.g., HTTP 80, HTTPS 443, DNS 53). Registered ports are 1024–49151, and dynamic/private (ephemeral) ports are 49152–65535.",
  },
  {
    q: "Which port does HTTPS use by default?",
    options: ["21", "80", "443", "3389"],
    answer: 2,
    explain: "HTTPS (HTTP over TLS/SSL) uses TCP port 443. Plain HTTP uses port 80.",
  },
  {
    q: "Which port does DNS primarily use?",
    options: ["25", "53", "67", "110"],
    answer: 1,
    explain: "DNS uses port 53 (UDP for most queries, TCP for zone transfers and large responses).",
  },
  {
    q: "Which ports does DHCP use?",
    options: ["67 and 68", "20 and 21", "80 and 443", "137 and 138"],
    answer: 0,
    explain: "DHCP servers listen on UDP 67 and clients on UDP 68. (BOOTP shares these ports.)",
  },
  {
    q: "Which port does SSH use?",
    options: ["22", "23", "25", "443"],
    answer: 0,
    explain: "SSH (Secure Shell) uses TCP port 22 for encrypted remote administration. Telnet (unencrypted) uses port 23.",
  },
  {
    q: "The IPv4 range 10.0.0.0 – 10.255.255.255 is...",
    options: ["Public", "Private (RFC 1918)", "Loopback", "Multicast"],
    answer: 1,
    explain: "10.0.0.0/8 is a private (RFC 1918) range, not routable on the public Internet. Others are 172.16.0.0/12 and 192.168.0.0/16.",
  },
  {
    q: "Which of the following is a private IPv4 range?",
    options: ["172.16.0.0 – 172.31.255.255", "8.8.8.0 – 8.8.8.255", "1.1.1.0 – 1.1.1.255", "200.0.0.0 – 200.0.0.255"],
    answer: 0,
    explain: "172.16.0.0/12 (172.16.0.0–172.31.255.255) is one of the three RFC 1918 private ranges, along with 10.0.0.0/8 and 192.168.0.0/16.",
  },
  {
    q: "The IPv4 loopback address is...",
    options: ["0.0.0.0", "127.0.0.1", "255.255.255.255", "169.254.0.1"],
    answer: 1,
    explain: "127.0.0.1 is the IPv4 loopback (localhost), used to test the local TCP/IP stack. The whole 127.0.0.0/8 block is reserved for loopback.",
  },
  {
    q: "An address in the 169.254.x.x range indicates...",
    options: [
      "A correctly configured public address",
      "APIPA — the host failed to reach a DHCP server",
      "A multicast group",
      "The default gateway",
    ],
    answer: 1,
    explain: "169.254.0.0/16 is APIPA (Automatic Private IP Addressing). A host self-assigns one when no DHCP server responds, signaling a DHCP/connectivity problem.",
  },
  {
    q: "What technology lets many private hosts share one public IP address?",
    options: ["DNS", "NAT", "ARP", "STP"],
    answer: 1,
    explain: "NAT (Network Address Translation) translates private source addresses to a public address (and back), conserving public IPv4 addresses. PAT adds port multiplexing.",
  },
  {
    q: "Which command displays IP configuration on a Windows host?",
    options: ["ifconfig", "ipconfig", "ip route", "netstat -r"],
    answer: 1,
    explain: "ipconfig shows IP address, mask, gateway, and (with /all) DNS/DHCP/MAC info on Windows. Linux/macOS use ifconfig or the newer 'ip' command.",
  },
  {
    q: "Which command tests basic reachability by sending ICMP echo requests?",
    options: ["ping", "nslookup", "arp", "tracert"],
    answer: 0,
    explain: "ping sends ICMP Echo Request packets and waits for Echo Replies to test whether a host is reachable and measure round-trip time.",
  },
  {
    q: "Which command traces the routers (hops) a packet passes through to a destination?",
    options: ["ping", "tracert / traceroute", "ipconfig", "nslookup"],
    answer: 1,
    explain: "tracert (Windows) / traceroute (Linux/macOS) reveals each Layer 3 hop to the destination, useful for locating where connectivity breaks or latency spikes.",
  },
  {
    q: "Which command queries DNS to resolve or troubleshoot name resolution?",
    options: ["nslookup / dig", "arp -a", "route print", "ping -t"],
    answer: 0,
    explain: "nslookup (and the more capable dig) query DNS servers directly to resolve names, check record types, and diagnose DNS problems.",
  },
  {
    q: "Which command displays the local ARP cache (IP-to-MAC mappings)?",
    options: ["arp -a", "ping", "nslookup", "tracert"],
    answer: 0,
    explain: "arp -a lists the current IP-to-MAC address mappings the host has cached, useful for diagnosing Layer 2/3 mapping issues.",
  },
  {
    q: "Which command shows active connections and listening ports?",
    options: ["netstat", "ping", "arp", "nslookup"],
    answer: 0,
    explain: "netstat lists active TCP/UDP connections, listening ports, and (with options) routing and interface statistics.",
  },
  {
    q: "The 'all-zeros' address 0.0.0.0 commonly represents...",
    options: [
      "A broadcast to all hosts",
      "'This host' / an unspecified address or default route",
      "The loopback",
      "A multicast group",
    ],
    answer: 1,
    explain: "0.0.0.0 means 'this/any host' (as a source during DHCP) or the default route (0.0.0.0/0) in routing tables — 'everything not otherwise matched.'",
  },
  {
    q: "The limited broadcast address for an IPv4 network is...",
    options: ["0.0.0.0", "127.0.0.1", "255.255.255.255", "224.0.0.1"],
    answer: 2,
    explain: "255.255.255.255 is the limited broadcast address, delivered to all hosts on the local subnet (routers do not forward it).",
  },
  {
    q: "IPv4 addresses in 224.0.0.0 – 239.255.255.255 are...",
    options: ["Private", "Loopback", "Multicast (Class D)", "Public unicast"],
    answer: 2,
    explain: "The 224.0.0.0/4 block is Class D, reserved for multicast — one-to-many delivery to hosts that have joined a multicast group.",
  },
  {
    q: "Which port does SMTP use for sending email?",
    options: ["25", "110", "143", "443"],
    answer: 0,
    explain: "SMTP uses TCP port 25 (server-to-server). POP3 uses 110 and IMAP uses 143 for retrieving mail; submission often uses 587.",
  },
  {
    q: "Which ports do POP3 and IMAP use, respectively?",
    options: ["110 and 143", "25 and 110", "143 and 443", "67 and 68"],
    answer: 0,
    explain: "POP3 uses TCP 110 and IMAP uses TCP 143. Their TLS-secured variants use 995 (POP3S) and 993 (IMAPS).",
  },
  {
    q: "Which port does RDP (Remote Desktop Protocol) use?",
    options: ["22", "23", "3389", "8080"],
    answer: 2,
    explain: "RDP uses TCP port 3389 for remote graphical access to Windows systems.",
  },
  {
    q: "In IPv6, a link-local address begins with...",
    options: ["2001::/16", "fe80::/10", "::1/128", "ff00::/8"],
    answer: 1,
    explain: "IPv6 link-local addresses use the fe80::/10 prefix and are valid only on the local link. ::1 is loopback and ff00::/8 is multicast.",
  },
  {
    q: "The IPv6 loopback address is...",
    options: ["::1", "fe80::1", "127.0.0.1", "::"],
    answer: 0,
    explain: "In IPv6, ::1 (all zeros except the final bit) is the loopback address, equivalent to IPv4's 127.0.0.1.",
  },
  {
    q: "Consecutive groups of all-zero hextets in IPv6 can be compressed with...",
    options: ["A single colon (:)", "A double colon (::)", "A dash (-)", "A dot (.)"],
    answer: 1,
    explain: "The double colon (::) replaces one or more consecutive all-zero hextets, but may be used only once in an address to avoid ambiguity.",
  },
  {
    q: "In IPv6, EUI-64 is a method to...",
    options: [
      "Compress the address",
      "Derive the 64-bit interface ID automatically from the 48-bit MAC address",
      "Assign the default gateway",
      "Encrypt traffic",
    ],
    answer: 1,
    explain: "EUI-64 expands a 48-bit MAC to a 64-bit interface identifier (inserting FFFE and flipping the U/L bit), allowing automatic interface-ID generation.",
  },
  {
    q: "Which IPv6 mechanism lets a host configure its own address without DHCP?",
    options: ["SLAAC", "NAT", "ARP", "STP"],
    answer: 0,
    explain: "SLAAC (Stateless Address Autoconfiguration) lets a host build its own global address using the prefix from Router Advertisements plus an interface ID.",
  },
  {
    q: "Which protocol replaces ARP's function in IPv6 (neighbor discovery)?",
    options: ["ICMPv6 Neighbor Discovery (NDP)", "DHCPv6", "DNS", "OSPFv3"],
    answer: 0,
    explain: "IPv6 uses NDP (Neighbor Discovery Protocol), built on ICMPv6, for tasks ARP handled in IPv4 — resolving link-layer addresses and finding routers.",
  },
  {
    q: "A subnet mask's job is to...",
    options: [
      "Encrypt the IP address",
      "Separate the network portion of an address from the host portion",
      "Assign MAC addresses",
      "Resolve domain names",
    ],
    answer: 1,
    explain: "The subnet mask marks which bits of an IP address are the network portion (1s) and which are the host portion (0s), enabling routing decisions.",
  },
  {
    q: "The default subnet mask for a Class C network (/24) is...",
    options: ["255.0.0.0", "255.255.0.0", "255.255.255.0", "255.255.255.255"],
    answer: 2,
    explain: "A /24 (Class C default) mask is 255.255.255.0 — the first three octets are network, the last octet is host (254 usable hosts).",
  },
  {
    q: "A host's TCP/IP configuration minimally requires which of the following to reach other networks?",
    options: [
      "IP address, subnet mask, and default gateway",
      "Only a MAC address",
      "Only a hostname",
      "Only a DNS server",
    ],
    answer: 0,
    explain: "To communicate off-subnet, a host needs an IP address, subnet mask (to know its network), and a default gateway (to route to other networks). DNS is needed for name resolution.",
  },
  {
    q: "Which utility on Linux shows/manages IP addresses and routes in modern distributions?",
    options: ["the 'ip' command (e.g., ip addr, ip route)", "ipconfig", "regedit", "diskpart"],
    answer: 0,
    explain: "The iproute2 'ip' command (ip addr, ip route, ip link) is the modern Linux tool, replacing the deprecated ifconfig/route utilities.",
  },
  {
    q: "Which of the following is a valid reason to use static IP addressing instead of DHCP?",
    options: [
      "For laptops that roam between networks",
      "For servers, printers, and routers that need a consistent, predictable address",
      "To reduce administrative effort on thousands of clients",
      "To hide the gateway",
    ],
    answer: 1,
    explain: "Infrastructure like servers, printers, and network gear benefits from static (fixed) addresses so services and DNS records stay consistent. DHCP suits large numbers of clients.",
  },
  {
    q: "A DHCP 'reservation' ensures that...",
    options: [
      "A specific MAC always receives the same IP from the DHCP pool",
      "The DHCP server is disabled",
      "All addresses are static",
      "DNS is bypassed",
    ],
    answer: 0,
    explain: "A reservation binds a client's MAC address to a specific IP within the DHCP scope, combining DHCP's automation with a predictable address.",
  },
  {
    q: "The 'exclusion range' in a DHCP scope is used to...",
    options: [
      "Block certain MAC addresses",
      "Keep specific addresses from being handed out (e.g., reserved for static devices)",
      "Encrypt DHCP traffic",
      "Extend the lease time",
    ],
    answer: 1,
    explain: "An exclusion range removes addresses from the assignable pool so they can be used statically (e.g., for the gateway or servers) without conflict.",
  },
  {
    q: "A workstation receives 169.254.18.77/16 after rebooting. Other users on the same switch are online. What should you check first?",
    options: [
      "Whether the DHCP server or relay is reachable from that VLAN",
      "Whether the website has an expired certificate",
      "Whether the MAC address table is full",
      "Whether the subnet uses IPv6 only",
    ],
    answer: 0,
    explain: "A 169.254.x.x APIPA address usually means the host did not receive a DHCP lease. Check DHCP reachability, the DHCP scope, relay/ip helper, and VLAN placement.",
  },
  {
    q: "A user can ping 203.0.113.10 but cannot reach intranet.example.com. Which test best isolates the likely problem?",
    options: [
      "Run nslookup intranet.example.com",
      "Replace the Ethernet cable immediately",
      "Change the default gateway",
      "Disable the firewall on the switch",
    ],
    answer: 0,
    explain: "Successful ping to an IP shows basic Layer 3 connectivity. Failure by name points to DNS, so nslookup or dig is the right next test.",
  },
  {
    q: "A server is statically configured as 192.168.12.50/24, but the default gateway is 192.168.13.1. What will most likely fail?",
    options: [
      "Communication with hosts on 192.168.12.0/24",
      "Communication with remote networks",
      "ARP for local hosts",
      "The server's loopback test",
    ],
    answer: 1,
    explain: "The default gateway must be reachable on the local subnet. With /24, 192.168.13.1 is outside 192.168.12.0/24, so off-subnet traffic will fail.",
  },
  {
    q: "A DHCP administrator wants one printer to always receive the same address while still using DHCP. Which feature should be used?",
    options: ["Reservation", "Exclusion range", "APIPA", "NAT overload"],
    answer: 0,
    explain: "A DHCP reservation maps a specific client identifier or MAC address to a predictable IP address while keeping address management centralized in DHCP.",
  },
];
