// ── Module 07 — Cloud Computing & Remote Access (30) ────────────────────────
QUESTIONS["07"] = [
  {
    q: "In which cloud service model does the provider deliver virtual machines, storage, and networking that you manage?",
    options: ["SaaS", "PaaS", "IaaS", "DaaS"],
    answer: 2,
    explain: "IaaS (Infrastructure as a Service) provides fundamental compute, storage, and network resources; the customer manages the OS and applications on top (e.g., AWS EC2, Azure VMs).",
  },
  {
    q: "Which cloud model delivers ready-to-use applications over the Internet (e.g., email, CRM)?",
    options: ["IaaS", "PaaS", "SaaS", "Bare metal"],
    answer: 2,
    explain: "SaaS (Software as a Service) delivers complete applications (Gmail, Office 365, Salesforce) via a browser; the provider manages everything beneath the app.",
  },
  {
    q: "PaaS (Platform as a Service) is best suited for...",
    options: [
      "End users needing finished apps",
      "Developers who want a managed platform (runtime, DB, tools) to build and deploy code without managing servers",
      "Storing backup tapes",
      "Configuring physical switches",
    ],
    answer: 1,
    explain: "PaaS provides a managed application platform (OS, runtime, middleware, databases) so developers focus on code, not infrastructure (e.g., Azure App Service, Heroku).",
  },
  {
    q: "A cloud deployment used exclusively by a single organization is a...",
    options: ["Public cloud", "Private cloud", "Community cloud", "Hybrid cloud"],
    answer: 1,
    explain: "A private cloud is dedicated to one organization (on-prem or hosted), offering more control and isolation. Public clouds share infrastructure among many tenants.",
  },
  {
    q: "A hybrid cloud combines...",
    options: [
      "Two public clouds only",
      "Private (or on-prem) and public cloud resources working together",
      "Two data centers with no cloud",
      "Only SaaS apps",
    ],
    answer: 1,
    explain: "Hybrid cloud integrates on-prem/private and public cloud so workloads and data can move between them — enabling cloud bursting and flexible placement.",
  },
  {
    q: "What is a hypervisor?",
    options: [
      "A network switch",
      "Software that creates and runs virtual machines by abstracting physical hardware",
      "A cloud billing tool",
      "A type of firewall",
    ],
    answer: 1,
    explain: "A hypervisor (VMM) allocates physical CPU/RAM/IO to multiple virtual machines and keeps them isolated. Examples: VMware ESXi, Hyper-V, KVM.",
  },
  {
    q: "A Type 1 (bare-metal) hypervisor runs...",
    options: [
      "As an app on top of a host OS",
      "Directly on the physical hardware with no underlying OS",
      "Only in the cloud",
      "Inside a container",
    ],
    answer: 1,
    explain: "Type 1 hypervisors (ESXi, Hyper-V, KVM) run directly on hardware for performance and efficiency. Type 2 (VirtualBox, VMware Workstation) run atop a host OS.",
  },
  {
    q: "Compared to VMs, containers...",
    options: [
      "Include a full guest OS each",
      "Share the host OS kernel and are lighter/faster to start",
      "Cannot be networked",
      "Require a Type 1 hypervisor",
    ],
    answer: 1,
    explain: "Containers virtualize at the OS level, sharing the host kernel and packaging just the app and its dependencies — far lighter and faster than full VMs (e.g., Docker).",
  },
  {
    q: "The cloud characteristic of 'elasticity' means...",
    options: [
      "Resources are fixed",
      "Resources scale up or down automatically with demand",
      "Data is always encrypted",
      "There is no billing",
    ],
    answer: 1,
    explain: "Elasticity lets capacity grow or shrink automatically to match load, so you pay for what you use and handle spikes without permanent over-provisioning.",
  },
  {
    q: "'Multitenancy' in public cloud refers to...",
    options: [
      "One customer per server",
      "Multiple customers securely sharing the same underlying physical infrastructure",
      "Multiple ISPs",
      "Several VLANs on a switch",
    ],
    answer: 1,
    explain: "Multitenancy means many customers (tenants) share pooled physical resources, logically isolated from each other — a core efficiency of public cloud.",
  },
  {
    q: "Which secure method gives an administrator encrypted command-line access to a remote Linux server?",
    options: ["Telnet", "SSH", "HTTP", "FTP"],
    answer: 1,
    explain: "SSH (port 22) provides encrypted remote CLI access, key-based authentication, and secure tunneling — the standard for remote Unix/Linux administration.",
  },
  {
    q: "Which protocol provides a remote graphical Windows desktop?",
    options: ["RDP", "SSH", "SNMP", "SMTP"],
    answer: 0,
    explain: "RDP (Remote Desktop Protocol, TCP 3389) delivers a full graphical session of a remote Windows machine. Restrict/secure it (VPN, NLA) to reduce attack surface.",
  },
  {
    q: "A site-to-site VPN is used to...",
    options: [
      "Connect a single roaming laptop",
      "Permanently connect two networks (e.g., branch offices) over the Internet with an encrypted tunnel",
      "Replace DNS",
      "Provide Wi-Fi",
    ],
    answer: 1,
    explain: "A site-to-site VPN links entire networks (typically via IPsec between routers/firewalls), so users at each site communicate transparently as if on one network.",
  },
  {
    q: "A client-to-site (remote-access) VPN is used by...",
    options: [
      "Two data centers",
      "Individual remote users connecting a device into the corporate network",
      "Public web servers",
      "Switches connecting to APs",
    ],
    answer: 1,
    explain: "A remote-access VPN lets individual users (with a VPN client) securely connect their device to the corporate network from anywhere over an encrypted tunnel.",
  },
  {
    q: "A clientless VPN typically operates through...",
    options: [
      "A dedicated installed application",
      "A web browser using SSL/TLS (e.g., an SSL VPN portal)",
      "A serial cable",
      "SNMP",
    ],
    answer: 1,
    explain: "Clientless (SSL/TLS) VPNs let users reach internal web apps through an HTTPS portal in a browser, without installing a full VPN client.",
  },
  {
    q: "Out-of-band management refers to...",
    options: [
      "Managing devices over the normal production network",
      "A separate dedicated path (e.g., console/serial or a management port) to manage devices even if the main network is down",
      "Wireless management only",
      "Cloud billing",
    ],
    answer: 1,
    explain: "Out-of-band management uses a separate channel (console/serial port, dedicated mgmt interface, or cellular) so admins can reach devices even during a production-network outage.",
  },
  {
    q: "NFV (Network Function Virtualization) means...",
    options: [
      "Running network functions (firewalls, routers, load balancers) as software/VMs instead of dedicated hardware",
      "A new cabling standard",
      "A wireless protocol",
      "A DNS record type",
    ],
    answer: 0,
    explain: "NFV replaces purpose-built network appliances with software instances running on standard servers/VMs, improving flexibility and reducing hardware dependence.",
  },
  {
    q: "Which term describes accessing cloud resources over a dedicated private connection instead of the public Internet?",
    options: [
      "Direct/private cloud connection (e.g., AWS Direct Connect, Azure ExpressRoute)",
      "Captive portal",
      "APIPA",
      "Split horizon",
    ],
    answer: 0,
    explain: "Services like AWS Direct Connect or Azure ExpressRoute provide a dedicated private link to the cloud, offering more consistent latency, bandwidth, and security than the public Internet.",
  },
  {
    q: "A jump box (bastion host) is used to...",
    options: [
      "Store backups",
      "Provide a hardened, monitored single entry point for administering internal systems",
      "Assign DHCP leases",
      "Terminate fiber",
    ],
    answer: 1,
    explain: "A jump box is a hardened host that admins connect to first, then 'jump' to internal systems — concentrating and auditing administrative access through one controlled point.",
  },
  {
    q: "'Cloud bursting' describes...",
    options: [
      "A cloud outage",
      "Overflowing extra workload from a private cloud/data center into the public cloud during demand spikes",
      "Deleting cloud data",
      "A DDoS attack",
    ],
    answer: 1,
    explain: "Cloud bursting handles peak demand by temporarily shifting overflow workloads to the public cloud, keeping baseline load on-prem — a hybrid-cloud strategy.",
  },
  {
    q: "In the shared responsibility model for IaaS, the customer is typically responsible for...",
    options: [
      "The physical data center security",
      "The guest OS, applications, and data (patching and configuration)",
      "The hypervisor host hardware",
      "Nothing at all",
    ],
    answer: 1,
    explain: "For IaaS, the provider secures the physical/host layer; the customer secures the guest OS, apps, data, and access. Responsibility shifts more to the provider in PaaS/SaaS.",
  },
  {
    q: "A VPN concentrator's role is to...",
    options: [
      "Assign IP addresses",
      "Terminate many VPN tunnels and handle their encryption/authentication",
      "Resolve DNS names",
      "Provide Wi-Fi",
    ],
    answer: 1,
    explain: "A VPN concentrator (often a firewall/appliance feature) aggregates and terminates numerous VPN connections, managing the encryption and authentication for each tunnel.",
  },
  {
    q: "Which protocol suite most commonly secures site-to-site VPN tunnels?",
    options: ["IPsec", "SNMP", "SMTP", "ARP"],
    answer: 0,
    explain: "IPsec (with IKE for key exchange) is the dominant framework for site-to-site VPNs, providing authentication and encryption of IP traffic at Layer 3.",
  },
  {
    q: "A key security advantage of centralizing apps in SaaS/VDI is...",
    options: [
      "Data and updates are managed centrally rather than on each endpoint",
      "No authentication is needed",
      "Endpoints never need patching for anything",
      "It removes the need for backups",
    ],
    answer: 0,
    explain: "Centralizing apps/desktops (SaaS, VDI/DaaS) keeps data and patching in the data center/cloud, reducing exposure from lost or unpatched endpoints — though access control still matters.",
  },
  {
    q: "VDI (Virtual Desktop Infrastructure) provides users with...",
    options: [
      "A physical PC only",
      "Centrally hosted virtual desktops accessed remotely from thin/zero clients or any device",
      "A DNS service",
      "A routing protocol",
    ],
    answer: 1,
    explain: "VDI hosts user desktops as VMs in the data center/cloud; users connect remotely, so data stays centralized and endpoints can be lightweight (thin clients).",
  },
  {
    q: "Which is a benefit of the public cloud's 'pay-as-you-go' model?",
    options: [
      "Large upfront capital expense",
      "Converting capital expense (CapEx) to operational expense (OpEx) with usage-based billing",
      "No monitoring needed",
      "Guaranteed zero cost",
    ],
    answer: 1,
    explain: "Public cloud shifts spending from big upfront hardware purchases (CapEx) to usage-based operating costs (OpEx), improving agility and matching cost to actual consumption.",
  },
  {
    q: "Which remote-access risk is MOST associated with exposing RDP directly to the Internet?",
    options: [
      "Improved performance",
      "Brute-force attacks and ransomware entry via port 3389",
      "Better encryption",
      "Automatic patching",
    ],
    answer: 1,
    explain: "Internet-facing RDP (3389) is a top ransomware vector; attackers brute-force or exploit it. Place RDP behind a VPN/gateway, require MFA, and restrict source IPs.",
  },
  {
    q: "SD-WAN primarily improves WAN connectivity by...",
    options: [
      "Using only a single leased line",
      "Intelligently steering traffic over multiple links (broadband, LTE, MPLS) with central policy control",
      "Eliminating the need for routers",
      "Removing encryption",
    ],
    answer: 1,
    explain: "SD-WAN abstracts and centrally manages multiple transport links, dynamically routing application traffic over the best path — often replacing/augmenting costly MPLS with broadband.",
  },
  {
    q: "The main purpose of a cloud region/availability zone design is to...",
    options: [
      "Increase latency",
      "Improve resilience by distributing resources across isolated failure domains",
      "Reduce security",
      "Avoid backups",
    ],
    answer: 1,
    explain: "Deploying across multiple availability zones/regions isolates failures (power, hardware, disaster) so an outage in one zone doesn't take down the whole application.",
  },
  {
    q: "Which authentication enhancement should always protect remote-access solutions like VPN and RDP gateways?",
    options: [
      "Single static password only",
      "Multi-factor authentication (MFA)",
      "Disabling logging",
      "Open (no) authentication",
    ],
    answer: 1,
    explain: "MFA adds a second factor beyond the password, dramatically reducing the risk of credential theft being enough to breach remote-access services.",
  },
];
