// ── Module 11 — Network Performance & Recovery (40) ─────────────────────────
QUESTIONS["11"] = [
  {
    q: "QoS (Quality of Service) is used to...",
    options: [
      "Encrypt traffic",
      "Prioritize certain traffic (e.g., voice/video) to guarantee performance",
      "Assign IP addresses",
      "Provide Wi-Fi",
    ],
    answer: 1,
    explain: "QoS classifies and prioritizes traffic so latency-sensitive applications (VoIP, video) get preferential treatment during congestion, meeting their performance requirements.",
  },
  {
    q: "Latency is best defined as...",
    options: [
      "The amount of data per second",
      "The time delay for data to travel from source to destination",
      "The number of dropped packets",
      "Signal loss over distance",
    ],
    answer: 1,
    explain: "Latency is delay — how long a packet takes to reach its destination (often measured as round-trip time). High latency hurts real-time applications.",
  },
  {
    q: "Jitter refers to...",
    options: [
      "Total bandwidth",
      "Variation in packet delay over time",
      "The number of hops",
      "Cable attenuation",
    ],
    answer: 1,
    explain: "Jitter is the inconsistency in latency between packets. High jitter disrupts VoIP/video (choppy audio); jitter buffers and QoS help smooth it out.",
  },
  {
    q: "Throughput differs from bandwidth in that throughput is...",
    options: [
      "The theoretical maximum capacity",
      "The actual achieved data rate under real conditions",
      "The cable length",
      "The number of VLANs",
    ],
    answer: 1,
    explain: "Bandwidth is the maximum theoretical capacity of a link; throughput is the real-world rate actually achieved, which is lower due to overhead, congestion, and errors.",
  },
  {
    q: "Which QoS mechanism marks packets at Layer 3 for prioritization?",
    options: ["DSCP (in the IP header)", "MAC address", "SSID", "TTL"],
    answer: 0,
    explain: "DSCP (Differentiated Services Code Point) marks the IP header's ToS field so routers can classify and prioritize traffic. CoS (802.1p) marks at Layer 2.",
  },
  {
    q: "A performance baseline is valuable because it...",
    options: [
      "Encrypts data",
      "Records normal metrics so you can detect deviations and plan capacity",
      "Assigns IPs",
      "Replaces monitoring",
    ],
    answer: 1,
    explain: "A baseline captures normal utilization, latency, and error rates. Comparing current performance to it reveals anomalies, trends, and when to upgrade capacity.",
  },
  {
    q: "Which protocol lets a manager poll devices for performance metrics via agents and receive traps?",
    options: ["SNMP", "SMTP", "ARP", "RDP"],
    answer: 0,
    explain: "SNMP is the standard for network monitoring — managers poll device MIBs for metrics (CPU, interface stats) and devices send traps on events. Use SNMPv3 for security.",
  },
  {
    q: "NetFlow (and IPFIX/sFlow) is primarily used for...",
    options: [
      "Encrypting traffic",
      "Analyzing traffic flows — who is talking to whom, how much, and on what ports",
      "Assigning DHCP",
      "Cabling",
    ],
    answer: 1,
    explain: "Flow technologies export metadata about conversations (source/dest, ports, bytes), giving visibility into bandwidth consumers and traffic patterns for capacity and security analysis.",
  },
  {
    q: "Syslog is used to...",
    options: [
      "Centralize log messages from network devices to a collector",
      "Route packets",
      "Assign VLANs",
      "Terminate fiber",
    ],
    answer: 0,
    explain: "Syslog sends event/log messages from devices to a central syslog server for aggregation, retention, and analysis — often feeding a SIEM.",
  },
  {
    q: "Port mirroring (SPAN) is used to...",
    options: [
      "Copy traffic from one or more ports to a monitoring port for analysis",
      "Double network speed",
      "Assign IPs",
      "Provide PoE",
    ],
    answer: 0,
    explain: "A SPAN/mirror port duplicates traffic from selected ports/VLANs to a port where a sniffer or IDS can analyze it without disrupting the original flow.",
  },
  {
    q: "Load balancing improves performance and availability by...",
    options: [
      "Sending all traffic to one server",
      "Distributing traffic across multiple servers/paths",
      "Encrypting traffic",
      "Disabling redundancy",
    ],
    answer: 1,
    explain: "A load balancer spreads requests across a pool of servers, improving throughput and providing redundancy — if one server fails, others continue serving.",
  },
  {
    q: "A first-hop redundancy protocol like HSRP or VRRP provides...",
    options: [
      "Faster DNS",
      "A virtual/redundant default gateway so hosts keep connectivity if one router fails",
      "More IP addresses",
      "Wi-Fi roaming",
    ],
    answer: 1,
    explain: "FHRPs (HSRP, VRRP, GLBP) let two or more routers share a virtual gateway IP/MAC; if the active router fails, a standby takes over, keeping the gateway available.",
  },
  {
    q: "Spanning Tree Protocol (STP) prevents...",
    options: [
      "IP conflicts",
      "Layer 2 switching loops (and resulting broadcast storms) in redundant topologies",
      "Wi-Fi interference",
      "DNS poisoning",
    ],
    answer: 1,
    explain: "STP (802.1D and successors like RSTP) blocks redundant paths to prevent bridging loops and broadcast storms, while keeping a backup path ready if the active link fails.",
  },
  {
    q: "Link aggregation (LACP/EtherChannel) is used to...",
    options: [
      "Combine multiple physical links into one logical link for more bandwidth and redundancy",
      "Split one link into many VLANs",
      "Encrypt links",
      "Assign IPs",
    ],
    answer: 0,
    explain: "Link aggregation bundles several physical links into one logical channel, increasing throughput and providing redundancy — if one member fails, traffic continues on the rest.",
  },
  {
    q: "A UPS (Uninterruptible Power Supply) provides...",
    options: [
      "Permanent power for weeks",
      "Battery backup to ride through short outages and allow graceful shutdown or generator start",
      "Cooling for servers",
      "Internet access",
    ],
    answer: 1,
    explain: "A UPS supplies battery power during brief outages and conditions power (surges/sags), bridging the gap until a generator starts or systems shut down cleanly.",
  },
  {
    q: "RAID improves ___ for storage.",
    options: [
      "Encryption",
      "Fault tolerance and/or performance",
      "IP addressing",
      "Wireless range",
    ],
    answer: 1,
    explain: "RAID (Redundant Array of Independent Disks) combines drives for redundancy (e.g., RAID 1/5/6 survive drive failure) and/or performance (striping). It is not a backup by itself.",
  },
  {
    q: "Which RAID level mirrors data across two drives (full redundancy, 50% capacity)?",
    options: ["RAID 0", "RAID 1", "RAID 5", "RAID 6"],
    answer: 1,
    explain: "RAID 1 mirrors identical data on two drives — either can fail without data loss, but usable capacity is half the raw total. RAID 0 stripes with no redundancy.",
  },
  {
    q: "In disaster recovery, a 'hot site' is...",
    options: [
      "An empty building with power only",
      "A fully equipped, running duplicate site ready for near-immediate failover",
      "A backup tape",
      "A cloud region with no data",
    ],
    answer: 1,
    explain: "A hot site is fully operational with hardware, data, and connectivity ready — enabling near-instant failover but at the highest cost. Warm and cold sites cost less but take longer to activate.",
  },
  {
    q: "A 'cold site' differs from a hot site in that a cold site...",
    options: [
      "Is fully running with current data",
      "Provides only space/power/connectivity; equipment and data must be brought in and set up",
      "Is a type of firewall",
      "Requires no setup",
    ],
    answer: 1,
    explain: "A cold site has the facility (space, power, cooling, network) but no ready systems or data — cheapest, but the slowest to bring online after a disaster.",
  },
  {
    q: "The difference between a full and an incremental backup is that an incremental backs up...",
    options: [
      "Everything every time",
      "Only data changed since the last backup of any type",
      "Only the OS",
      "Nothing",
    ],
    answer: 1,
    explain: "A full backup copies everything; an incremental copies only what changed since the last backup (full or incremental) — faster/smaller but requiring the full chain to restore.",
  },
  {
    q: "A differential backup copies...",
    options: [
      "Only changes since the last FULL backup",
      "Only changes since the last incremental",
      "Everything each time",
      "Nothing",
    ],
    answer: 0,
    explain: "A differential backs up all changes since the last full backup. Restores need only the full + latest differential (simpler than incrementals, but differentials grow larger over time).",
  },
  {
    q: "Traffic shaping is used to...",
    options: [
      "Drop all traffic",
      "Smooth traffic to a defined rate (buffering bursts) to manage bandwidth and meet QoS",
      "Encrypt packets",
      "Assign VLANs",
    ],
    answer: 1,
    explain: "Shaping delays/buffers excess traffic to conform to a rate, smoothing bursts. Policing, by contrast, drops (or remarks) traffic that exceeds the rate rather than buffering it.",
  },
  {
    q: "A network bottleneck is...",
    options: [
      "A security policy",
      "The point of least capacity that limits overall performance",
      "A backup type",
      "A DNS record",
    ],
    answer: 1,
    explain: "A bottleneck is the constrained resource (a slow link, overloaded router, or saturated server) that caps end-to-end performance. Monitoring locates it for targeted upgrades.",
  },
  {
    q: "High availability is commonly expressed as...",
    options: [
      "The number of VLANs",
      "Uptime percentage / 'nines' (e.g., 99.999% = five nines)",
      "Cable length",
      "Number of hops",
    ],
    answer: 1,
    explain: "Availability is expressed as a percentage of uptime; 'five nines' (99.999%) allows only ~5 minutes of downtime per year. Higher availability requires more redundancy.",
  },
  {
    q: "Which is the BEST protection against ransomware destroying your ability to recover data?",
    options: [
      "RAID only",
      "Offline/immutable, tested backups (3-2-1)",
      "A stronger Wi-Fi password",
      "Disabling logging",
    ],
    answer: 1,
    explain: "Only backups that ransomware cannot reach or alter (offline/immutable, following 3-2-1) guarantee recovery. RAID protects against drive failure, not malicious encryption.",
  },
  {
    q: "MTTR (Mean Time To Repair) measures...",
    options: [
      "Average time to restore a failed component/service",
      "Average time between failures",
      "The bandwidth",
      "The number of users",
    ],
    answer: 0,
    explain: "MTTR is the average time to diagnose and repair a failure and restore service. Lower MTTR means faster recovery; it pairs with MTBF for reliability analysis.",
  },
  {
    q: "Redundant power supplies and dual uplinks are examples of...",
    options: [
      "Eliminating single points of failure (SPOFs)",
      "Increasing latency",
      "Reducing security",
      "Traffic shaping",
    ],
    answer: 0,
    explain: "Adding redundancy for critical components removes single points of failure, so one failed PSU, link, or device doesn't cause an outage — a core high-availability practice.",
  },
  {
    q: "Which tool would you use to continuously graph interface utilization over time?",
    options: [
      "A network monitoring system polling SNMP (e.g., PRTG, LibreNMS, Zabbix)",
      "A punch-down tool",
      "An OTDR",
      "A crimper",
    ],
    answer: 0,
    explain: "SNMP-based NMS platforms poll interface counters and graph utilization, errors, and availability over time — essential for baselining and spotting trends/bottlenecks.",
  },
  {
    q: "The purpose of an active-passive cluster is to...",
    options: [
      "Load balance across all nodes equally",
      "Keep a standby node ready to take over if the active node fails",
      "Disable failover",
      "Encrypt data",
    ],
    answer: 1,
    explain: "In active-passive clustering, one node handles the workload while a passive standby monitors and takes over on failure — providing high availability with automatic failover.",
  },
  {
    q: "VoIP quality is MOST sensitive to which combination?",
    options: [
      "High latency, jitter, and packet loss",
      "Cable color",
      "Number of VLANs",
      "DNS TTL",
    ],
    answer: 0,
    explain: "Real-time voice degrades with latency, jitter, and packet loss. QoS prioritization, jitter buffers, and adequate bandwidth keep call quality acceptable.",
  },
  {
    q: "Which document guides restoring operations after a major outage or disaster?",
    options: [
      "Disaster recovery (DR) plan",
      "Acceptable use policy",
      "Cabling standard",
      "DNS zone file",
    ],
    answer: 0,
    explain: "A DR plan defines procedures, roles, priorities, and resources (sites, backups, RTO/RPO targets) to restore IT operations after a disaster — tested regularly.",
  },
  {
    q: "The main reason to test backups (restore drills) is to...",
    options: [
      "Fill disk space",
      "Verify that backups are actually recoverable before you need them",
      "Increase bandwidth",
      "Assign IPs",
    ],
    answer: 1,
    explain: "An untested backup may be corrupt, incomplete, or unrestorable. Periodic restore testing confirms recoverability and validates RTO/RPO assumptions.",
  },
  {
    q: "Which QoS approach guarantees strict priority for a class such as voice?",
    options: [
      "Best-effort only",
      "A priority (low-latency) queue that services voice ahead of other traffic",
      "Randomly dropping voice",
      "Disabling QoS",
    ],
    answer: 1,
    explain: "A strict-priority/low-latency queue services voice first, minimizing its delay and jitter. Other classes share remaining bandwidth via weighted queuing.",
  },
  {
    q: "A 'broadcast storm' most directly degrades performance by...",
    options: [
      "Encrypting all traffic",
      "Flooding the network with broadcasts (often from a switching loop), consuming bandwidth and CPU",
      "Assigning duplicate IPs",
      "Improving throughput",
    ],
    answer: 1,
    explain: "A broadcast storm — frequently caused by a Layer 2 loop without STP — floods segments with broadcast frames, saturating links and overwhelming devices until connectivity fails.",
  },
  {
    q: "Cold, warm, and hot spares refer to...",
    options: [
      "Backup site temperatures",
      "Standby hardware components with varying readiness to replace a failed part",
      "RAID levels",
      "QoS classes",
    ],
    answer: 1,
    explain: "Spare readiness ranges from cold (on the shelf, must be installed/configured) to warm (installed, needs activation) to hot (online, auto-takes over) — trading cost for recovery speed.",
  },
  {
    q: "Which metric would indicate a saturated link needing an upgrade?",
    options: [
      "Sustained high interface utilization (e.g., ~90–100%) with rising errors/drops",
      "Zero utilization",
      "A low MAC table",
      "A short DNS TTL",
    ],
    answer: 0,
    explain: "Consistently high utilization with increasing output drops/queue depth signals congestion — the link is a bottleneck and needs more bandwidth, aggregation, or QoS.",
  },
  {
    q: "Geographic redundancy (multi-site) protects against...",
    options: [
      "A single-site disaster (fire, flood, power loss) taking down the whole service",
      "Weak passwords",
      "Cable crosstalk",
      "DNS typos",
    ],
    answer: 0,
    explain: "Distributing systems/data across geographically separate sites ensures a localized disaster at one site doesn't cause total outage — the basis of resilient DR design.",
  },
  {
    q: "Which of these is NOT a valid way to improve availability?",
    options: [
      "Redundant hardware and links",
      "Clustering and failover",
      "Regular tested backups",
      "Removing all monitoring and logging",
    ],
    answer: 3,
    explain: "Redundancy, clustering/failover, and tested backups all improve availability. Removing monitoring/logging reduces visibility and hurts your ability to prevent and recover from outages.",
  },
  {
    q: "The primary benefit of caching (e.g., a caching proxy or CDN) on performance is...",
    options: [
      "It encrypts traffic",
      "It serves frequently requested content locally, reducing latency and upstream bandwidth",
      "It assigns IP addresses",
      "It replaces backups",
    ],
    answer: 1,
    explain: "Caching stores popular content closer to users (proxy/CDN), so repeat requests are served faster and consume less WAN/Internet bandwidth.",
  },
  {
    q: "Which best describes 'failover'?",
    options: [
      "Manually rebuilding a server from scratch",
      "Automatic switching to a redundant/standby system when the primary fails",
      "Deleting old data",
      "Encrypting a link",
    ],
    answer: 1,
    explain: "Failover automatically shifts operation to a standby component/system upon detecting a failure, minimizing downtime — a cornerstone of high-availability design.",
  },
];
