// ── Module 03 — Addressing · expansion pool ─────────────────────────────────
QUESTIONS["03"].push(
  {
    q: "How many bits are in each IPv4 octet?",
    options: ["4", "8", "16", "32"],
    answer: 1,
    explain: "An IPv4 address has four 8-bit octets (4 × 8 = 32 bits). Each octet ranges 0–255.",
  },
  {
    q: "What is the decimal value of the binary octet 11000000?",
    options: ["128", "192", "224", "240"],
    answer: 1,
    explain: "128 + 64 = 192. The two leftmost bits are set: 10000000 (128) + 01000000 (64) = 192.",
  },
  {
    q: "Which address type is 172.16.5.4?",
    options: ["Public", "Private (RFC 1918)", "Loopback", "Multicast"],
    answer: 1,
    explain: "172.16.0.0–172.31.255.255 (172.16.0.0/12) is a private range, not routable on the public Internet.",
  },
  {
    q: "Which of the following is a valid public IPv4 address?",
    options: ["10.1.1.1", "192.168.5.5", "8.8.4.4", "169.254.10.10"],
    answer: 2,
    explain: "8.8.4.4 is public (a Google DNS server). The others are private (10.x, 192.168.x) or APIPA (169.254.x).",
  },
  {
    q: "The address ::1 in IPv6 represents the...",
    options: ["Default gateway", "Loopback", "Link-local prefix", "Multicast group"],
    answer: 1,
    explain: "::1/128 is the IPv6 loopback address, equivalent to 127.0.0.1 in IPv4.",
  },
  {
    q: "IPv6 link-local addresses use which prefix?",
    options: ["2000::/3", "fe80::/10", "ff00::/8", "::/128"],
    answer: 1,
    explain: "Link-local addresses begin with fe80::/10 and are valid only on the local link (not routed).",
  },
  {
    q: "Which record type would you query to find the IPv6 address of a host?",
    options: ["A", "AAAA", "MX", "CNAME"],
    answer: 1,
    explain: "The AAAA record maps a hostname to a 128-bit IPv6 address; the A record maps to IPv4.",
  },
  {
    q: "A CNAME record is used to...",
    options: [
      "Point a name to another name (an alias)",
      "Identify a mail server",
      "Map a name to an IPv4 address",
      "Do a reverse lookup",
    ],
    answer: 0,
    explain: "A CNAME (canonical name) record aliases one hostname to another (e.g., www → server1.example.com).",
  },
  {
    q: "Which command would you use on Linux to view the routing table?",
    options: ["ip route", "nslookup", "arp -a", "ping"],
    answer: 0,
    explain: "`ip route` (or the legacy `route`) shows the Linux routing table, including the default gateway.",
  },
  {
    q: "Which utility measures round-trip time to a host and confirms basic reachability?",
    options: ["ping", "arp", "nslookup", "netstat"],
    answer: 0,
    explain: "ping sends ICMP echo requests and reports replies and round-trip time — the first reachability test.",
  },
  {
    q: "A default gateway must be an address on which network relative to the host?",
    options: [
      "Any random network",
      "The host's own local subnet",
      "A public network only",
      "The DNS server's subnet",
    ],
    answer: 1,
    explain: "The default gateway must reside in the host's local subnet so the host can reach it directly at Layer 2 to forward off-subnet traffic.",
  },
  {
    q: "Which port does IMAP over TLS (IMAPS) use?",
    options: ["143", "993", "995", "465"],
    answer: 1,
    explain: "IMAPS uses TCP 993. Plain IMAP is 143. POP3S is 995.",
  },
  {
    q: "Which port does POP3 over TLS (POP3S) use?",
    options: ["110", "995", "993", "587"],
    answer: 1,
    explain: "POP3S uses TCP 995; plain POP3 is 110.",
  },
  {
    q: "Which well-known port is used by NTP for time synchronization?",
    options: ["123", "161", "389", "53"],
    answer: 0,
    explain: "NTP uses UDP 123 to synchronize clocks — important for logs, certificates, and Kerberos.",
  },
  {
    q: "Which port does LDAP use by default?",
    options: ["389", "443", "636", "88"],
    answer: 0,
    explain: "LDAP uses TCP 389 (LDAPS is 636). It queries directory services such as Active Directory.",
  },
  {
    q: "What does the command `tracert`/`traceroute` reveal?",
    options: [
      "The DNS records of a host",
      "Each router (hop) along the path to a destination",
      "The MAC address of the gateway",
      "The listening ports on a server",
    ],
    answer: 1,
    explain: "traceroute/tracert lists the Layer 3 hops to a destination, useful for locating where a path breaks or slows.",
  },
  {
    q: "In IPv6, what does SLAAC allow a host to do?",
    options: [
      "Encrypt its traffic automatically",
      "Configure its own address using the Router Advertisement prefix + an interface ID",
      "Resolve domain names",
      "Assign itself a MAC address",
    ],
    answer: 1,
    explain: "Stateless Address Autoconfiguration lets a host build a global address from the advertised prefix plus its interface ID — no DHCP needed.",
  },
  {
    q: "Which IPv6 mechanism replaces IPv4 ARP for finding a neighbor's link-layer address?",
    options: ["NDP (ICMPv6)", "DHCPv6", "DNS", "STP"],
    answer: 0,
    explain: "Neighbor Discovery Protocol (built on ICMPv6) handles address resolution and router discovery in IPv6, replacing ARP.",
  },
  {
    q: "A subnet mask of 255.255.255.0 corresponds to which prefix length?",
    options: ["/16", "/23", "/24", "/25"],
    answer: 2,
    explain: "255.255.255.0 = 24 network bits = /24 (Class C default), leaving 8 host bits (254 usable hosts).",
  },
  {
    q: "Which is the broadcast address for the network 192.168.1.0/24?",
    options: ["192.168.1.0", "192.168.1.1", "192.168.1.254", "192.168.1.255"],
    answer: 3,
    explain: "In a /24, the last address (all host bits 1) is the broadcast: 192.168.1.255.",
  },
  {
    q: "Which command displays the MAC (physical) address of a Windows host's adapters?",
    options: ["ipconfig /all", "ping -a", "route print", "nslookup"],
    answer: 0,
    explain: "`ipconfig /all` shows detailed adapter info including the Physical Address (MAC), DHCP, and DNS settings.",
  },
  {
    q: "Which of the following is a link-local IPv4 (APIPA) address?",
    options: ["10.0.0.5", "169.254.5.10", "172.16.0.1", "192.0.2.5"],
    answer: 1,
    explain: "APIPA addresses fall in 169.254.0.0/16 and are self-assigned when a DHCP server can't be reached.",
  },
  {
    q: "The 'ephemeral' (dynamic) port range is...",
    options: ["0–1023", "1024–49151", "49152–65535", "1–255"],
    answer: 2,
    explain: "Ephemeral/dynamic ports (49152–65535) are used temporarily by clients as source ports for outbound connections.",
  },
  {
    q: "Which DNS server role answers definitively for a domain it is responsible for?",
    options: ["Recursive resolver", "Root server", "Authoritative server", "Forwarder"],
    answer: 2,
    explain: "The authoritative server holds the actual records for a zone and gives definitive answers; resolvers/forwarders relay queries.",
  },
  {
    q: "What is the function of a DNS TTL value?",
    options: [
      "It sets the packet hop limit",
      "It tells resolvers how long to cache a record before re-querying",
      "It encrypts the record",
      "It defines the port",
    ],
    answer: 1,
    explain: "A record's TTL controls how long resolvers may cache it; lower TTLs speed changes but increase query load.",
  },
  {
    q: "Which tool shows active TCP connections and listening ports on a host?",
    options: ["netstat / ss", "arp", "tracert", "nslookup"],
    answer: 0,
    explain: "netstat (or ss on Linux) lists active connections, listening ports, and related statistics.",
  },
  {
    q: "How many usable host addresses does a /24 provide?",
    options: ["254", "256", "126", "510"],
    answer: 0,
    explain: "A /24 has 8 host bits: 2^8 = 256, minus 2 (network + broadcast) = 254 usable hosts.",
  },
  {
    q: "Which statement about MAC and IP addresses is TRUE?",
    options: [
      "MAC changes as a packet is routed; IP stays the same",
      "IP can change when a device moves networks; MAC stays the same",
      "Both are Layer 3 addresses",
      "Both are assigned by DHCP",
    ],
    answer: 1,
    explain: "A device's burned-in MAC stays constant, while its IP changes with the network. In routing, the destination IP is preserved end-to-end while MACs change hop to hop.",
  },
  {
    q: "Which record is used for reverse DNS (IP → name)?",
    options: ["A", "PTR", "MX", "TXT"],
    answer: 1,
    explain: "The PTR (pointer) record maps an IP address back to a hostname, used in reverse lookups and some anti-spam checks.",
  },
  {
    q: "A TXT record is commonly used for...",
    options: [
      "Mapping names to IPs",
      "Holding text data such as SPF/DKIM records for email validation",
      "Routing packets",
      "Assigning MAC addresses",
    ],
    answer: 1,
    explain: "TXT records store arbitrary text; SPF, DKIM, and domain-verification tokens are common uses.",
  },
  {
    q: "Which command clears/refreshes the DNS resolver cache on Windows?",
    options: ["ipconfig /flushdns", "ipconfig /renew", "netstat -r", "arp -d"],
    answer: 0,
    explain: "`ipconfig /flushdns` clears the local DNS cache, useful after a DNS change to force fresh lookups.",
  },
  {
    q: "Which command releases and renews a DHCP lease on Windows?",
    options: [
      "ipconfig /release then ipconfig /renew",
      "ipconfig /flushdns",
      "arp -a",
      "route add",
    ],
    answer: 0,
    explain: "`ipconfig /release` drops the current lease and `ipconfig /renew` requests a new one from the DHCP server.",
  },
  {
    q: "A host with IP 192.168.1.50/24 wants to reach 192.168.1.70. What does it do?",
    options: [
      "Send the packet to the default gateway",
      "Deliver directly on the local subnet via ARP/MAC",
      "Query DNS first",
      "Drop the packet",
    ],
    answer: 1,
    explain: "Both addresses are in the same /24 subnet, so the host resolves the destination MAC via ARP and delivers directly — no gateway needed.",
  },
  {
    q: "Which protocol dynamically provides a host its IP, mask, gateway, and DNS?",
    options: ["DNS", "DHCP", "ARP", "ICMP"],
    answer: 1,
    explain: "DHCP leases full IP configuration to clients automatically via the DORA exchange.",
  },
  {
    q: "In DHCP, what is a 'lease'?",
    options: [
      "A permanent static assignment",
      "A time-limited allocation of an IP address to a client",
      "A firewall rule",
      "A DNS record",
    ],
    answer: 1,
    explain: "A DHCP lease grants an address for a set duration; the client renews it periodically or the address returns to the pool.",
  },
  {
    q: "Which is required for a client on VLAN 20 to get DHCP from a server on VLAN 10?",
    options: [
      "A second NIC",
      "A DHCP relay / ip helper-address on the router",
      "A crossover cable",
      "A public IP",
    ],
    answer: 1,
    explain: "DHCP Discover is a broadcast confined to its VLAN; a DHCP relay forwards it as unicast to the server on another subnet.",
  },
  {
    q: "The IPv4 address 0.0.0.0 in a routing table represents...",
    options: [
      "The loopback",
      "The default route (all destinations not otherwise matched)",
      "A broadcast",
      "A multicast group",
    ],
    answer: 1,
    explain: "0.0.0.0/0 is the default route — the 'gateway of last resort' for any destination not specifically listed.",
  },
  {
    q: "Which two transport protocols can DNS use, and when?",
    options: [
      "TCP only",
      "UDP for normal queries; TCP for zone transfers and large responses",
      "UDP only",
      "ICMP for all queries",
    ],
    answer: 1,
    explain: "DNS uses UDP 53 for most queries but switches to TCP 53 for zone transfers and responses that exceed UDP size limits.",
  },
  {
    q: "What is the purpose of an MX record's preference (priority) value?",
    options: [
      "It sets the TTL",
      "It orders mail servers so lower values are tried first",
      "It encrypts email",
      "It defines the IP",
    ],
    answer: 1,
    explain: "When multiple MX records exist, senders try the mail server with the lowest preference number first, providing failover.",
  },
  {
    q: "Which utility can perform a detailed DNS query, showing record types and authority?",
    options: ["dig", "ping", "arp", "route"],
    answer: 0,
    explain: "dig (Domain Information Groper) is a flexible DNS lookup tool showing record data, TTLs, and which server answered.",
  },
  {
    q: "Which IPv6 feature compresses one run of consecutive all-zero hextets?",
    options: ["A single colon", "A double colon (::)", "A slash", "A dash"],
    answer: 1,
    explain: "The double colon (::) replaces one contiguous run of all-zero hextets, and may appear only once per address.",
  },
  {
    q: "How many bits is the standard IPv6 interface identifier in a /64 subnet?",
    options: ["32", "48", "64", "128"],
    answer: 2,
    explain: "In a /64, the first 64 bits are the network prefix and the remaining 64 bits are the interface identifier.",
  },
  {
    q: "Which address would a host use to send to all nodes on its local IPv6 link?",
    options: ["ff02::1", "::1", "fe80::", "2000::1"],
    answer: 0,
    explain: "ff02::1 is the IPv6 all-nodes multicast address for the local link (IPv6 has no broadcast — it uses multicast instead).",
  },
  {
    q: "A private IPv4 network reaching the Internet typically relies on which technology at the edge?",
    options: ["NAT/PAT", "STP", "VLAN", "OSPF"],
    answer: 0,
    explain: "NAT/PAT translates private source addresses to a public address (and port), letting many internal hosts share one public IP.",
  },
  {
    q: "Which is TRUE about the loopback range 127.0.0.0/8?",
    options: [
      "It is routable on the Internet",
      "It is reserved for local host testing; traffic never leaves the device",
      "It is a private LAN range",
      "It is used for multicast",
    ],
    answer: 1,
    explain: "The entire 127.0.0.0/8 block is loopback; packets addressed there stay within the host to test the local TCP/IP stack.",
  },
  {
    q: "Which command shows a host's ARP cache entries?",
    options: ["arp -a", "ping", "ipconfig /renew", "nslookup"],
    answer: 0,
    explain: "`arp -a` lists cached IP-to-MAC mappings, useful when diagnosing Layer 2/3 resolution problems.",
  },
  {
    q: "A network uses 255.255.255.240 as its mask. How many usable hosts per subnet?",
    options: ["16", "14", "30", "6"],
    answer: 1,
    explain: "255.255.255.240 = /28 = 4 host bits: 2^4 = 16, minus 2 = 14 usable hosts.",
  },
  {
    q: "Which DNS record identifies the authoritative name servers for a zone?",
    options: ["NS", "MX", "A", "PTR"],
    answer: 0,
    explain: "NS (Name Server) records list the authoritative servers for a domain/zone, used for delegation.",
  },
  {
    q: "A DHCP 'scope' is...",
    options: [
      "A single static address",
      "The range of addresses and options a server can assign for a subnet",
      "A DNS zone",
      "A firewall ACL",
    ],
    answer: 1,
    explain: "A scope defines the pool of assignable addresses plus options (gateway, DNS, lease time) for a particular subnet.",
  },
  {
    q: "Why assign a static IP (or DHCP reservation) to a network printer or server?",
    options: [
      "To make it unreachable",
      "So its address stays consistent for clients, DNS, and firewall rules",
      "To use more bandwidth",
      "To disable DNS",
    ],
    answer: 1,
    explain: "Infrastructure devices need predictable addresses so references (DNS, print queues, ACLs) remain valid; reservations give DHCP-managed consistency.",
  },
  {
    q: "Which is the network ID of host 10.5.12.200 with mask 255.255.255.0?",
    options: ["10.5.12.0", "10.5.0.0", "10.5.12.200", "10.0.0.0"],
    answer: 0,
    explain: "With a /24 mask, the network ID zeroes the host octet: 10.5.12.0.",
  },
  {
    q: "Which port does the SMTP submission service (authenticated client mail) commonly use?",
    options: ["25", "587", "110", "143"],
    answer: 1,
    explain: "Port 587 is the mail submission port for authenticated clients sending mail; 25 is used for server-to-server relay.",
  }
);
