// ── Module 04 — Network Protocols (50) ──────────────────────────────────────
QUESTIONS["04"] = [
  {
    q: "TCP/IP is best described as...",
    options: [
      "A single protocol",
      "A suite of protocols including TCP, IP, UDP, ARP, and others",
      "A type of cable",
      "A brand of router",
    ],
    answer: 1,
    explain: "TCP/IP is a suite (stack) of cooperating protocols — including TCP, IP (v4/v6), UDP, ICMP, and ARP — that together enable Internet communication.",
  },
  {
    q: "Which transport protocol is connection-oriented and provides reliable, ordered delivery?",
    options: ["UDP", "TCP", "IP", "ICMP"],
    answer: 1,
    explain: "TCP is connection-oriented: it establishes a session, sequences bytes, acknowledges receipt, and retransmits lost data — providing reliable, ordered delivery.",
  },
  {
    q: "Which transport protocol is connectionless and prioritizes speed over reliability?",
    options: ["TCP", "UDP", "ARP", "HTTP"],
    answer: 1,
    explain: "UDP is connectionless — no handshake, sequencing, or acknowledgments. It's faster and lower-overhead, ideal for streaming, VoIP, DNS, and gaming.",
  },
  {
    q: "What are the three steps of the TCP three-way handshake?",
    options: [
      "SYN, SYN-ACK, ACK",
      "ACK, FIN, RST",
      "Discover, Offer, Request",
      "Hello, Update, Bye",
    ],
    answer: 0,
    explain: "TCP connections open with SYN (client), SYN-ACK (server), then ACK (client) — synchronizing sequence numbers before data flows.",
  },
  {
    q: "Which TCP flag is used to gracefully close a connection?",
    options: ["SYN", "FIN", "URG", "PSH"],
    answer: 1,
    explain: "The FIN flag signals that a sender has finished transmitting data, initiating a graceful teardown. RST, by contrast, abruptly resets a connection.",
  },
  {
    q: "Which TCP flag abruptly terminates (resets) a connection?",
    options: ["FIN", "RST", "ACK", "SYN"],
    answer: 1,
    explain: "RST (reset) immediately aborts a TCP connection, often sent when a port is closed or an unexpected packet arrives.",
  },
  {
    q: "A port number identifies...",
    options: [
      "The physical network jack",
      "The application/service a segment is destined for",
      "The MAC address",
      "The default gateway",
    ],
    answer: 1,
    explain: "Transport-layer port numbers identify the sending/receiving application (e.g., 80 for web, 25 for mail), allowing many services to share one IP.",
  },
  {
    q: "The combination of an IP address and a port number is called a...",
    options: ["Socket", "Frame", "Datagram", "Subnet"],
    answer: 0,
    explain: "A socket is the endpoint identified by IP:port (e.g., 192.168.1.5:443). A pair of sockets defines a unique TCP/UDP connection.",
  },
  {
    q: "As data moves down the TCP/IP stack, at the Transport layer TCP or UDP adds a header that includes...",
    options: ["The MAC address", "A port number", "The cable type", "The VLAN tag"],
    answer: 1,
    explain: "The Transport-layer header adds source and destination port numbers (among other fields) to identify the receiving application.",
  },
  {
    q: "Which protocol is used by ping and for delivering error/diagnostic messages?",
    options: ["ICMP", "SMTP", "SNMP", "FTP"],
    answer: 0,
    explain: "ICMP (Internet Control Message Protocol) carries diagnostic and error messages, including the Echo Request/Reply used by ping and 'destination unreachable' notices.",
  },
  {
    q: "Which protocol provides encrypted remote command-line access to a device?",
    options: ["Telnet", "SSH", "FTP", "HTTP"],
    answer: 1,
    explain: "SSH encrypts the session (login, commands, output) over TCP 22. Telnet (TCP 23) sends everything in clear text and should be avoided.",
  },
  {
    q: "Why should Telnet be avoided for remote administration?",
    options: [
      "It is too fast",
      "It transmits credentials and data in clear text",
      "It uses too much bandwidth",
      "It only works over fiber",
    ],
    answer: 1,
    explain: "Telnet sends everything, including usernames and passwords, in plaintext — trivially captured by a sniffer. SSH is the secure replacement.",
  },
  {
    q: "Which protocol secures HTTP, email, and other traffic using certificates and encryption at the session/presentation layers?",
    options: ["TLS/SSL", "ARP", "DHCP", "ICMP"],
    answer: 0,
    explain: "TLS (Transport Layer Security), successor to SSL, provides encryption, integrity, and server authentication (via certificates) for HTTPS, secure mail, and more.",
  },
  {
    q: "IPsec operates primarily at which OSI layer?",
    options: ["Layer 2 (Data Link)", "Layer 3 (Network)", "Layer 4 (Transport)", "Layer 7 (Application)"],
    answer: 1,
    explain: "IPsec secures traffic at Layer 3 (Network), encrypting/authenticating IP packets. It's widely used to build site-to-site and remote-access VPNs.",
  },
  {
    q: "Which two protocols make up the core of IPsec?",
    options: ["AH and ESP", "TCP and UDP", "PAP and CHAP", "SSL and TLS"],
    answer: 0,
    explain: "IPsec uses AH (Authentication Header) for integrity/authentication and ESP (Encapsulating Security Payload) for encryption (and optionally integrity).",
  },
  {
    q: "Which protocol securely transfers files over SSH?",
    options: ["FTP", "TFTP", "SFTP", "SMTP"],
    answer: 2,
    explain: "SFTP (SSH File Transfer Protocol) runs over SSH (port 22), encrypting file transfers. FTP (20/21) and TFTP (69) are unencrypted.",
  },
  {
    q: "FTPS differs from SFTP in that FTPS...",
    options: [
      "Uses SSH",
      "Is FTP secured with TLS/SSL",
      "Is unencrypted",
      "Uses UDP only",
    ],
    answer: 1,
    explain: "FTPS is traditional FTP wrapped in TLS/SSL, while SFTP is a different protocol built on SSH. Both encrypt transfers but work quite differently.",
  },
  {
    q: "Which protocol is used to monitor and manage network devices, gathering stats via agents?",
    options: ["SNMP", "SMTP", "SFTP", "RDP"],
    answer: 0,
    explain: "SNMP (Simple Network Management Protocol) lets a manager poll device agents for metrics and receive traps. Use SNMPv3 for authentication and encryption.",
  },
  {
    q: "Which SNMP version adds authentication and encryption?",
    options: ["SNMPv1", "SNMPv2c", "SNMPv3", "SNMPv0"],
    answer: 2,
    explain: "SNMPv3 introduces security features — authentication, integrity, and encryption — that v1 and v2c lack (they rely on plaintext community strings).",
  },
  {
    q: "Which protocol synchronizes clocks across network devices?",
    options: ["NTP", "DNS", "ARP", "LDAP"],
    answer: 0,
    explain: "NTP (Network Time Protocol, UDP 123) keeps device clocks synchronized — critical for logs, certificates, Kerberos, and correlating security events.",
  },
  {
    q: "Which protocol is commonly used to query and modify directory services like Active Directory?",
    options: ["LDAP", "SMTP", "SNMP", "TFTP"],
    answer: 0,
    explain: "LDAP (Lightweight Directory Access Protocol, TCP 389; LDAPS 636) queries and updates directory data such as users and groups in AD or OpenLDAP.",
  },
  {
    q: "A VPN provides...",
    options: [
      "A physical private cable between sites",
      "An encrypted tunnel over a public network to connect users/sites securely",
      "Faster DNS resolution",
      "Automatic IP addressing",
    ],
    answer: 1,
    explain: "A VPN (Virtual Private Network) creates an encrypted tunnel across an untrusted network (like the Internet), letting remote users or sites communicate as if on a private LAN.",
  },
  {
    q: "A 'full tunnel' VPN configuration means...",
    options: [
      "Only traffic to the corporate network goes through the VPN",
      "All of the client's traffic is routed through the VPN",
      "No traffic is encrypted",
      "The VPN only carries DNS",
    ],
    answer: 1,
    explain: "In full tunnel, every packet from the client goes through the VPN (more secure, more load). Split tunnel sends only corporate-bound traffic through the VPN.",
  },
  {
    q: "Which protocol/port pair is correct?",
    options: ["HTTP – 8080 only", "HTTPS – 443", "SSH – 25", "DNS – 80"],
    answer: 1,
    explain: "HTTPS uses TCP 443. (HTTP=80, SSH=22, SMTP=25, DNS=53.) 8080 is a common alternate HTTP proxy port but not the standard.",
  },
  {
    q: "Which protocol resolves IP-to-MAC and is confined to the local broadcast domain?",
    options: ["DNS", "ARP", "BGP", "OSPF"],
    answer: 1,
    explain: "ARP broadcasts a request ('who has this IP?') on the local segment; the owner replies with its MAC. Routers do not forward ARP beyond the local network.",
  },
  {
    q: "QUIC is a modern transport protocol that runs over...",
    options: ["TCP", "UDP", "ICMP", "ARP"],
    answer: 1,
    explain: "QUIC runs over UDP and provides multiplexed, encrypted, low-latency connections; it underpins HTTP/3, reducing handshake overhead compared to TCP+TLS.",
  },
  {
    q: "Which protocol is used by web servers and browsers for the modern HTTP/2 and is always encrypted in practice?",
    options: ["HTTP over TLS (HTTPS)", "FTP", "Telnet", "SNMP"],
    answer: 0,
    explain: "HTTPS (HTTP over TLS) secures web traffic with encryption and server authentication. HTTP/2 in browsers is used over TLS in practice.",
  },
  {
    q: "The main advantage of UDP for VoIP is...",
    options: [
      "Guaranteed delivery",
      "Low latency, since retransmitting late audio is worse than dropping it",
      "Built-in encryption",
      "Automatic addressing",
    ],
    answer: 1,
    explain: "Real-time voice/video favor UDP's low latency — a late-arriving retransmitted packet is useless, so speed matters more than guaranteed delivery.",
  },
  {
    q: "TCP achieves reliability partly through...",
    options: [
      "Sequence numbers and acknowledgments",
      "Broadcasting every packet",
      "Ignoring lost packets",
      "Using MAC addresses",
    ],
    answer: 0,
    explain: "TCP numbers bytes with sequence numbers and requires ACKs; unacknowledged data is retransmitted, and receivers reorder segments — ensuring reliable, in-order delivery.",
  },
  {
    q: "TCP flow control is primarily managed by the...",
    options: ["Window size field", "TTL field", "MAC address", "VLAN tag"],
    answer: 0,
    explain: "The TCP window size (advertised by the receiver) controls how much unacknowledged data the sender may transmit, preventing the receiver from being overwhelmed.",
  },
  {
    q: "Which protocol assigns and manages email retrieval while keeping messages synchronized across devices?",
    options: ["POP3", "IMAP", "SMTP", "SNMP"],
    answer: 1,
    explain: "IMAP (port 143/993) keeps mail on the server and syncs state across devices. POP3 typically downloads and removes mail, suiting a single device.",
  },
  {
    q: "The purpose of a reverse proxy is to...",
    options: [
      "Hide internal clients from the Internet",
      "Sit in front of servers, handling requests, load balancing, and TLS termination on their behalf",
      "Assign IP addresses",
      "Resolve MAC addresses",
    ],
    answer: 1,
    explain: "A reverse proxy fronts one or more servers, distributing load, terminating TLS, and adding caching/security. A forward proxy, in contrast, fronts clients.",
  },
  {
    q: "Which protocol/utility would you use to test whether a specific TCP port is open on a remote host?",
    options: ["ping", "telnet/nc to the port, or nmap", "arp", "ipconfig"],
    answer: 1,
    explain: "You can test a TCP port with telnet host port, netcat (nc), or a scanner like nmap. ping only tests ICMP reachability, not specific ports.",
  },
  {
    q: "Which of the following is a Layer 7 (application) protocol?",
    options: ["IP", "TCP", "HTTP", "Ethernet"],
    answer: 2,
    explain: "HTTP is an application-layer (Layer 7) protocol. IP is Layer 3, TCP is Layer 4, and Ethernet is Layers 1–2.",
  },
  {
    q: "The TTL (Time To Live) field in an IP packet is used to...",
    options: [
      "Encrypt the payload",
      "Prevent packets from looping forever by decrementing at each router",
      "Store the MAC address",
      "Set the port number",
    ],
    answer: 1,
    explain: "Each router decrements TTL by one; when it reaches zero the packet is discarded and an ICMP 'time exceeded' is sent — preventing infinite routing loops. traceroute exploits this.",
  },
  {
    q: "Which protocol is used for secure directory authentication and is the basis of Windows domain logins?",
    options: ["Kerberos", "FTP", "SNMP", "ICMP"],
    answer: 0,
    explain: "Kerberos (UDP/TCP 88) provides ticket-based, mutual authentication and is the default authentication protocol in Active Directory domains.",
  },
  {
    q: "Which remote-access protocol gives a full graphical desktop of a Windows machine?",
    options: ["SSH", "RDP", "SNMP", "SMTP"],
    answer: 1,
    explain: "RDP (Remote Desktop Protocol, TCP 3389) provides remote graphical desktop access to Windows systems. SSH is text/command-line oriented.",
  },
  {
    q: "Which statement about ports 20 and 21 is correct?",
    options: [
      "They are used by SSH",
      "FTP uses port 21 for control and port 20 for data (active mode)",
      "They are HTTPS ports",
      "They are DNS ports",
    ],
    answer: 1,
    explain: "FTP uses TCP 21 for the command/control channel and TCP 20 for data transfer in active mode. Both are unencrypted, hence SFTP/FTPS for security.",
  },
  {
    q: "An application that needs guaranteed, in-order delivery of a large file should use...",
    options: ["UDP", "TCP", "ICMP", "ARP"],
    answer: 1,
    explain: "File transfers require every byte in order — TCP's acknowledgment, sequencing, and retransmission make it the right choice over unreliable UDP.",
  },
  {
    q: "Which protocol allows dynamic discovery and configuration of IPv6 default gateways via Router Advertisements?",
    options: ["ICMPv6 / NDP", "ARP", "DHCPv4", "STP"],
    answer: 0,
    explain: "In IPv6, routers send Router Advertisement messages (ICMPv6/NDP) so hosts can discover the gateway and prefix, enabling SLAAC.",
  },
  {
    q: "The primary function of the IP protocol is...",
    options: [
      "Reliable, ordered delivery",
      "Logical addressing and best-effort routing of packets between networks",
      "Encrypting data",
      "Resolving names",
    ],
    answer: 1,
    explain: "IP provides logical addressing and connectionless, best-effort delivery of packets across networks. Reliability is added above it by TCP.",
  },
  {
    q: "Which utility captures and analyzes packets on the wire for deep protocol inspection?",
    options: ["Wireshark", "ipconfig", "ping", "nslookup"],
    answer: 0,
    explain: "Wireshark (and tcpdump) are protocol analyzers/sniffers that capture frames and decode them layer by layer for troubleshooting and security analysis.",
  },
  {
    q: "A DNS query typically uses UDP, but switches to TCP when...",
    options: [
      "The response is large or during zone transfers",
      "The client is on Wi-Fi",
      "Encryption is required",
      "Never — DNS is UDP only",
    ],
    answer: 0,
    explain: "DNS uses UDP 53 for normal queries but falls back to TCP 53 for responses that exceed UDP limits and for zone transfers between servers.",
  },
  {
    q: "Which pair correctly matches a secure protocol to the insecure one it replaces?",
    options: [
      "SSH replaces Telnet",
      "HTTP replaces HTTPS",
      "FTP replaces SFTP",
      "SNMPv1 replaces SNMPv3",
    ],
    answer: 0,
    explain: "SSH (encrypted) replaces Telnet (plaintext). Likewise HTTPS>HTTP, SFTP/FTPS>FTP, and SNMPv3>SNMPv1/2c for security.",
  },
  {
    q: "The purpose of encapsulation headers at each layer is to...",
    options: [
      "Slow down transmission",
      "Provide the addressing/control info each layer needs to do its job",
      "Encrypt everything by default",
      "Remove the payload",
    ],
    answer: 1,
    explain: "Each layer adds a header with the information it needs (ports at Transport, IPs at Network, MACs at Data Link) so peer layers on the receiver can process the data.",
  },
  {
    q: "Which protocol would a network engineer use to push configuration backups from a router to a simple server with minimal overhead on a trusted LAN?",
    options: ["TFTP", "HTTPS", "SFTP", "RDP"],
    answer: 0,
    explain: "TFTP (UDP 69) is a lightweight, no-authentication file transfer often used to move IOS images and configs on trusted networks. It's insecure, so it belongs only on protected segments.",
  },
  {
    q: "SMTP is used to ___, while POP3/IMAP are used to ___.",
    options: [
      "receive mail; send mail",
      "send mail; retrieve mail",
      "browse the web; send mail",
      "resolve names; send mail",
    ],
    answer: 1,
    explain: "SMTP sends/relays outgoing mail between servers, while POP3 and IMAP retrieve mail from a server to a client.",
  },
  {
    q: "Which field distinguishes the upper-layer protocol (TCP vs UDP vs ICMP) carried inside an IPv4 packet?",
    options: ["The Protocol field", "The TTL field", "The Options field", "The Checksum field"],
    answer: 0,
    explain: "The IPv4 header's Protocol field identifies the encapsulated protocol (e.g., 6=TCP, 17=UDP, 1=ICMP) so the receiver hands the payload to the correct handler.",
  },
  {
    q: "Which best describes the difference between a connectionless and connection-oriented protocol?",
    options: [
      "Connectionless establishes a session first; connection-oriented does not",
      "Connection-oriented sets up and verifies a session (TCP); connectionless just sends (UDP)",
      "They are identical",
      "Connectionless always encrypts",
    ],
    answer: 1,
    explain: "Connection-oriented (TCP) establishes and maintains a verified session with handshakes and ACKs; connectionless (UDP) simply sends datagrams without setup or guarantees.",
  },
  {
    q: "Which protocol would you use to securely browse an internal web app, ensuring the traffic is encrypted end to end?",
    options: ["HTTP", "HTTPS (HTTP over TLS)", "Telnet", "TFTP"],
    answer: 1,
    explain: "HTTPS wraps HTTP in TLS, encrypting the session and authenticating the server with a certificate — the standard for any web traffic that must be confidential and tamper-resistant.",
  },
];
