// ── Module 06 — Wireless Networking (35) ────────────────────────────────────
QUESTIONS["06"] = [
  {
    q: "Which IEEE standard family governs Wi-Fi wireless LANs?",
    options: ["802.3", "802.11", "802.1Q", "802.15"],
    answer: 1,
    explain: "IEEE 802.11 defines wireless LAN (Wi-Fi) standards. 802.3 is Ethernet, 802.1Q is VLAN tagging, and 802.15 covers PANs like Bluetooth.",
  },
  {
    q: "Which two frequency bands do most Wi-Fi networks use?",
    options: ["900 MHz and 1.8 GHz", "2.4 GHz and 5 GHz", "10 GHz and 60 GHz", "88 MHz and 108 MHz"],
    answer: 1,
    explain: "Wi-Fi primarily uses the 2.4 GHz and 5 GHz bands (Wi-Fi 6E adds 6 GHz). 2.4 GHz has better range/penetration; 5 GHz offers more channels and speed.",
  },
  {
    q: "Compared to 5 GHz, the 2.4 GHz band generally offers...",
    options: [
      "Shorter range but more channels",
      "Longer range and better obstacle penetration but fewer non-overlapping channels and more interference",
      "Higher throughput always",
      "No interference at all",
    ],
    answer: 1,
    explain: "2.4 GHz travels farther and penetrates walls better but is crowded (only 3 non-overlapping 20 MHz channels: 1, 6, 11) and prone to interference from many devices.",
  },
  {
    q: "In the 2.4 GHz band (North America), which channels are non-overlapping?",
    options: ["1, 2, 3", "1, 6, 11", "1, 5, 9", "2, 7, 12"],
    answer: 1,
    explain: "Channels 1, 6, and 11 are the standard non-overlapping 20 MHz channels in the 2.4 GHz band, minimizing co-channel interference between nearby APs.",
  },
  {
    q: "Which 802.11 amendment is marketed as 'Wi-Fi 6'?",
    options: ["802.11n", "802.11ac", "802.11ax", "802.11g"],
    answer: 2,
    explain: "802.11ax = Wi-Fi 6 (and 6E on 6 GHz). 802.11ac=Wi-Fi 5, 802.11n=Wi-Fi 4. Wi-Fi 6 improves efficiency in dense environments with OFDMA and MU-MIMO.",
  },
  {
    q: "802.11ac operates in which band?",
    options: ["2.4 GHz only", "5 GHz only", "900 MHz", "60 GHz"],
    answer: 1,
    explain: "802.11ac (Wi-Fi 5) operates only in the 5 GHz band, using wider channels (up to 160 MHz) and MU-MIMO for high throughput.",
  },
  {
    q: "What does SSID stand for?",
    options: ["Secure Server ID", "Service Set Identifier", "Signal Strength Indicator", "Subnet Set ID"],
    answer: 1,
    explain: "The SSID (Service Set Identifier) is the wireless network's name that clients use to identify and connect to it.",
  },
  {
    q: "Which wireless security standard is the current strongest, using SAE for the handshake?",
    options: ["WEP", "WPA", "WPA2", "WPA3"],
    answer: 3,
    explain: "WPA3 is the newest standard, replacing the WPA2 4-way handshake with SAE (Simultaneous Authentication of Equals), resisting offline dictionary attacks.",
  },
  {
    q: "Which legacy wireless security protocol is considered broken and must not be used?",
    options: ["WPA2", "WPA3", "WEP", "802.1X"],
    answer: 2,
    explain: "WEP (Wired Equivalent Privacy) uses weak RC4/IV design and is easily cracked in minutes. It is deprecated; use WPA2/WPA3 instead.",
  },
  {
    q: "WPA2-Enterprise differs from WPA2-Personal (PSK) in that Enterprise...",
    options: [
      "Uses a single shared password",
      "Authenticates each user individually via 802.1X/RADIUS",
      "Has no encryption",
      "Only works on 2.4 GHz",
    ],
    answer: 1,
    explain: "WPA2-Enterprise uses 802.1X with a RADIUS server so each user authenticates with unique credentials, whereas Personal (PSK) uses one shared passphrase for everyone.",
  },
  {
    q: "Which encryption cipher does WPA2 use?",
    options: ["RC4/TKIP", "AES-CCMP", "DES", "MD5"],
    answer: 1,
    explain: "WPA2 uses AES-based CCMP for strong encryption. WPA (and legacy WPA2 compatibility) used TKIP/RC4, which is weaker and deprecated.",
  },
  {
    q: "Wireless clients avoid collisions using which access method?",
    options: ["CSMA/CD", "CSMA/CA", "Token passing", "Polling only"],
    answer: 1,
    explain: "Wi-Fi uses CSMA/CA (Collision Avoidance): a station listens, waits, and uses acknowledgments because it cannot reliably detect collisions on the air (unlike wired CSMA/CD).",
  },
  {
    q: "An 802.11 'BSS' (Basic Service Set) consists of...",
    options: [
      "Multiple APs sharing one SSID",
      "A single AP and its associated clients",
      "Two wired switches",
      "A VLAN trunk",
    ],
    answer: 1,
    explain: "A BSS is one access point and the stations associated with it, identified by a BSSID (the AP's MAC). Multiple BSSs sharing an SSID form an ESS.",
  },
  {
    q: "An 'ESS' (Extended Service Set) enables...",
    options: [
      "A single isolated AP",
      "Multiple APs with the same SSID so clients can roam seamlessly",
      "Wired-only networking",
      "Disabling encryption",
    ],
    answer: 1,
    explain: "An ESS links multiple BSSs (APs) under one SSID over a common distribution system, allowing clients to roam between APs without losing the connection.",
  },
  {
    q: "MIMO (Multiple Input Multiple Output) improves wireless by...",
    options: [
      "Using multiple antennas/spatial streams to increase throughput and reliability",
      "Reducing the number of channels",
      "Encrypting frames",
      "Disabling other clients",
    ],
    answer: 0,
    explain: "MIMO uses multiple transmit/receive antennas and spatial streams (spatial multiplexing) to boost data rates and resilience via multipath. MU-MIMO serves multiple clients simultaneously.",
  },
  {
    q: "A wireless 'site survey' is performed to...",
    options: [
      "Assign IP addresses",
      "Map coverage, signal strength, interference, and optimal AP placement/channels",
      "Configure DNS",
      "Set up a firewall",
    ],
    answer: 1,
    explain: "A site survey (passive/active/predictive) measures RF conditions to plan AP locations, channels, and power for adequate coverage and minimal interference.",
  },
  {
    q: "A directional (e.g., Yagi or panel) antenna is best used to...",
    options: [
      "Provide equal coverage in all directions",
      "Focus signal in one direction, extending range for point-to-point links",
      "Increase interference",
      "Power the AP",
    ],
    answer: 1,
    explain: "Directional antennas concentrate RF energy in a specific direction, increasing gain/range for point-to-point bridges. Omnidirectional antennas radiate in all directions for general coverage.",
  },
  {
    q: "Which term describes a rogue AP set up to trick users into connecting (impersonating a legitimate SSID)?",
    options: ["Evil twin", "Honeynet", "Jump box", "Bastion host"],
    answer: 0,
    explain: "An evil twin is a malicious AP broadcasting a legitimate-looking SSID to lure clients and capture credentials or perform man-in-the-middle attacks.",
  },
  {
    q: "802.1X wireless authentication requires which server role?",
    options: ["DHCP server", "RADIUS (authentication) server", "DNS server", "NTP server"],
    answer: 1,
    explain: "802.1X port-based authentication uses a RADIUS server as the authentication server; the AP acts as the authenticator and the client is the supplicant.",
  },
  {
    q: "Which of the following most commonly causes 2.4 GHz Wi-Fi interference?",
    options: [
      "Fiber-optic cable",
      "Microwave ovens, cordless phones, and Bluetooth devices",
      "Ethernet switches",
      "DNS servers",
    ],
    answer: 1,
    explain: "The 2.4 GHz band is shared by microwaves, cordless phones, Bluetooth, and baby monitors — all potential interference sources that degrade Wi-Fi performance.",
  },
  {
    q: "Hiding the SSID (disabling broadcast) provides...",
    options: [
      "Strong security equivalent to encryption",
      "Only minor obscurity; it is not a real security control",
      "Faster speeds",
      "More channels",
    ],
    answer: 1,
    explain: "Not broadcasting the SSID offers negligible security — the name is still visible in client probes and can be captured. Real protection comes from WPA2/WPA3 encryption.",
  },
  {
    q: "Which wireless mode connects two networks/buildings wirelessly like a virtual cable?",
    options: ["Infrastructure mode", "Wireless bridge (point-to-point)", "Ad hoc chat", "Monitor mode"],
    answer: 1,
    explain: "A wireless bridge links two wired segments over a point-to-point RF link (often with directional antennas), effectively replacing a cable between buildings.",
  },
  {
    q: "In infrastructure mode, wireless clients communicate...",
    options: [
      "Directly peer-to-peer with no AP",
      "Through a central access point",
      "Only over fiber",
      "Using tokens",
    ],
    answer: 1,
    explain: "Infrastructure mode routes all client traffic through an access point (the norm for business/home Wi-Fi). Ad hoc mode is direct device-to-device without an AP.",
  },
  {
    q: "Channel bonding (e.g., using 40/80/160 MHz channels) affects Wi-Fi by...",
    options: [
      "Reducing throughput",
      "Increasing throughput per link but consuming more spectrum (fewer clean channels)",
      "Disabling encryption",
      "Powering more APs",
    ],
    answer: 1,
    explain: "Bonding channels widens the channel to boost speed, but uses more of the band — practical mainly in 5/6 GHz where more spectrum exists. In 2.4 GHz it worsens interference.",
  },
  {
    q: "A heat map produced by a site-survey tool shows...",
    options: [
      "CPU temperature of the AP",
      "Signal strength/coverage across a physical area",
      "The firewall rules",
      "DHCP scope utilization",
    ],
    answer: 1,
    explain: "A Wi-Fi heat map overlays measured signal strength (and sometimes interference/SNR) onto a floor plan, revealing coverage gaps and where to add or move APs.",
  },
  {
    q: "OFDMA, introduced in Wi-Fi 6, improves efficiency by...",
    options: [
      "Serving multiple clients within a channel using subcarrier resource units",
      "Encrypting frames twice",
      "Adding more SSIDs",
      "Disabling MIMO",
    ],
    answer: 0,
    explain: "OFDMA divides a channel into resource units so the AP can serve several clients simultaneously in one transmission, greatly improving efficiency in dense environments.",
  },
  {
    q: "The main benefit of a wireless controller (WLC) managing many APs is...",
    options: [
      "Each AP must be configured by hand",
      "Centralized configuration, monitoring, roaming, and channel/power management for all APs",
      "It removes the need for switches",
      "It provides Internet access",
    ],
    answer: 1,
    explain: "A wireless LAN controller centrally manages 'thin' APs — pushing configs, coordinating channels/power (RRM), enabling fast roaming, and providing unified monitoring.",
  },
  {
    q: "Which factor most reduces Wi-Fi signal as distance increases?",
    options: ["DNS latency", "Free-space path loss and obstacles/absorption", "MAC address size", "VLAN tagging"],
    answer: 1,
    explain: "RF weakens with distance (path loss) and is absorbed/reflected by walls, floors, and objects. This is why AP placement and a site survey matter for reliable coverage.",
  },
  {
    q: "Band steering encourages capable clients to...",
    options: [
      "Use the less congested 5 GHz band instead of 2.4 GHz",
      "Disconnect from the network",
      "Switch to wired",
      "Use WEP",
    ],
    answer: 0,
    explain: "Band steering nudges dual-band clients onto 5 GHz (more channels, higher speed), relieving congestion on the crowded 2.4 GHz band.",
  },
  {
    q: "A captive portal is commonly used to...",
    options: [
      "Encrypt the entire LAN",
      "Force users to authenticate or accept terms via a web page before granting network access (e.g., guest Wi-Fi)",
      "Assign VLANs to switches",
      "Route between subnets",
    ],
    answer: 1,
    explain: "A captive portal intercepts a new client's web traffic and redirects to a login/terms page, common on guest and public Wi-Fi before allowing Internet access.",
  },
  {
    q: "802.11n (Wi-Fi 4) introduced which key capability?",
    options: [
      "MIMO and operation on both 2.4 and 5 GHz",
      "Operation only at 900 MHz",
      "Removal of encryption",
      "Single-antenna only",
    ],
    answer: 0,
    explain: "802.11n added MIMO (multiple spatial streams), channel bonding, and dual-band (2.4/5 GHz) operation, substantially increasing throughput over 802.11g/a.",
  },
  {
    q: "The main reason to lower AP transmit power in a dense deployment is to...",
    options: [
      "Save electricity only",
      "Reduce co-channel interference and encourage clients to roam to nearer APs",
      "Increase coverage overlap",
      "Disable roaming",
    ],
    answer: 1,
    explain: "In high-density designs, reducing power (and adding more APs) shrinks each cell, cutting co-channel interference and improving capacity as clients associate with the closest AP.",
  },
  {
    q: "A client showing a very low SNR (signal-to-noise ratio) will experience...",
    options: [
      "Higher throughput",
      "Lower data rates, retransmissions, and possible drops",
      "No effect",
      "Automatic encryption",
    ],
    answer: 1,
    explain: "Low SNR means the signal is barely above the noise floor, forcing lower modulation/data rates and causing retransmissions — degrading throughput and reliability.",
  },
  {
    q: "WPA3-Personal's main improvement over WPA2-Personal is...",
    options: [
      "Removing all encryption",
      "SAE, which protects against offline password-guessing (dictionary) attacks",
      "Using WEP keys",
      "Requiring no password",
    ],
    answer: 1,
    explain: "WPA3-Personal replaces the PSK 4-way handshake with SAE (Dragonfly), providing forward secrecy and resistance to offline dictionary attacks even with weak passwords.",
  },
  {
    q: "Which tool/setting helps identify the least congested Wi-Fi channel to use?",
    options: [
      "A Wi-Fi analyzer / spectrum analyzer",
      "A cable certifier",
      "A punch-down tool",
      "An OTDR",
    ],
    answer: 0,
    explain: "A Wi-Fi/spectrum analyzer shows which channels neighboring APs and interference occupy, guiding you to the cleanest channel for your AP.",
  },
];
