// ── Module 07 — Cloud Computing & Remote Access · expansion pool ────────────
QUESTIONS["07"].push(
  {
    q: "In which cloud model does the customer manage the OS and applications but not the physical hardware?",
    options: ["SaaS", "PaaS", "IaaS", "FaaS"],
    answer: 2,
    explain: "IaaS provides compute/storage/network; the customer manages the guest OS, apps, and data on top.",
  },
  {
    q: "A managed platform where developers deploy code without managing servers is...",
    options: ["IaaS", "PaaS", "SaaS", "DaaS"],
    answer: 1,
    explain: "PaaS provides a managed runtime/platform (OS, middleware, databases) so developers focus on code.",
  },
  {
    q: "Gmail and Salesforce are examples of which cloud service model?",
    options: ["IaaS", "PaaS", "SaaS", "Bare metal"],
    answer: 2,
    explain: "SaaS delivers complete applications over the network; the provider manages everything beneath the app.",
  },
  {
    q: "Which deployment model dedicates cloud infrastructure to a single organization?",
    options: ["Public", "Private", "Community", "Hybrid"],
    answer: 1,
    explain: "A private cloud is used exclusively by one organization (on-prem or hosted), offering more control and isolation.",
  },
  {
    q: "A hybrid cloud combines...",
    options: [
      "Two public clouds only",
      "Private/on-prem and public cloud resources working together",
      "Two data centers with no cloud",
      "Only SaaS apps",
    ],
    answer: 1,
    explain: "Hybrid integrates private/on-prem and public cloud so workloads/data can move between them (enabling cloud bursting).",
  },
  {
    q: "Which cloud characteristic means resources scale automatically with demand?",
    options: ["Multitenancy", "Elasticity", "Measured service", "Broad access"],
    answer: 1,
    explain: "Elasticity lets capacity grow or shrink automatically to match load, so you pay for what you use.",
  },
  {
    q: "Multitenancy in public cloud means...",
    options: [
      "One customer per physical server",
      "Multiple customers securely share pooled physical infrastructure",
      "Multiple ISPs",
      "Several VLANs on a switch",
    ],
    answer: 1,
    explain: "Multitenancy lets many customers (tenants) share pooled resources, logically isolated from one another.",
  },
  {
    q: "A Type 1 hypervisor runs...",
    options: [
      "As an app on a host OS",
      "Directly on the hardware with no underlying OS",
      "Only in the cloud",
      "Inside a container",
    ],
    answer: 1,
    explain: "Type 1 (bare-metal) hypervisors (ESXi, Hyper-V, KVM) run directly on hardware; Type 2 run atop a host OS.",
  },
  {
    q: "Compared to VMs, containers...",
    options: [
      "Each include a full guest OS",
      "Share the host kernel and are lighter and faster to start",
      "Cannot be networked",
      "Require a Type 1 hypervisor",
    ],
    answer: 1,
    explain: "Containers virtualize at the OS level, sharing the host kernel and packaging just the app + dependencies (e.g., Docker).",
  },
  {
    q: "NFV (Network Function Virtualization) means...",
    options: [
      "Running network functions (firewalls, routers, LBs) as software instead of dedicated hardware",
      "A new cabling standard",
      "A wireless protocol",
      "A DNS record",
    ],
    answer: 0,
    explain: "NFV replaces purpose-built appliances with software instances on standard servers, improving flexibility and cost.",
  },
  {
    q: "VDI provides users with...",
    options: [
      "A physical PC",
      "Centrally hosted virtual desktops accessed remotely",
      "A DNS service",
      "A routing protocol",
    ],
    answer: 1,
    explain: "Virtual Desktop Infrastructure hosts desktops as VMs in the data center/cloud; users connect remotely, keeping data centralized.",
  },
  {
    q: "Which provides a dedicated private connection to a cloud provider (bypassing the public Internet)?",
    options: [
      "AWS Direct Connect / Azure ExpressRoute",
      "APIPA",
      "A captive portal",
      "Split horizon",
    ],
    answer: 0,
    explain: "Direct Connect/ExpressRoute give a private link to the cloud with more consistent latency, bandwidth, and security.",
  },
  {
    q: "A site-to-site VPN connects...",
    options: [
      "A single roaming laptop",
      "Two entire networks (e.g., branch and HQ) over an encrypted tunnel",
      "Two public web servers directly",
      "A switch to an AP",
    ],
    answer: 1,
    explain: "Site-to-site VPNs (usually IPsec on routers/firewalls) link whole networks so users at each site communicate transparently.",
  },
  {
    q: "A clientless VPN typically works through...",
    options: [
      "A dedicated installed application",
      "A browser using SSL/TLS (an HTTPS portal)",
      "A serial cable",
      "SNMP",
    ],
    answer: 1,
    explain: "Clientless (SSL/TLS) VPNs let users reach internal web apps via an HTTPS portal without installing a full VPN client.",
  },
  {
    q: "Out-of-band management refers to...",
    options: [
      "Managing devices over the production network",
      "A separate dedicated path (console/cellular) to manage devices even during a network outage",
      "Wireless management only",
      "Cloud billing",
    ],
    answer: 1,
    explain: "Out-of-band management uses a separate channel so admins reach devices even when the production network is down.",
  },
  {
    q: "A jump box (bastion host) is used to...",
    options: [
      "Serve public web pages",
      "Provide a single hardened, monitored entry point for administering internal systems",
      "Store backups",
      "Assign DHCP",
    ],
    answer: 1,
    explain: "Admins connect to a hardened jump box first, then reach internal systems — concentrating and auditing privileged access.",
  },
  {
    q: "'Cloud bursting' describes...",
    options: [
      "A cloud outage",
      "Overflowing peak workload from a private cloud into the public cloud on demand",
      "Deleting cloud data",
      "A DDoS attack",
    ],
    answer: 1,
    explain: "Cloud bursting handles demand spikes by temporarily shifting overflow workloads to the public cloud (a hybrid strategy).",
  },
  {
    q: "In the IaaS shared-responsibility model, the customer secures...",
    options: [
      "Physical data center security",
      "The guest OS, applications, data, and access",
      "The hypervisor host hardware",
      "Nothing at all",
    ],
    answer: 1,
    explain: "For IaaS, the provider secures the physical/host layer; the customer secures the OS, apps, data, and access.",
  },
  {
    q: "The public cloud's pay-as-you-go model primarily converts...",
    options: [
      "OpEx to CapEx",
      "CapEx to OpEx (usage-based operating cost)",
      "Bandwidth to latency",
      "VLANs to subnets",
    ],
    answer: 1,
    explain: "Cloud shifts big upfront hardware purchases (CapEx) to usage-based operating expense (OpEx), improving agility.",
  },
  {
    q: "Which remote-access risk is greatest when RDP (3389) is exposed to the Internet?",
    options: [
      "Improved performance",
      "Brute-force attacks and ransomware entry",
      "Better encryption",
      "Automatic patching",
    ],
    answer: 1,
    explain: "Internet-facing RDP is a top ransomware vector; place it behind a VPN/gateway, require MFA, and restrict source IPs.",
  },
  {
    q: "SD-WAN improves WAN connectivity by...",
    options: [
      "Requiring a single MPLS circuit",
      "Centrally steering traffic across multiple links (MPLS, broadband, LTE) by policy",
      "Removing encryption",
      "Eliminating routers",
    ],
    answer: 1,
    explain: "SD-WAN abstracts and manages multiple transports, routing app traffic over the best path and reducing reliance on MPLS.",
  },
  {
    q: "Deploying across multiple availability zones/regions primarily improves...",
    options: [
      "Latency only",
      "Resilience by isolating failures across independent locations",
      "Security by removing backups",
      "Billing accuracy",
    ],
    answer: 1,
    explain: "Spreading resources across AZs/regions isolates failures (power, hardware, disaster) so one zone's outage doesn't take everything down.",
  },
  {
    q: "A VPN concentrator's role is to...",
    options: [
      "Assign IP addresses",
      "Terminate many VPN tunnels and handle their encryption/authentication",
      "Resolve DNS",
      "Provide Wi-Fi",
    ],
    answer: 1,
    explain: "A VPN concentrator aggregates and terminates numerous VPN connections, managing each tunnel's encryption and authentication.",
  },
  {
    q: "Which authentication enhancement should always protect VPN and RDP gateways?",
    options: [
      "A single static password",
      "Multi-factor authentication (MFA)",
      "Disabled logging",
      "Open access",
    ],
    answer: 1,
    explain: "MFA adds a second factor so a stolen password alone can't breach remote-access services.",
  },
  {
    q: "In a full-tunnel remote-access VPN, what happens to the user's non-corporate traffic?",
    options: [
      "It bypasses the VPN",
      "It also goes through the VPN (all traffic tunneled)",
      "It is dropped",
      "It is unencrypted",
    ],
    answer: 1,
    explain: "Full tunnel sends all client traffic through the VPN (more secure, more load); split tunnel sends only corporate traffic.",
  },
  {
    q: "DaaS (Desktop as a Service) is essentially...",
    options: [
      "Cloud-hosted VDI delivered as a subscription",
      "A database service",
      "A DNS service",
      "A cabling standard",
    ],
    answer: 0,
    explain: "DaaS is VDI delivered from the cloud as a managed subscription, offloading desktop hosting to the provider.",
  },
  {
    q: "Which describes 'resource pooling' in cloud computing?",
    options: [
      "Dedicated hardware per customer",
      "Provider resources serve multiple customers dynamically from a shared pool",
      "A single VLAN",
      "A backup rotation",
    ],
    answer: 1,
    explain: "Resource pooling dynamically assigns shared provider resources to customers as needed — a core NIST cloud characteristic.",
  },
  {
    q: "A community cloud is best suited for...",
    options: [
      "A single company",
      "Several organizations with shared requirements or compliance (e.g., healthcare, government)",
      "Home users",
      "Any random public users",
    ],
    answer: 1,
    explain: "A community cloud is shared by organizations with common needs/compliance, splitting cost while meeting shared requirements.",
  },
  {
    q: "Which is a security advantage of centralizing desktops/apps (VDI/SaaS)?",
    options: [
      "No authentication needed",
      "Data and patching stay centralized rather than on each endpoint",
      "Endpoints never need protection",
      "It removes the need for backups",
    ],
    answer: 1,
    explain: "Centralizing data and updates reduces exposure from lost/unpatched endpoints, though access control still matters.",
  },
  {
    q: "A virtual switch (vSwitch) exists...",
    options: [
      "As a physical device only",
      "Inside the hypervisor to connect VMs to each other and the physical network",
      "In the DNS server",
      "In the firewall CPU",
    ],
    answer: 1,
    explain: "A vSwitch runs in the hypervisor, providing virtual NIC connectivity among VMs and bridging to physical NICs.",
  },
  {
    q: "Which is TRUE of measured service (metered usage) in cloud?",
    options: [
      "Usage is untracked",
      "Resource use is monitored and billed, giving transparency and pay-per-use",
      "It is always free",
      "It prevents scaling",
    ],
    answer: 1,
    explain: "Measured service monitors and reports resource consumption, enabling usage-based billing and transparency.",
  },
  {
    q: "Which remote-access method gives a text/command-line session to a Linux server securely?",
    options: ["RDP", "SSH", "Telnet", "SMTP"],
    answer: 1,
    explain: "SSH (port 22) provides an encrypted CLI session with key-based authentication — the standard for Unix/Linux remote admin.",
  },
  {
    q: "Elastic auto-scaling most directly helps with...",
    options: [
      "Fixed monthly cost regardless of load",
      "Handling variable demand by adding/removing capacity automatically",
      "Encrypting data",
      "Assigning MAC addresses",
    ],
    answer: 1,
    explain: "Auto-scaling adds instances during spikes and removes them when idle, matching capacity (and cost) to demand.",
  },
  {
    q: "Which is a benefit of infrastructure as code (IaC) in cloud deployments?",
    options: [
      "Manual, one-off configuration",
      "Repeatable, version-controlled, automated provisioning",
      "No documentation",
      "Slower deployments",
    ],
    answer: 1,
    explain: "IaC defines infrastructure in templates/code, enabling consistent, version-controlled, automated deployments.",
  },
  {
    q: "Which best mitigates the risk of a compromised cloud admin account?",
    options: [
      "Sharing the account widely",
      "MFA, least privilege, and separate admin roles with logging",
      "Disabling logging",
      "Using one password everywhere",
    ],
    answer: 1,
    explain: "MFA, least-privilege role separation, and audit logging limit both the chance and the impact of admin-account compromise.",
  },
  {
    q: "Which describes 'broad network access' as a cloud characteristic?",
    options: [
      "Services are reachable over the network from diverse client devices",
      "Only one device can connect",
      "Access requires a private line",
      "It disables the Internet",
    ],
    answer: 0,
    explain: "Broad network access means cloud services are available over the network to many client types (laptops, phones, thin clients).",
  },
  {
    q: "A remote worker needs the same experience as being in the office, with corporate traffic secured. Best fit?",
    options: [
      "Open Wi-Fi",
      "Client-to-site VPN with MFA (full or split tunnel per policy)",
      "Telnet",
      "Public FTP",
    ],
    answer: 1,
    explain: "A remote-access (client-to-site) VPN with MFA securely connects the user's device to the corporate network.",
  },
  {
    q: "Which is a drawback of full-tunnel VPN?",
    options: [
      "It is less secure",
      "It concentrates all user traffic through the VPN, adding load/latency",
      "It cannot encrypt",
      "It bypasses corporate policy",
    ],
    answer: 1,
    explain: "Full tunnel routes everything through the VPN, increasing bandwidth/latency on the concentrator; split tunnel reduces that at some risk.",
  },
  {
    q: "Which cloud role would a load balancer most likely fill?",
    options: [
      "Assigning DNS names",
      "Distributing incoming requests across multiple backend instances",
      "Encrypting disks",
      "Storing logs",
    ],
    answer: 1,
    explain: "A cloud load balancer spreads traffic across backend instances for scalability and availability.",
  },
  {
    q: "Which is the safest way to expose an internal web app to remote users?",
    options: [
      "Open port 3389 to the Internet",
      "A reverse proxy / clientless SSL VPN with authentication and MFA",
      "Telnet",
      "A public open share",
    ],
    answer: 1,
    explain: "A reverse proxy or clientless SSL VPN with strong authentication (MFA) publishes internal apps securely without broad exposure.",
  },
  {
    q: "Snapshots of a VM are primarily used for...",
    options: [
      "Increasing CPU",
      "Capturing a point-in-time state for quick rollback or cloning",
      "Assigning IPs",
      "Encrypting the network",
    ],
    answer: 1,
    explain: "Snapshots record a VM's state at a moment, enabling fast rollback after a change or cloning — but they are not a full backup strategy.",
  },
  {
    q: "Which is a risk of 'shadow IT' cloud usage?",
    options: [
      "Better governance",
      "Unsanctioned services bypass security controls and data governance",
      "Lower cost always",
      "Improved compliance",
    ],
    answer: 1,
    explain: "Shadow IT (unapproved cloud services) evades security, monitoring, and data-governance controls, creating risk.",
  },
  {
    q: "Which authentication factor category does a hardware token belong to?",
    options: [
      "Something you know",
      "Something you have",
      "Something you are",
      "Somewhere you are",
    ],
    answer: 1,
    explain: "A hardware token is 'something you have.' MFA combines categories (know/have/are) for stronger authentication.",
  },
  {
    q: "Which best describes containers' orchestration (e.g., Kubernetes)?",
    options: [
      "Manually starting each container",
      "Automated deployment, scaling, and management of many containers",
      "A DNS record type",
      "A cabling standard",
    ],
    answer: 1,
    explain: "Orchestrators like Kubernetes automate deploying, scaling, healing, and networking of containerized workloads.",
  },
  {
    q: "A key benefit of a private link (ExpressRoute/Direct Connect) over Internet VPN is...",
    options: [
      "Lower reliability",
      "More predictable performance and a private path off the public Internet",
      "No need for any security",
      "It is always free",
    ],
    answer: 1,
    explain: "Dedicated private links offer consistent bandwidth/latency and keep traffic off the public Internet, at higher cost than a VPN.",
  }
);
