// ── Module 09 — Network Risk Management (35) ────────────────────────────────
QUESTIONS["09"] = [
  {
    q: "In security terms, a 'vulnerability' is...",
    options: [
      "An event that causes harm",
      "A weakness that could be exploited",
      "The likelihood of an attack",
      "A security control",
    ],
    answer: 1,
    explain: "A vulnerability is a weakness (in software, config, or process). A threat is what might exploit it; risk is the likelihood and impact of that exploitation.",
  },
  {
    q: "Risk is commonly expressed as a function of...",
    options: [
      "Threat × vulnerability (likelihood) and impact",
      "Bandwidth × latency",
      "Cost of hardware only",
      "Number of users",
    ],
    answer: 0,
    explain: "Risk considers the likelihood that a threat exploits a vulnerability and the impact if it does. Controls reduce likelihood and/or impact.",
  },
  {
    q: "The three pillars of the CIA triad are...",
    options: [
      "Confidentiality, Integrity, Availability",
      "Control, Identity, Access",
      "Cost,Impact, Alerting",
      "Cryptography, Isolation, Auditing",
    ],
    answer: 0,
    explain: "The CIA triad — Confidentiality (secrecy), Integrity (accuracy/no tampering), and Availability (accessible when needed) — is the foundation of information security.",
  },
  {
    q: "A DoS (Denial of Service) attack aims to...",
    options: [
      "Steal passwords quietly",
      "Overwhelm a system/service so it becomes unavailable to legitimate users",
      "Encrypt files for ransom",
      "Redirect DNS",
    ],
    answer: 1,
    explain: "A DoS floods or crashes a target to exhaust its resources, denying service to legitimate users. A DDoS uses many distributed sources (often a botnet) to amplify it.",
  },
  {
    q: "What distinguishes a DDoS from a DoS attack?",
    options: [
      "DDoS uses many distributed/compromised sources (a botnet)",
      "DDoS is always encrypted",
      "DoS targets only DNS",
      "There is no difference",
    ],
    answer: 0,
    explain: "A DDoS (Distributed DoS) comes from many coordinated sources — typically a botnet — making it far harder to block by source and far more powerful than a single-source DoS.",
  },
  {
    q: "In a man-in-the-middle (on-path) attack, the attacker...",
    options: [
      "Physically steals a server",
      "Secretly intercepts/relays communication between two parties",
      "Deletes all logs",
      "Sends spam email",
    ],
    answer: 1,
    explain: "An on-path (MITM) attacker positions between two parties to intercept, read, or alter traffic — often via ARP spoofing, rogue APs, or DNS manipulation.",
  },
  {
    q: "ARP spoofing/poisoning enables an attacker to...",
    options: [
      "Assign IP addresses",
      "Associate their MAC with another host's IP to intercept LAN traffic",
      "Break WPA3",
      "Summarize routes",
    ],
    answer: 1,
    explain: "By sending forged ARP replies, an attacker maps a victim's (or the gateway's) IP to the attacker's MAC, redirecting traffic through them — a common MITM technique. Dynamic ARP Inspection mitigates it.",
  },
  {
    q: "Which attack forges the source address of packets to impersonate a trusted host?",
    options: ["Spoofing", "Phishing", "Fuzzing", "Tailgating"],
    answer: 0,
    explain: "Spoofing falsifies identifying information (IP, MAC, or email sender) to impersonate a trusted source, bypassing filters or hiding the attacker's origin.",
  },
  {
    q: "Phishing is best categorized as which type of attack?",
    options: ["Physical", "Social engineering", "Cryptographic", "Routing"],
    answer: 1,
    explain: "Phishing is social engineering — tricking users (usually via deceptive email/messages) into revealing credentials or running malware. Spear phishing targets specific individuals.",
  },
  {
    q: "'Tailgating' (piggybacking) is a ___ attack.",
    options: ["Network", "Physical/social", "Cryptographic", "Wireless"],
    answer: 1,
    explain: "Tailgating is following an authorized person through a secure door without badging in — a physical/social-engineering attack that mantraps and awareness training help prevent.",
  },
  {
    q: "Ransomware primarily harms which part of the CIA triad first?",
    options: ["Confidentiality only", "Availability (and often confidentiality)", "Nothing", "Only integrity"],
    answer: 1,
    explain: "Ransomware encrypts data to deny access (availability) and increasingly also exfiltrates it (confidentiality) for double extortion. Good offline backups are the key defense.",
  },
  {
    q: "Which malware disguises itself as legitimate software to trick users into running it?",
    options: ["Trojan", "Worm", "Rootkit", "Logic bomb"],
    answer: 0,
    explain: "A Trojan horse masquerades as a useful/benign program but carries a malicious payload. Unlike worms, it relies on the user to run it.",
  },
  {
    q: "A worm differs from a virus in that a worm...",
    options: [
      "Requires a host file and user action",
      "Self-replicates and spreads across networks without user interaction",
      "Cannot spread at all",
      "Only affects printers",
    ],
    answer: 1,
    explain: "A worm self-propagates over the network by exploiting vulnerabilities, needing no host file or user action — enabling rapid, wide spread (e.g., WannaCry).",
  },
  {
    q: "A zero-day vulnerability is one that...",
    options: [
      "Has been patched for years",
      "Is unknown to the vendor / has no available patch when exploited",
      "Only affects zero users",
      "Is a false positive",
    ],
    answer: 1,
    explain: "A zero-day is a flaw exploited before the vendor has a patch (defenders have had 'zero days' to fix it), making it especially dangerous.",
  },
  {
    q: "What is the purpose of a vulnerability scan?",
    options: [
      "To exploit systems for profit",
      "To identify known weaknesses/misconfigurations so they can be remediated",
      "To encrypt the network",
      "To assign IP addresses",
    ],
    answer: 1,
    explain: "A vulnerability scan (e.g., Nessus/OpenVAS) automatically checks systems against known vulnerabilities and misconfigurations, producing a prioritized remediation list.",
  },
  {
    q: "How does a penetration test differ from a vulnerability scan?",
    options: [
      "A pen test actively attempts to exploit weaknesses to demonstrate real impact",
      "They are identical",
      "A pen test only reads documentation",
      "A vulnerability scan exploits systems",
    ],
    answer: 0,
    explain: "A vulnerability scan finds and reports weaknesses; a penetration test goes further by (with authorization) exploiting them to show real-world impact and chained attacks.",
  },
  {
    q: "CVSS is used to...",
    options: [
      "Encrypt VLANs",
      "Score the severity of vulnerabilities on a standardized scale",
      "Assign MAC addresses",
      "Route packets",
    ],
    answer: 1,
    explain: "CVSS (Common Vulnerability Scoring System) rates vulnerability severity (0–10) based on exploitability and impact, helping teams prioritize remediation.",
  },
  {
    q: "A CVE identifier refers to...",
    options: [
      "A publicly cataloged, uniquely numbered known vulnerability",
      "A cabling standard",
      "A VLAN configuration",
      "A cloud region",
    ],
    answer: 0,
    explain: "CVE (Common Vulnerabilities and Exposures) assigns a unique ID (e.g., CVE-2021-44228) to each publicly known vulnerability for consistent reference across tools and vendors.",
  },
  {
    q: "The principle of 'least privilege' means...",
    options: [
      "Everyone is an administrator",
      "Users and processes get only the minimum access needed to do their job",
      "No one has any access",
      "Access is granted permanently",
    ],
    answer: 1,
    explain: "Least privilege limits each user/process to the minimum rights required, shrinking the attack surface and containing damage if an account is compromised.",
  },
  {
    q: "Separation of duties is a control that...",
    options: [
      "Gives one person total control",
      "Splits critical tasks among multiple people to prevent fraud/errors",
      "Removes all logging",
      "Speeds up approvals by skipping review",
    ],
    answer: 1,
    explain: "Separation of duties divides sensitive functions so no single individual can complete a risky process alone (e.g., request vs approve), reducing fraud and mistakes.",
  },
  {
    q: "A security policy is important because it...",
    options: [
      "Replaces all technical controls",
      "Defines rules, responsibilities, and expected behavior to guide and enforce security",
      "Is only for the IT team's amusement",
      "Configures the firewall automatically",
    ],
    answer: 1,
    explain: "Policies establish the organization's security rules, roles, and acceptable behavior — the governance foundation that technical controls, training, and audits enforce.",
  },
  {
    q: "Which of the following is a physical security control?",
    options: ["Firewall ACL", "Badge readers, locks, mantraps, and security cameras", "Antivirus", "TLS encryption"],
    answer: 1,
    explain: "Physical controls (locks, badge access, mantraps, CCTV, security guards) protect the tangible assets and facilities — a critical layer alongside logical controls.",
  },
  {
    q: "The purpose of MFA (multi-factor authentication) is to...",
    options: [
      "Use only one password",
      "Require two or more independent factors (know/have/are), so a stolen password alone is insufficient",
      "Disable passwords entirely",
      "Encrypt the LAN",
    ],
    answer: 1,
    explain: "MFA combines factors — something you know, have, and/or are — so compromising one (like a password) is not enough to gain access, greatly reducing account takeover risk.",
  },
  {
    q: "A 'defense in depth' strategy means...",
    options: [
      "Relying on a single strong firewall",
      "Layering multiple, diverse security controls so a failure of one doesn't compromise everything",
      "Disabling logging",
      "Using one password everywhere",
    ],
    answer: 1,
    explain: "Defense in depth layers controls (physical, network, host, application, data, policy) so that if one layer fails, others still protect the asset.",
  },
  {
    q: "A social-engineering awareness program primarily reduces the risk of...",
    options: [
      "Cable faults",
      "Phishing and pretexting attacks that target people",
      "Fiber attenuation",
      "IP conflicts",
    ],
    answer: 1,
    explain: "Since many breaches start by deceiving people, user training on recognizing phishing, pretexting, and suspicious requests is a key control against social engineering.",
  },
  {
    q: "In business continuity, RTO (Recovery Time Objective) defines...",
    options: [
      "The maximum acceptable data loss",
      "The target time to restore a service after an outage",
      "The cost of hardware",
      "The number of users",
    ],
    answer: 1,
    explain: "RTO is how quickly a service must be restored after disruption. RPO (Recovery Point Objective) defines how much data loss (time since last backup) is acceptable.",
  },
  {
    q: "RPO (Recovery Point Objective) defines...",
    options: [
      "How fast to recover",
      "The maximum acceptable amount of data loss, measured in time",
      "The number of firewalls",
      "The encryption strength",
    ],
    answer: 1,
    explain: "RPO sets how much data (in time) you can afford to lose — e.g., an RPO of 1 hour means backups/replication must be no more than an hour apart.",
  },
  {
    q: "The 3-2-1 backup rule recommends...",
    options: [
      "3 passwords, 2 admins, 1 firewall",
      "3 copies of data, on 2 different media, with 1 copy offsite",
      "3 VLANs, 2 subnets, 1 router",
      "3 backups per day",
    ],
    answer: 1,
    explain: "The 3-2-1 rule: keep 3 copies of data on 2 types of media with 1 copy offsite (or offline/immutable) — resilient against hardware failure, disaster, and ransomware.",
  },
  {
    q: "A honeypot is deployed to...",
    options: [
      "Serve production traffic",
      "Lure and study attackers using a decoy system, and detect intrusions",
      "Store real customer data",
      "Provide DHCP",
    ],
    answer: 1,
    explain: "A honeypot is a decoy designed to attract attackers, diverting them from real assets while generating intelligence and early warning of malicious activity.",
  },
  {
    q: "Which document formalizes how an organization will respond to a security incident?",
    options: [
      "Incident response plan",
      "Cable label",
      "Subnet plan",
      "SLA only",
    ],
    answer: 0,
    explain: "An incident response plan defines roles, steps (preparation, identification, containment, eradication, recovery, lessons learned), and communications for handling incidents.",
  },
  {
    q: "Patching/updating systems reduces risk primarily by...",
    options: [
      "Adding new vulnerabilities",
      "Closing known vulnerabilities before they can be exploited",
      "Increasing bandwidth",
      "Disabling MFA",
    ],
    answer: 1,
    explain: "Timely patch management remediates known vulnerabilities, removing the low-hanging fruit that most attacks and worms rely on.",
  },
  {
    q: "A 'brute-force' attack attempts to...",
    options: [
      "Physically break a server",
      "Systematically try many passwords/keys until one works",
      "Flood a link with traffic",
      "Redirect DNS",
    ],
    answer: 1,
    explain: "Brute-force attacks try many combinations to guess credentials or keys. Account lockouts, rate limiting, strong passwords, and MFA mitigate them.",
  },
  {
    q: "Which control BEST limits the damage of a compromised user account?",
    options: [
      "Giving every user admin rights",
      "Least privilege plus network segmentation",
      "Disabling backups",
      "Sharing passwords",
    ],
    answer: 1,
    explain: "Least privilege limits what a compromised account can do, and segmentation limits where it can reach — together containing the blast radius of a breach.",
  },
  {
    q: "A risk that an organization chooses to accept rather than mitigate is an example of...",
    options: ["Risk acceptance", "Risk transference", "Risk avoidance", "Risk elimination"],
    answer: 0,
    explain: "Risk responses include acceptance (tolerate it), avoidance (stop the activity), transference (e.g., insurance/outsourcing), and mitigation (reduce it with controls).",
  },
  {
    q: "Buying cyber-insurance to cover potential breach costs is an example of risk...",
    options: ["Avoidance", "Acceptance", "Transference", "Mitigation"],
    answer: 2,
    explain: "Risk transference shifts the financial impact to a third party (like an insurer). It doesn't reduce the likelihood of the event, only who bears the cost.",
  },
];
