// ── Module 10 — Security in Network Design · expansion pool ─────────────────
QUESTIONS["10"].push(
  {
    q: "A stateful firewall differs from a stateless one because it...",
    options: [
      "Checks each packet in isolation",
      "Tracks connection state and auto-permits legitimate return traffic",
      "Cannot use ports",
      "Works only at Layer 1",
    ],
    answer: 1,
    explain: "A stateful firewall maintains a connection table, understanding sessions and allowing return traffic — smarter than a stateless filter.",
  },
  {
    q: "An NGFW adds which capability over a traditional firewall?",
    options: [
      "Only faster ports",
      "Application awareness, deep packet inspection, and integrated IPS",
      "DHCP only",
      "Cable testing",
    ],
    answer: 1,
    explain: "NGFWs combine stateful filtering with app/user awareness, DPI, and IPS for granular, identity-based control.",
  },
  {
    q: "A WAF specifically protects...",
    options: [
      "Physical doors",
      "Web applications from attacks like SQL injection and XSS",
      "Fiber cables",
      "Wireless channels",
    ],
    answer: 1,
    explain: "A Web Application Firewall inspects HTTP(S) traffic and blocks app-layer attacks a network firewall would miss.",
  },
  {
    q: "In an ACL, traffic matching no rule is typically...",
    options: [
      "Always permitted",
      "Denied by the implicit deny-all at the end",
      "Encrypted",
      "Logged and forwarded",
    ],
    answer: 1,
    explain: "Most ACLs end with an implicit deny; anything not explicitly permitted is dropped, and first match wins.",
  },
  {
    q: "How does an IDS differ from an IPS?",
    options: [
      "IDS blocks; IPS only alerts",
      "IDS detects and alerts (passive); IPS detects and blocks (inline)",
      "They are identical",
      "IPS only works on Wi-Fi",
    ],
    answer: 1,
    explain: "An IDS monitors and alerts out-of-band; an IPS sits inline and can actively drop malicious traffic.",
  },
  {
    q: "Signature-based detection is limited because it...",
    options: [
      "Detects unknown attacks well",
      "Only catches known attack patterns (blind to zero-days)",
      "Requires no updates",
      "Encrypts traffic",
    ],
    answer: 1,
    explain: "Signature matching relies on a database of known patterns, so novel/zero-day attacks without a signature slip through.",
  },
  {
    q: "Anomaly/behavior-based detection is better at...",
    options: [
      "Zero false positives",
      "Catching novel attacks by flagging deviations from a baseline",
      "Encrypting traffic",
      "Routing packets",
    ],
    answer: 1,
    explain: "Behavior/anomaly detection baselines normal and flags deviations, catching new attacks at the cost of more false positives.",
  },
  {
    q: "A DMZ (screened subnet) is used to...",
    options: [
      "Store the most sensitive internal data",
      "Host public-facing servers isolated from the internal LAN",
      "Replace the firewall",
      "Provide guest DHCP",
    ],
    answer: 1,
    explain: "A DMZ places Internet-facing services between outside and inside, so a compromise there doesn't directly expose the LAN.",
  },
  {
    q: "NAC (Network Access Control) enforces...",
    options: [
      "Only physical locks",
      "Identity and device posture checks before granting access",
      "Faster switching",
      "DNS resolution",
    ],
    answer: 1,
    explain: "NAC verifies who/what is connecting and whether it meets health requirements (patches, AV) before allowing access, often via 802.1X.",
  },
  {
    q: "The 'AAA' framework stands for...",
    options: [
      "Access, Authorization, Availability",
      "Authentication, Authorization, Accounting",
      "Auditing, Access, Alerting",
      "Authentication, Availability, Auditing",
    ],
    answer: 1,
    explain: "AAA = Authentication (who), Authorization (what may you do), Accounting (what you did) — the model behind RADIUS/TACACS+.",
  },
  {
    q: "TACACS+ is preferred over RADIUS for device administration because it...",
    options: [
      "Uses UDP and encrypts only the password",
      "Uses TCP, encrypts the entire payload, and separates AAA functions",
      "Only works on Wi-Fi",
      "Provides no accounting",
    ],
    answer: 1,
    explain: "TACACS+ (TCP 49) encrypts the whole packet and separates AAA, offering granular command authorization for device admin.",
  },
  {
    q: "802.1X provides...",
    options: [
      "Port-based access control requiring authentication before the port opens",
      "IP addressing",
      "Route summarization",
      "Cable testing",
    ],
    answer: 0,
    explain: "802.1X authenticates a supplicant via an authenticator (switch/AP) to a RADIUS server before allowing traffic on the port.",
  },
  {
    q: "Port security on a switch mitigates...",
    options: [
      "Fiber attenuation",
      "MAC flooding and rogue devices by limiting MACs per port",
      "DNS poisoning",
      "Weak Wi-Fi",
    ],
    answer: 1,
    explain: "Port security limits which/how many MAC addresses use a port and can shut it down on violation, stopping MAC flooding and rogue devices.",
  },
  {
    q: "DHCP snooping protects against...",
    options: [
      "Fiber loss",
      "Rogue DHCP servers by trusting only designated ports",
      "Slow DNS",
      "Weak passwords",
    ],
    answer: 1,
    explain: "DHCP snooping permits DHCP server responses only from trusted uplink ports and builds a binding table used by DAI/IPSG.",
  },
  {
    q: "Dynamic ARP Inspection (DAI) mitigates...",
    options: [
      "ARP spoofing/poisoning (MITM)",
      "DNS tunneling",
      "Wi-Fi jamming",
      "Crosstalk",
    ],
    answer: 0,
    explain: "DAI validates ARP packets against the DHCP snooping binding table, dropping forged ARP replies that enable MITM.",
  },
  {
    q: "IP Source Guard prevents...",
    options: [
      "IP spoofing by validating source IP/MAC against the DHCP snooping table",
      "Fiber loss",
      "Wi-Fi jamming",
      "Slow DNS",
    ],
    answer: 0,
    explain: "IP Source Guard permits only traffic whose source IP/MAC matches a legitimate binding, blocking IP spoofing on access ports.",
  },
  {
    q: "A forward proxy provides...",
    options: [
      "Routing between VLANs",
      "Content filtering, caching, and anonymity for internal clients accessing the Internet",
      "DHCP leases",
      "Physical security",
    ],
    answer: 1,
    explain: "A forward proxy sits between clients and the Internet, enabling URL/content filtering, caching, logging, and hiding client addresses.",
  },
  {
    q: "A SIEM is used to...",
    options: [
      "Assign IP addresses",
      "Aggregate and correlate logs/events for detection, investigation, and alerting",
      "Terminate fiber",
      "Provide Wi-Fi",
    ],
    answer: 1,
    explain: "A SIEM centralizes logs, correlates events across systems, and generates alerts/dashboards for security monitoring and compliance.",
  },
  {
    q: "Zero trust is based on...",
    options: [
      "Trusting everything inside the perimeter",
      "'Never trust, always verify' — authenticate/authorize every request regardless of location",
      "Removing authentication",
      "One shared password",
    ],
    answer: 1,
    explain: "Zero trust assumes no implicit trust by location; every access is continuously verified (identity, posture, least privilege).",
  },
  {
    q: "A UTM appliance combines...",
    options: [
      "Only a switch and router",
      "Multiple security functions (firewall, IPS, AV, content filter, VPN) in one device",
      "Only Wi-Fi and DHCP",
      "Cabling tools",
    ],
    answer: 1,
    explain: "Unified Threat Management consolidates several security features in one box — convenient but a potential single point of failure.",
  },
  {
    q: "Disabling unused switch ports helps because it...",
    options: [
      "Increases speed",
      "Prevents unauthorized devices from plugging in and gaining access",
      "Improves DNS",
      "Adds VLANs",
    ],
    answer: 1,
    explain: "Shutting unused ports (and placing them in an unused VLAN) stops an intruder from connecting to a live port to reach the network.",
  },
  {
    q: "Placing device management interfaces in a separate, restricted VLAN...",
    options: [
      "Improves Wi-Fi range",
      "Limits who can reach administration, reducing attack surface",
      "Increases broadcasts",
      "Speeds file transfers",
    ],
    answer: 1,
    explain: "An isolated management network confines sensitive admin access to authorized users, shrinking the attack surface.",
  },
  {
    q: "BPDU Guard is used to...",
    options: [
      "Prevent a rogue switch's BPDUs from manipulating the spanning tree",
      "Encrypt DNS",
      "Block Wi-Fi",
      "Assign IPs",
    ],
    answer: 0,
    explain: "BPDU Guard disables a PortFast access port that receives a BPDU, stopping an unauthorized switch from hijacking the topology.",
  },
  {
    q: "MAC filtering as a security control is...",
    options: [
      "Unbreakable",
      "Weak (MACs can be spoofed) but useful as a minor layer",
      "The strongest defense",
      "Only for fiber",
    ],
    answer: 1,
    explain: "MAC filtering can be bypassed by spoofing an allowed address; it is a minor layer, not a substitute for 802.1X or encryption.",
  },
  {
    q: "Egress filtering is used to...",
    options: [
      "Block only inbound traffic",
      "Control/inspect outbound traffic to stop exfiltration and malware call-home",
      "Assign VLANs",
      "Provide PoE",
    ],
    answer: 1,
    explain: "Egress filtering restricts outbound traffic to expected destinations/ports, helping stop data exfiltration and C2 traffic.",
  },
  {
    q: "Geo-IP blocking restricts access based on...",
    options: [
      "Cable quality",
      "The geographic location of the source",
      "The subnet mask",
      "DNS TTL",
    ],
    answer: 1,
    explain: "Geo-blocking allows/denies traffic by source country/region, reducing exposure to areas with no legitimate business need.",
  },
  {
    q: "A honeynet is...",
    options: [
      "A production network",
      "A network of honeypots to attract and study attackers",
      "A backup site",
      "A guest Wi-Fi",
    ],
    answer: 1,
    explain: "A honeynet is a whole decoy network of honeypots, isolated from production, used to study attackers and detect intrusions.",
  },
  {
    q: "A key security best practice for administrative access is...",
    options: [
      "Telnet with shared passwords",
      "SSH with individual accounts, MFA, and role-based authorization via AAA",
      "Open HTTP console to the Internet",
      "No authentication on the LAN",
    ],
    answer: 1,
    explain: "Use encrypted SSH, unique per-admin accounts, MFA, and centralized AAA with least-privilege roles and logging — never plaintext Telnet.",
  },
  {
    q: "The 'default deny' (fail-closed) principle means...",
    options: [
      "Allow everything by default",
      "Block everything not explicitly permitted",
      "Disable the firewall",
      "Permit all outbound",
    ],
    answer: 1,
    explain: "Default deny blocks anything not explicitly allowed — the safe posture behind ACL design and the implicit deny at the end of an ACL.",
  },
  {
    q: "Isolating IoT/OT devices on their own VLAN with tight ACLs is an example of...",
    options: [
      "Reducing security",
      "Microsegmentation to limit exposure of vulnerable devices",
      "Route summarization",
      "DNS caching",
    ],
    answer: 1,
    explain: "Isolating often-insecure IoT/OT devices limits what they can reach and what can reach them, containing their inherent risk.",
  },
  {
    q: "An IPS must be placed where relative to traffic?",
    options: [
      "Out-of-band via a mirror port",
      "Inline in the traffic path so it can drop malicious packets",
      "On a backup server",
      "In DNS",
    ],
    answer: 1,
    explain: "Because it actively blocks, an IPS sits inline; an IDS can watch a copy of traffic (SPAN/tap) since it only alerts.",
  },
  {
    q: "A jump box (bastion host) improves security by...",
    options: [
      "Serving public web pages",
      "Providing a single hardened, audited entry point for internal administration",
      "Storing backups",
      "Assigning IPs",
    ],
    answer: 1,
    explain: "Admins connect to a hardened, monitored jump box first, concentrating and logging privileged access through one chokepoint.",
  },
  {
    q: "Which is a 'detective' control (vs preventive)?",
    options: [
      "A locked door",
      "IDS alerts / camera footage that identify an incident after it occurs",
      "A firewall rule",
      "Encryption",
    ],
    answer: 1,
    explain: "Detective controls (IDS, cameras, log review, audits) reveal that an event happened; preventive controls stop it first.",
  },
  {
    q: "Content/URL filtering typically blocks...",
    options: [
      "CPU cycles",
      "Access to malicious or policy-violating website categories",
      "VLAN tags",
      "MAC addresses",
    ],
    answer: 1,
    explain: "URL/content filters (on a proxy or NGFW) block categories like malware, phishing, or inappropriate content, enforcing acceptable use.",
  },
  {
    q: "A VPN concentrator in a secure design is used to...",
    options: [
      "Assign DHCP",
      "Terminate and manage many encrypted VPN tunnels at the edge",
      "Filter web content",
      "Provide Wi-Fi",
    ],
    answer: 1,
    explain: "A VPN concentrator centralizes termination of numerous VPN tunnels, handling their authentication and encryption.",
  },
  {
    q: "Which combination best embodies defense in depth at the edge?",
    options: [
      "A single ACL",
      "Perimeter firewall + IPS + DMZ segmentation + MFA remote access + monitoring",
      "Only antivirus on one PC",
      "Only a Wi-Fi password",
    ],
    answer: 1,
    explain: "Layering firewall, IPS, DMZ, hardened MFA remote access, and monitoring means no single failure exposes the whole network.",
  },
  {
    q: "Which log source is MOST useful for investigating a suspected breach?",
    options: [
      "No logs (to save space)",
      "Centralized logs in a SIEM correlating firewall, auth, and endpoint events",
      "Only the DHCP lease file",
      "The cable colors",
    ],
    answer: 1,
    explain: "A SIEM correlating diverse logs gives the visibility needed to detect, scope, and investigate incidents — you can't defend what you can't see.",
  },
  {
    q: "A screened subnet typically uses firewall interfaces to separate...",
    options: [
      "Nothing",
      "The Internet, the DMZ, and the internal network",
      "Only two PCs",
      "Only wireless",
    ],
    answer: 1,
    explain: "A screened subnet (DMZ) sits behind firewall interfaces so Internet traffic reaches DMZ servers but not the internal LAN.",
  },
  {
    q: "Which reduces the risk of lateral movement after an initial compromise?",
    options: [
      "One flat network",
      "Network segmentation with least privilege between zones",
      "Shared admin passwords",
      "Disabling logging",
    ],
    answer: 1,
    explain: "Segmentation plus least privilege limits where a compromised host can reach, containing lateral movement.",
  },
  {
    q: "A reverse proxy in front of web servers can provide...",
    options: [
      "Client anonymity for browsing",
      "Load balancing, TLS termination, and an added security layer",
      "DHCP",
      "VLAN tagging",
    ],
    answer: 1,
    explain: "A reverse proxy fronts servers — distributing load, terminating TLS, caching, and shielding servers (a WAF often lives here).",
  },
  {
    q: "Which is TRUE about NAT as a security measure?",
    options: [
      "It encrypts traffic",
      "It hides internal private addresses but is not a substitute for a firewall",
      "It replaces authentication",
      "It stops all attacks",
    ],
    answer: 1,
    explain: "NAT provides address obscurity and blocks unsolicited inbound by default, but real filtering still requires a firewall.",
  },
  {
    q: "Which access-control model assigns permissions based on job function?",
    options: ["DAC", "RBAC (role-based)", "MAC", "None"],
    answer: 1,
    explain: "Role-Based Access Control grants permissions to roles (e.g., 'HR', 'Admin'), simplifying management and enforcing least privilege.",
  },
  {
    q: "A security posture assessment evaluates...",
    options: [
      "Cable colors",
      "The overall state of an organization's controls and readiness",
      "Wi-Fi channels only",
      "The DNS TTL",
    ],
    answer: 1,
    explain: "A posture assessment reviews policies, controls, and configurations to gauge security maturity and identify gaps.",
  },
  {
    q: "Which control most directly stops an unauthorized AP plugged into a wired port?",
    options: [
      "Longer DHCP leases",
      "802.1X / port security on the switch port",
      "Bigger subnets",
      "Disabling logging",
    ],
    answer: 1,
    explain: "802.1X (or port security) authenticates/limits devices on a wired port, preventing a rogue AP from gaining network access.",
  },
  {
    q: "Which is a benefit of centralized authentication (RADIUS/TACACS+) over local accounts?",
    options: [
      "Harder to manage",
      "Consistent policy, easier account revocation, and centralized logging",
      "No accountability",
      "Weaker security",
    ],
    answer: 1,
    explain: "Centralized AAA applies uniform policy, lets you disable a user everywhere at once, and logs access centrally.",
  },
  {
    q: "Which describes 'privilege escalation'?",
    options: [
      "Reducing user rights",
      "An attacker gaining higher access than originally granted",
      "Assigning a VLAN",
      "Resetting a switch",
    ],
    answer: 1,
    explain: "Privilege escalation is when an attacker moves from limited access to higher (e.g., admin) rights; least privilege and patching reduce it.",
  },
  {
    q: "A key reason to segment guest Wi-Fi from the corporate network is to...",
    options: [
      "Increase broadcasts",
      "Prevent untrusted guest devices from reaching internal resources",
      "Slow the Internet",
      "Share printers with guests",
    ],
    answer: 1,
    explain: "Isolating guests (own VLAN, Internet-only, client isolation) keeps untrusted devices away from internal systems.",
  },
  {
    q: "Which is the safest handling of firewall rule order?",
    options: [
      "Put deny-all first",
      "Place specific permits before broader rules, ending with implicit/explicit deny",
      "Random order",
      "One permit-any rule",
    ],
    answer: 1,
    explain: "Because first match wins, specific permits go before broader rules, and the list ends in a deny — anything not allowed is blocked.",
  }
);
