// ── Module 05 — Cabling · expansion pool ────────────────────────────────────
QUESTIONS["05"].push(
  {
    q: "Which copper category is rated for 1 Gbps at 100 m and is the common baseline today?",
    options: ["Cat 3", "Cat 5", "Cat 5e", "Cat 6a"],
    answer: 2,
    explain: "Cat 5e supports 1000BASE-T (1 Gbps) to 100 m and remains widely deployed; Cat 6a is used where 10 Gbps to 100 m is needed.",
  },
  {
    q: "What is the maximum distance for 10GBASE-T over Cat 6a?",
    options: ["55 m", "100 m", "300 m", "500 m"],
    answer: 1,
    explain: "Cat 6a supports 10 Gbps over the full 100 m; Cat 6 only reaches 10 Gbps to about 55 m.",
  },
  {
    q: "Which connector is used with twisted-pair Ethernet?",
    options: ["LC", "SC", "RJ-45", "BNC"],
    answer: 2,
    explain: "RJ-45 (8P8C) is the standard modular connector for UTP/STP Ethernet; LC/SC are fiber and BNC is coax.",
  },
  {
    q: "Which is a small-form-factor fiber connector often used in duplex pairs?",
    options: ["ST", "SC", "LC", "F-type"],
    answer: 2,
    explain: "LC (Lucent Connector) is a compact fiber connector, common in high-density equipment, frequently duplexed.",
  },
  {
    q: "What causes attenuation in a cable?",
    options: [
      "Adjacent pair interference",
      "Signal weakening as it travels over distance",
      "A grounding loop",
      "Excess connectors only",
    ],
    answer: 1,
    explain: "Attenuation is the loss of signal strength over distance; exceeding length limits makes the signal too weak to use.",
  },
  {
    q: "NEXT (near-end crosstalk) measures...",
    options: [
      "Fiber bend loss",
      "Interference coupled from one pair into another near the transmitter",
      "Total DC resistance",
      "PoE wattage",
    ],
    answer: 1,
    explain: "NEXT quantifies how much signal from one pair bleeds into an adjacent pair near the source — a key certification metric.",
  },
  {
    q: "Which medium is immune to electromagnetic interference?",
    options: ["UTP", "STP", "Coax", "Fiber optic"],
    answer: 3,
    explain: "Fiber carries light, not electricity, so it is unaffected by EMI/RFI — ideal for noisy or long-distance runs.",
  },
  {
    q: "Single-mode fiber is characterized by...",
    options: [
      "A large core and LED source, short distance",
      "A small (~9 µm) core and laser source, long distance",
      "Copper conductors",
      "No connectors",
    ],
    answer: 1,
    explain: "SMF has a ~9 µm core with laser light for long-haul, high-bandwidth links; MMF has a larger core and LED/VCSEL for shorter runs.",
  },
  {
    q: "Multimode fiber core diameters are typically...",
    options: ["9 µm", "50 or 62.5 µm", "1 mm", "0.1 µm"],
    answer: 1,
    explain: "MMF uses 50 or 62.5 µm cores, allowing multiple light paths (modes) suited to shorter distances.",
  },
  {
    q: "Which standard delivers 10 Gbps over multimode fiber (short reach)?",
    options: ["10GBASE-T", "10GBASE-SR", "10GBASE-LR", "1000BASE-T"],
    answer: 1,
    explain: "10GBASE-SR ('short reach') runs 10 Gbps over MMF for up to a few hundred meters; 10GBASE-LR uses SMF for long reach.",
  },
  {
    q: "Which standard delivers 10 Gbps over single-mode fiber for long distances?",
    options: ["10GBASE-SR", "10GBASE-LR", "100BASE-TX", "10BASE-T"],
    answer: 1,
    explain: "10GBASE-LR ('long reach') runs 10 Gbps over SMF up to ~10 km.",
  },
  {
    q: "In '1000BASE-T', what does 'BASE' signify?",
    options: [
      "Base station",
      "Baseband signaling (the medium carries a single digital signal)",
      "The basement wiring",
      "The base color",
    ],
    answer: 1,
    explain: "BASE = baseband: the entire medium bandwidth carries one digital signal (vs broadband, which multiplexes channels).",
  },
  {
    q: "Which transceiver form factor provides a 10 Gbps modular port?",
    options: ["SFP", "SFP+", "GBIC", "RJ-45"],
    answer: 1,
    explain: "SFP+ supports 10 Gbps; SFP is 1 Gbps and QSFP/QSFP+ handle 40 Gbps and above.",
  },
  {
    q: "A media converter is used to...",
    options: [
      "Change IP addresses",
      "Convert between media types such as copper and fiber",
      "Filter packets",
      "Assign VLANs",
    ],
    answer: 1,
    explain: "A media converter bridges different physical media — commonly copper Ethernet to fiber — to extend distance.",
  },
  {
    q: "Which IEEE standard defines the original PoE (~15.4 W at the source)?",
    options: ["802.3af", "802.3at", "802.3bt", "802.11ac"],
    answer: 0,
    explain: "802.3af (PoE) supplies up to 15.4 W; 802.3at (PoE+) ~30 W; 802.3bt (PoE++) up to 60–100 W.",
  },
  {
    q: "PoE+ (802.3at) provides approximately how much power at the source?",
    options: ["15.4 W", "30 W", "60 W", "100 W"],
    answer: 1,
    explain: "802.3at (PoE+) supplies about 30 W at the source, enough for many APs, PTZ cameras, and larger IP phones.",
  },
  {
    q: "A cable tester's wiremap function detects...",
    options: [
      "CPU load",
      "Opens, shorts, and miswires (correct pin-to-pin mapping)",
      "IP conflicts",
      "VLAN mismatches",
    ],
    answer: 1,
    explain: "A wiremap tester verifies each conductor is correctly terminated, catching opens, shorts, and crossed/split pairs.",
  },
  {
    q: "Which tool locates a specific cable within a bundle?",
    options: ["OTDR", "Toner probe (tone generator + probe)", "Crimper", "Multimeter"],
    answer: 1,
    explain: "A tone generator injects an audible signal onto a wire; the probe detects it to identify the matching cable.",
  },
  {
    q: "Which tool locates faults/splices and measures loss on a fiber run?",
    options: ["Wiremap tester", "OTDR", "Punch-down tool", "Crimper"],
    answer: 1,
    explain: "An OTDR (Optical Time-Domain Reflectometer) characterizes fiber, locating breaks, splices, and bends and measuring loss.",
  },
  {
    q: "A dirty or damaged fiber end-face most directly causes...",
    options: [
      "A VLAN mismatch",
      "Higher insertion loss and link errors",
      "An IP conflict",
      "A DHCP failure",
    ],
    answer: 1,
    explain: "Contamination scatters light, increasing insertion loss and causing errors; fiber ends should be inspected and cleaned before mating.",
  },
  {
    q: "What is a cable's minimum bend radius?",
    options: [
      "Its maximum data rate",
      "The tightest bend allowed before signal loss or damage occurs",
      "The connector size",
      "The jacket color code",
    ],
    answer: 1,
    explain: "Bending tighter than the minimum bend radius (especially for fiber) causes light loss (macrobend) or physical damage.",
  },
  {
    q: "Auto-MDIX on a switch port...",
    options: [
      "Assigns VLANs",
      "Automatically adapts to straight-through or crossover cabling",
      "Provides PoE",
      "Encrypts the link",
    ],
    answer: 1,
    explain: "Auto-MDIX senses the cable type and swaps TX/RX pairs as needed, making crossover cables largely unnecessary.",
  },
  {
    q: "Which cable is used to connect a PC to a switch (unlike devices) without Auto-MDIX?",
    options: ["Crossover", "Straight-through", "Rollover", "Loopback"],
    answer: 1,
    explain: "Straight-through cables (same standard both ends) connect unlike devices like host-to-switch.",
  },
  {
    q: "A rollover cable is typically used to...",
    options: [
      "Connect two switches",
      "Connect to a device's console port for management",
      "Carry PoE",
      "Bridge fiber to copper",
    ],
    answer: 1,
    explain: "A rollover (console) cable connects a computer's serial/USB to a router or switch console port for out-of-band management.",
  },
  {
    q: "Coaxial cable with F-type connectors is most associated with...",
    options: ["Fiber backbones", "Cable TV/broadband (DOCSIS)", "PoE", "Wireless bridging"],
    answer: 1,
    explain: "Coax (e.g., RG-6) with F-type connectors carries cable TV and broadband Internet using the DOCSIS standard.",
  },
  {
    q: "Which best mitigates EMI on a copper run near heavy machinery?",
    options: [
      "Increase the cable length",
      "Use shielded cable (STP) or fiber and route away from noise",
      "Remove the twists",
      "Use a longer patch cord",
    ],
    answer: 1,
    explain: "STP shielding or fiber, plus routing away from motors/power lines, reduces or eliminates EMI-induced errors.",
  },
  {
    q: "Why are the pairs in twisted-pair cabling twisted?",
    options: [
      "To increase weight",
      "To cancel interference and reduce crosstalk (common-mode rejection)",
      "To allow PoE",
      "To change color",
    ],
    answer: 1,
    explain: "Twisting makes interference affect both wires equally so it cancels, cutting crosstalk and EMI susceptibility.",
  },
  {
    q: "Which cable rating is required in air-handling plenum spaces?",
    options: ["Riser (CMR)", "Plenum (CMP)", "General (CM)", "Outdoor"],
    answer: 1,
    explain: "Plenum (CMP) cable uses fire-resistant, low-smoke jacketing required where building air circulates.",
  },
  {
    q: "The maximum length of a horizontal copper Ethernet run is...",
    options: ["55 m", "100 m", "550 m", "1 km"],
    answer: 1,
    explain: "All twisted-pair Ethernet is limited to a 100 m channel; longer runs require fiber or intermediate switches.",
  },
  {
    q: "Which measurement characterizes total fiber signal loss end to end?",
    options: [
      "Wiremap",
      "Insertion loss (dB), via a light source/power meter",
      "PoE budget",
      "MAC table size",
    ],
    answer: 1,
    explain: "Fiber links are validated by measuring insertion loss in dB with a light source and power meter (and characterized with an OTDR).",
  },
  {
    q: "STP differs from UTP by adding...",
    options: [
      "A light source",
      "Metallic shielding to reduce EMI (requires proper grounding)",
      "More conductors",
      "Fiber strands",
    ],
    answer: 1,
    explain: "STP adds foil/braid shielding around pairs and/or the cable to fight EMI, at higher cost and stiffness; grounding is required.",
  },
  {
    q: "A patch (patch cord) cable typically uses which conductor type?",
    options: [
      "Solid-core for in-wall runs",
      "Stranded for flexibility over short distances",
      "Fiber only",
      "Coax only",
    ],
    answer: 1,
    explain: "Patch cords use flexible stranded conductors for short connections; solid-core is used for longer permanent in-wall runs.",
  },
  {
    q: "Which fiber connector uses a bayonet-style twist lock and is an older type?",
    options: ["LC", "ST", "MPO", "RJ-45"],
    answer: 1,
    explain: "ST ('stick and twist') is a bayonet-coupling fiber connector, older than the push-pull SC and small-form-factor LC.",
  },
  {
    q: "Which multi-fiber connector supports high-density parallel optics (e.g., 40/100G breakouts)?",
    options: ["LC", "SC", "MPO/MTP", "BNC"],
    answer: 2,
    explain: "MPO/MTP connectors terminate many fibers in one ferrule, used for high-density and parallel-optic links like 40G/100G.",
  },
  {
    q: "Which PoE standard (802.3bt) can deliver up to ~60–100 W?",
    options: ["PoE (af)", "PoE+ (at)", "PoE++ / 4PPoE (bt)", "USB-PD"],
    answer: 2,
    explain: "802.3bt (PoE++/4PPoE) delivers up to 60 W (Type 3) or ~100 W (Type 4), powering demanding devices like PTZ cameras and displays.",
  },
  {
    q: "A wiremap showing pins 1&2 swapped with 3&6 on a link intended to be straight-through indicates...",
    options: [
      "Correct termination",
      "A miswire that must be corrected",
      "Fiber loss",
      "A PoE fault",
    ],
    answer: 1,
    explain: "For a straight-through link, swapped pairs are a termination error and must be corrected for reliable operation.",
  },
  {
    q: "Which best explains why fiber is preferred for building-to-building backbones?",
    options: [
      "It is always cheaper",
      "Greater distance, higher bandwidth, and EMI immunity",
      "It powers devices",
      "It needs no connectors",
    ],
    answer: 1,
    explain: "Backbone runs exceed copper's 100 m and demand bandwidth; fiber's reach, capacity, and EMI immunity make it the right choice.",
  },
  {
    q: "Which cabling problem is characterized by a split pair?",
    options: [
      "Two wires from different pairs used together, causing crosstalk despite continuity",
      "A short between two pins",
      "An open circuit",
      "Excess attenuation only",
    ],
    answer: 0,
    explain: "A split pair maintains end-to-end continuity but uses wires from different twisted pairs, defeating noise cancellation and causing crosstalk.",
  },
  {
    q: "100BASE-TX runs at what speed?",
    options: ["10 Mbps", "100 Mbps", "1 Gbps", "10 Gbps"],
    answer: 1,
    explain: "100BASE-TX ('Fast Ethernet') runs at 100 Mbps over Cat 5+ twisted pair to 100 m.",
  },
  {
    q: "Which is TRUE about plenum vs riser cable?",
    options: [
      "They are identical",
      "Plenum exceeds riser fire requirements and can substitute for riser, but not vice versa",
      "Riser is only for fiber",
      "Plenum is cheaper and less safe",
    ],
    answer: 1,
    explain: "Plenum-rated cable meets stricter fire/smoke requirements than riser, so it can replace riser where allowed, but riser cannot replace plenum.",
  },
  {
    q: "Which describes 'insertion loss'?",
    options: [
      "Signal reflected back to the source",
      "The reduction in signal power as it passes through a link/connector",
      "The number of connectors",
      "The cable's color",
    ],
    answer: 1,
    explain: "Insertion loss is the drop in signal power (in dB) across a component or link; lower is better for reliable transmission.",
  },
  {
    q: "Which describes 'return loss'?",
    options: [
      "Signal reflected back toward the source (higher is better)",
      "Total attenuation",
      "Crosstalk between pairs",
      "PoE wattage",
    ],
    answer: 0,
    explain: "Return loss measures reflected signal; a higher return-loss value means less reflection and a cleaner link.",
  },
  {
    q: "A technician needs 40 Gbps between two data-center switches. Which transceiver form factor fits?",
    options: ["SFP", "SFP+", "QSFP+", "RJ-45"],
    answer: 2,
    explain: "QSFP+ (Quad SFP) supports 40 Gbps (4 × 10G lanes); SFP is 1G and SFP+ is 10G.",
  },
  {
    q: "Which environmental factor most degrades copper but not fiber?",
    options: ["Temperature", "Electromagnetic interference (EMI)", "Humidity only", "Light"],
    answer: 1,
    explain: "EMI/RFI induces errors on electrical (copper) signals; fiber's optical signals are immune to it.",
  },
  {
    q: "What is the primary role of a fiber ferrule?",
    options: [
      "To power the fiber",
      "To precisely align the fiber core so two ends mate with minimal loss",
      "To convert light to electricity",
      "To store data",
    ],
    answer: 1,
    explain: "The ferrule holds and aligns the fiber end so mating connectors meet core-to-core with minimal insertion loss.",
  },
  {
    q: "Which best describes an SFP module's advantage?",
    options: [
      "It is soldered permanently",
      "It is hot-swappable, letting one switch port support different media/speeds",
      "It replaces the switch",
      "It provides Wi-Fi",
    ],
    answer: 1,
    explain: "SFP/SFP+ modules are hot-swappable, so a single cage can be fitted with copper, SX/LX fiber, etc., as needs change.",
  },
  {
    q: "A link keeps flapping (up/down) with rising CRC errors on copper. Which is the LEAST likely cause?",
    options: [
      "Damaged/marginal cable or connector",
      "EMI near the run",
      "Exceeding the 100 m limit",
      "An incorrect DNS record",
    ],
    answer: 3,
    explain: "CRC errors and flapping point to physical-layer issues (bad cable, EMI, length). DNS is unrelated to Layer 1 errors.",
  },
  {
    q: "Which fiber type would you choose for a 20 km inter-city link?",
    options: ["Cat 6a", "Multimode fiber", "Single-mode fiber", "Coax"],
    answer: 2,
    explain: "Single-mode fiber supports very long distances (tens of km); MMF and copper are far too limited.",
  },
  {
    q: "The color-coded jacket of a cable primarily helps with...",
    options: [
      "Increasing speed",
      "Organization/identification (e.g., voice vs data vs crossover)",
      "Encryption",
      "PoE delivery",
    ],
    answer: 1,
    explain: "Jacket colors are an organizational convention to distinguish cable purposes; they do not affect performance.",
  }
);
