// ── Module 09 — Network Risk Management · expansion pool ────────────────────
QUESTIONS["09"].push(
  {
    q: "Which part of the CIA triad ensures data is not altered without authorization?",
    options: ["Confidentiality", "Integrity", "Availability", "Accounting"],
    answer: 1,
    explain: "Integrity ensures accuracy and prevents unauthorized modification, protected by hashing and digital signatures.",
  },
  {
    q: "Which part of the CIA triad ensures systems are accessible when needed?",
    options: ["Confidentiality", "Integrity", "Availability", "Authentication"],
    answer: 2,
    explain: "Availability keeps services accessible, protected by redundancy, backups, and DDoS mitigation.",
  },
  {
    q: "A DDoS differs from a DoS in that a DDoS...",
    options: [
      "Is always encrypted",
      "Uses many distributed sources (often a botnet)",
      "Targets only DNS",
      "Is harmless",
    ],
    answer: 1,
    explain: "A Distributed DoS comes from many coordinated sources (a botnet), making it far harder to block and more powerful.",
  },
  {
    q: "ARP poisoning enables an attacker to...",
    options: [
      "Assign IP addresses",
      "Associate their MAC with another host's IP to intercept LAN traffic (MITM)",
      "Break WPA3",
      "Summarize routes",
    ],
    answer: 1,
    explain: "By sending forged ARP replies, an attacker maps a victim's/gateway's IP to their MAC, redirecting traffic through them. DAI mitigates it.",
  },
  {
    q: "Which attack forges the source address to impersonate a trusted host?",
    options: ["Spoofing", "Phishing", "Fuzzing", "Tailgating"],
    answer: 0,
    explain: "Spoofing falsifies identifying information (IP, MAC, email) to impersonate a trusted source or hide the attacker.",
  },
  {
    q: "Spear phishing differs from phishing in that it...",
    options: [
      "Targets a broad audience",
      "Targets a specific individual or organization with tailored content",
      "Uses only phone calls",
      "Is not social engineering",
    ],
    answer: 1,
    explain: "Spear phishing is a targeted phishing attack customized to a specific victim, increasing its success rate.",
  },
  {
    q: "Which is a physical/social-engineering attack where someone follows an authorized person through a secure door?",
    options: ["Tailgating", "Smurfing", "Fuzzing", "Spoofing"],
    answer: 0,
    explain: "Tailgating (piggybacking) is following an authorized person into a secure area; mantraps and awareness training help prevent it.",
  },
  {
    q: "Ransomware primarily harms which security goal first?",
    options: ["Confidentiality only", "Availability (often also confidentiality)", "Nothing", "Only integrity"],
    answer: 1,
    explain: "Ransomware encrypts data (denying availability) and increasingly exfiltrates it too. Offline/immutable backups are the key defense.",
  },
  {
    q: "A worm differs from a virus because a worm...",
    options: [
      "Needs a host file and user action",
      "Self-replicates across networks without user interaction",
      "Cannot spread",
      "Only affects printers",
    ],
    answer: 1,
    explain: "A worm self-propagates over the network by exploiting vulnerabilities, needing no host file or user action.",
  },
  {
    q: "A Trojan is characterized by...",
    options: [
      "Self-replication",
      "Disguising itself as legitimate software the user runs",
      "Encrypting the disk automatically",
      "Being harmless",
    ],
    answer: 1,
    explain: "A Trojan masquerades as useful software but carries a malicious payload; it relies on the user to execute it.",
  },
  {
    q: "A rootkit is dangerous because it...",
    options: [
      "Is easy to detect",
      "Hides deep in the OS to conceal malicious activity and maintain persistence",
      "Only affects Wi-Fi",
      "Improves performance",
    ],
    answer: 1,
    explain: "A rootkit embeds itself at a low level (kernel/boot) to hide malware and persist, making detection and removal difficult.",
  },
  {
    q: "A logic bomb executes when...",
    options: [
      "The system boots normally",
      "A specific condition or date is met",
      "The user logs out",
      "Never",
    ],
    answer: 1,
    explain: "A logic bomb lies dormant until a trigger condition (a date, event, or absence of a user) activates its payload.",
  },
  {
    q: "A zero-day vulnerability is one that...",
    options: [
      "Was patched years ago",
      "Is exploited before the vendor has a patch available",
      "Affects zero users",
      "Is a false positive",
    ],
    answer: 1,
    explain: "A zero-day is exploited before a fix exists (defenders have had 'zero days'), making it especially dangerous.",
  },
  {
    q: "The purpose of a vulnerability scan is to...",
    options: [
      "Exploit systems for profit",
      "Identify known weaknesses/misconfigurations for remediation",
      "Encrypt the network",
      "Assign IP addresses",
    ],
    answer: 1,
    explain: "A vulnerability scan checks systems against known issues and produces a prioritized remediation list — it does not exploit them.",
  },
  {
    q: "A penetration test goes beyond a scan by...",
    options: [
      "Only reading documentation",
      "Actively exploiting weaknesses (with authorization) to demonstrate real impact",
      "Encrypting logs",
      "Assigning VLANs",
    ],
    answer: 1,
    explain: "A pen test exploits vulnerabilities to show real-world impact and chained attacks, going further than a scan's reporting.",
  },
  {
    q: "CVSS provides...",
    options: [
      "A unique ID for each vulnerability",
      "A severity score (0–10) based on exploitability and impact",
      "An encryption key",
      "A routing metric",
    ],
    answer: 1,
    explain: "CVSS (Common Vulnerability Scoring System) rates severity to help prioritize remediation; CVE provides the unique identifier.",
  },
  {
    q: "The principle of least privilege means...",
    options: [
      "Everyone is an admin",
      "Users/processes get only the minimum access needed",
      "No one has access",
      "Access is permanent",
    ],
    answer: 1,
    explain: "Least privilege limits rights to the minimum required, shrinking the attack surface and containing compromise.",
  },
  {
    q: "Separation of duties helps prevent...",
    options: [
      "Faster approvals",
      "Fraud/errors by splitting critical tasks among multiple people",
      "Backups",
      "Encryption",
    ],
    answer: 1,
    explain: "Separation of duties ensures no single person can complete a sensitive process alone (e.g., request vs approve), reducing fraud.",
  },
  {
    q: "Defense in depth means...",
    options: [
      "One strong firewall",
      "Layering multiple diverse controls so one failure isn't catastrophic",
      "Disabling logging",
      "Using one password",
    ],
    answer: 1,
    explain: "Defense in depth layers physical, network, host, app, and data controls so a single control's failure doesn't expose the asset.",
  },
  {
    q: "MFA strengthens authentication by requiring...",
    options: [
      "One password",
      "Two or more independent factors (know/have/are)",
      "No password",
      "A longer username",
    ],
    answer: 1,
    explain: "MFA combines factors so a stolen password alone is insufficient, greatly reducing account-takeover risk.",
  },
  {
    q: "RTO defines...",
    options: [
      "Maximum acceptable data loss",
      "Target time to restore a service after an outage",
      "Hardware cost",
      "The number of users",
    ],
    answer: 1,
    explain: "Recovery Time Objective is how quickly a service must be restored after disruption.",
  },
  {
    q: "RPO defines...",
    options: [
      "How fast to recover",
      "The maximum acceptable amount of data loss, measured in time",
      "The firewall count",
      "The encryption strength",
    ],
    answer: 1,
    explain: "Recovery Point Objective sets how much data (in time) you can lose — driving backup/replication frequency.",
  },
  {
    q: "The 3-2-1 backup rule recommends...",
    options: [
      "3 passwords, 2 admins, 1 firewall",
      "3 copies, on 2 media types, with 1 offsite",
      "3 VLANs, 2 subnets, 1 router",
      "3 backups per day",
    ],
    answer: 1,
    explain: "3-2-1: keep 3 copies on 2 media with 1 offsite (ideally offline/immutable) — resilient against failure, disaster, and ransomware.",
  },
  {
    q: "A honeypot is deployed to...",
    options: [
      "Serve production traffic",
      "Lure and study attackers with a decoy while detecting intrusions",
      "Store customer data",
      "Provide DHCP",
    ],
    answer: 1,
    explain: "A honeypot is a decoy that attracts attackers, diverting them from real assets and generating early-warning intelligence.",
  },
  {
    q: "A brute-force attack attempts to...",
    options: [
      "Physically break a server",
      "Systematically try many passwords/keys until one works",
      "Flood a link",
      "Redirect DNS",
    ],
    answer: 1,
    explain: "Brute-force tries many combinations to guess credentials; lockouts, rate limiting, strong passwords, and MFA mitigate it.",
  },
  {
    q: "Timely patch management reduces risk mainly by...",
    options: [
      "Adding vulnerabilities",
      "Closing known vulnerabilities before they're exploited",
      "Increasing bandwidth",
      "Disabling MFA",
    ],
    answer: 1,
    explain: "Patching remediates known flaws, removing the low-hanging fruit that most attacks and worms rely on.",
  },
  {
    q: "Buying cyber-insurance is an example of which risk response?",
    options: ["Avoidance", "Acceptance", "Transference", "Mitigation"],
    answer: 2,
    explain: "Risk transference shifts financial impact to a third party (insurer); it doesn't reduce likelihood, only who bears the cost.",
  },
  {
    q: "Discontinuing a risky service entirely is which risk response?",
    options: ["Acceptance", "Avoidance", "Transference", "Mitigation"],
    answer: 1,
    explain: "Risk avoidance eliminates the risk by not performing the activity that causes it.",
  },
  {
    q: "An incident response plan defines...",
    options: [
      "Cable colors",
      "Roles, steps (prepare, identify, contain, eradicate, recover, learn), and communications for incidents",
      "The subnet plan",
      "DNS records",
    ],
    answer: 1,
    explain: "An IR plan documents how to detect, contain, eradicate, recover from, and learn from security incidents.",
  },
  {
    q: "Which control BEST limits damage from a single compromised user account?",
    options: [
      "Giving every user admin rights",
      "Least privilege plus network segmentation",
      "Disabling backups",
      "Sharing passwords",
    ],
    answer: 1,
    explain: "Least privilege limits what the account can do and segmentation limits where it can reach, containing the blast radius.",
  },
  {
    q: "A security policy is important because it...",
    options: [
      "Replaces all technical controls",
      "Defines rules, roles, and expected behavior that controls and training enforce",
      "Configures the firewall automatically",
      "Slows the network",
    ],
    answer: 1,
    explain: "Policies establish the governance foundation — rules and responsibilities — that technical controls and awareness enforce.",
  },
  {
    q: "A DNS amplification attack is a form of...",
    options: [
      "Phishing",
      "DDoS that abuses open resolvers to flood a victim with large responses",
      "Malware installation",
      "Physical intrusion",
    ],
    answer: 1,
    explain: "DNS amplification spoofs the victim's address in small queries to open resolvers, which send large responses to the victim, overwhelming it.",
  },
  {
    q: "Which is an example of 'something you are' in authentication?",
    options: ["A password", "A smart card", "A fingerprint", "A PIN"],
    answer: 2,
    explain: "Biometrics (fingerprint, face, iris) are 'something you are.' Passwords/PINs are 'know'; cards/tokens are 'have.'",
  },
  {
    q: "Social-engineering awareness training most directly reduces the risk of...",
    options: [
      "Cable faults",
      "Phishing and pretexting attacks that target people",
      "Fiber attenuation",
      "IP conflicts",
    ],
    answer: 1,
    explain: "Because many breaches start by deceiving people, training users to recognize phishing/pretexting is a key human-layer control.",
  },
  {
    q: "Which best describes a 'threat actor'?",
    options: [
      "A software patch",
      "An individual or group that may exploit vulnerabilities (e.g., insider, criminal, nation-state)",
      "A firewall rule",
      "A backup job",
    ],
    answer: 1,
    explain: "A threat actor is the entity behind a threat — insiders, hacktivists, criminals, or nation-states with varying motives and capabilities.",
  },
  {
    q: "Which is a compensating control?",
    options: [
      "The primary control itself",
      "An alternative control used when the ideal control isn't feasible",
      "Removing all controls",
      "A marketing plan",
    ],
    answer: 1,
    explain: "A compensating control provides comparable protection when the preferred control can't be implemented (e.g., extra monitoring instead of a patch).",
  },
  {
    q: "Which describes 'data at rest' vs 'data in transit' protection?",
    options: [
      "Both use the same method only",
      "At rest = encrypt stored data; in transit = encrypt data moving over the network (TLS/IPsec)",
      "Neither can be encrypted",
      "Only at rest matters",
    ],
    answer: 1,
    explain: "Data at rest is encrypted on disk/storage; data in transit is encrypted on the wire with TLS/IPsec. Both are needed for confidentiality.",
  },
  {
    q: "A man-in-the-middle attacker positioned between two parties can...",
    options: [
      "Only view a firewall",
      "Intercept, read, and possibly alter the traffic",
      "Assign IP addresses",
      "Improve performance",
    ],
    answer: 1,
    explain: "An on-path (MITM) attacker relays traffic between parties, able to eavesdrop or tamper — mitigated by encryption and DAI.",
  },
  {
    q: "Which is an insider threat scenario?",
    options: [
      "An external botnet attack",
      "An employee misusing authorized access to steal or damage data",
      "A power outage",
      "A DNS typo",
    ],
    answer: 1,
    explain: "Insider threats involve people with legitimate access (employees, contractors) misusing it; least privilege and monitoring reduce the risk.",
  },
  {
    q: "The best defense against ransomware destroying recoverability is...",
    options: [
      "RAID only",
      "Offline/immutable, tested backups following 3-2-1",
      "A stronger Wi-Fi password",
      "Disabling logging",
    ],
    answer: 1,
    explain: "Only backups ransomware can't reach or alter (offline/immutable, 3-2-1, tested) guarantee recovery. RAID protects against drive failure, not encryption.",
  },
  {
    q: "Which describes 'risk = ...'?",
    options: [
      "Bandwidth × latency",
      "A function of the likelihood a threat exploits a vulnerability and the resulting impact",
      "Cost of hardware only",
      "Number of users",
    ],
    answer: 1,
    explain: "Risk combines likelihood (threat exploiting a vulnerability) and impact; controls reduce one or both.",
  },
  {
    q: "Why change default credentials on new devices?",
    options: [
      "They are faster",
      "Defaults are publicly known and heavily targeted by attackers",
      "It disables the device",
      "It removes encryption",
    ],
    answer: 1,
    explain: "Default usernames/passwords are documented publicly and among the first things attackers try; change them immediately.",
  },
  {
    q: "A 'false positive' in a vulnerability scan is...",
    options: [
      "A real vulnerability missed",
      "A reported issue that isn't actually a vulnerability",
      "A patched system",
      "An encrypted file",
    ],
    answer: 1,
    explain: "A false positive is a finding flagged as a vulnerability that isn't real; a false negative is a real vulnerability the scan missed.",
  },
  {
    q: "Which is the strongest reason to encrypt backups?",
    options: [
      "To speed restores",
      "To protect confidentiality if backup media is lost or stolen",
      "To reduce their size",
      "To avoid documentation",
    ],
    answer: 1,
    explain: "Encrypting backups protects the data if media (tapes, drives, cloud copies) is lost or stolen.",
  },
  {
    q: "A watering-hole attack targets victims by...",
    options: [
      "Flooding a link",
      "Compromising a website the target group is known to visit",
      "Guessing passwords",
      "Physical theft",
    ],
    answer: 1,
    explain: "A watering-hole attack infects a legitimate site frequented by the intended victims, waiting for them to visit and be compromised.",
  },
  {
    q: "Which is TRUE about security awareness as a control layer?",
    options: [
      "It is unnecessary if firewalls exist",
      "People are a common attack target, so training is a critical layer of defense",
      "It replaces technical controls",
      "It only applies to IT staff",
    ],
    answer: 1,
    explain: "Since many breaches exploit people, ongoing awareness training complements technical controls and applies to all staff.",
  }
);
