// ── Module 06 — Wireless Networking · expansion pool ────────────────────────
QUESTIONS["06"].push(
  {
    q: "Which 802.11 standard operates only in the 5 GHz band and is branded Wi-Fi 5?",
    options: ["802.11n", "802.11ac", "802.11g", "802.11b"],
    answer: 1,
    explain: "802.11ac (Wi-Fi 5) operates only at 5 GHz, using wide channels and MU-MIMO for high throughput.",
  },
  {
    q: "Which standard is branded Wi-Fi 6 and uses OFDMA for efficiency?",
    options: ["802.11ac", "802.11ax", "802.11n", "802.11a"],
    answer: 1,
    explain: "802.11ax (Wi-Fi 6/6E) improves efficiency in dense environments with OFDMA and enhanced MU-MIMO.",
  },
  {
    q: "Which band does Wi-Fi 6E add over Wi-Fi 6?",
    options: ["900 MHz", "2.4 GHz", "6 GHz", "60 GHz"],
    answer: 2,
    explain: "Wi-Fi 6E extends 802.11ax into the 6 GHz band, providing additional clean spectrum and wide channels.",
  },
  {
    q: "Which access method do Wi-Fi stations use to reduce collisions?",
    options: ["CSMA/CD", "CSMA/CA", "Token passing", "Polling"],
    answer: 1,
    explain: "Wi-Fi uses CSMA/CA (collision avoidance) with acknowledgments because collisions can't be reliably detected on air.",
  },
  {
    q: "The name that identifies a wireless network to clients is the...",
    options: ["BSSID", "SSID", "MAC", "VLAN ID"],
    answer: 1,
    explain: "The SSID (Service Set Identifier) is the human-readable network name; the BSSID is the AP's MAC address for a BSS.",
  },
  {
    q: "What identifies a specific access point within an ESS?",
    options: ["SSID", "BSSID (the AP's MAC)", "IP address", "Channel number"],
    answer: 1,
    explain: "The BSSID (the AP's radio MAC address) uniquely identifies a basic service set; multiple BSSIDs can share one SSID in an ESS.",
  },
  {
    q: "Which wireless security standard uses SAE and offers the strongest protection?",
    options: ["WEP", "WPA", "WPA2", "WPA3"],
    answer: 3,
    explain: "WPA3 replaces the WPA2 handshake with SAE (Simultaneous Authentication of Equals), resisting offline dictionary attacks.",
  },
  {
    q: "Which legacy protocol is broken and must never be used?",
    options: ["WPA2", "WPA3", "WEP", "802.1X"],
    answer: 2,
    explain: "WEP's weak RC4/IV design is trivially cracked; it is deprecated in favor of WPA2/WPA3.",
  },
  {
    q: "WPA2 uses which encryption cipher?",
    options: ["RC4", "AES-CCMP", "DES", "MD5"],
    answer: 1,
    explain: "WPA2 uses AES-based CCMP; the older TKIP/RC4 (from WPA) is weaker and deprecated.",
  },
  {
    q: "WPA2/WPA3-Enterprise authenticates users via...",
    options: [
      "A single shared passphrase",
      "802.1X with a RADIUS server (unique per-user credentials)",
      "MAC filtering only",
      "No authentication",
    ],
    answer: 1,
    explain: "Enterprise mode uses 802.1X/RADIUS so each user authenticates individually; Personal (PSK) uses one shared passphrase.",
  },
  {
    q: "In 802.1X, what role does the access point play?",
    options: ["Supplicant", "Authenticator", "Authentication server", "Certificate authority"],
    answer: 1,
    explain: "The AP (or switch) is the authenticator, relaying credentials between the supplicant (client) and the RADIUS authentication server.",
  },
  {
    q: "Which non-overlapping channels are used in the 2.4 GHz band (North America)?",
    options: ["1, 2, 3", "1, 6, 11", "1, 5, 9", "3, 7, 11"],
    answer: 1,
    explain: "Channels 1, 6, and 11 are the standard non-overlapping 20 MHz channels in 2.4 GHz.",
  },
  {
    q: "Compared to 5 GHz, the 2.4 GHz band generally offers...",
    options: [
      "Higher speed and more channels",
      "Longer range and better wall penetration but more congestion",
      "No interference",
      "Immunity to obstacles",
    ],
    answer: 1,
    explain: "2.4 GHz travels farther and penetrates walls better but is crowded (few channels, many interferers), reducing reliability.",
  },
  {
    q: "Which technology uses multiple antennas/spatial streams to boost throughput?",
    options: ["MIMO", "NAT", "STP", "PoE"],
    answer: 0,
    explain: "MIMO (Multiple Input Multiple Output) uses multiple antennas and spatial streams for higher data rates and resilience.",
  },
  {
    q: "MU-MIMO improves performance by...",
    options: [
      "Serving multiple clients simultaneously",
      "Encrypting frames twice",
      "Disabling other radios",
      "Reducing channels",
    ],
    answer: 0,
    explain: "Multi-User MIMO lets an AP transmit to several clients at once using separate spatial streams, improving multi-client efficiency.",
  },
  {
    q: "OFDMA (introduced in Wi-Fi 6) improves efficiency by...",
    options: [
      "Dividing a channel into resource units to serve many clients in one transmission",
      "Doubling the SSID count",
      "Encrypting traffic",
      "Disabling MIMO",
    ],
    answer: 0,
    explain: "OFDMA subdivides a channel into resource units, letting the AP serve multiple clients simultaneously — great for dense environments.",
  },
  {
    q: "A directional antenna (e.g., Yagi) is best used to...",
    options: [
      "Provide equal coverage in all directions",
      "Focus signal in one direction for point-to-point links or extended range",
      "Power the AP",
      "Encrypt traffic",
    ],
    answer: 1,
    explain: "Directional antennas concentrate RF energy in one direction, increasing range/gain for bridges; omni antennas radiate in all directions.",
  },
  {
    q: "A rogue AP impersonating a legitimate SSID to capture credentials is a(n)...",
    options: ["Evil twin", "Honeypot", "Jump box", "Bastion host"],
    answer: 0,
    explain: "An evil twin broadcasts a legitimate-looking SSID to lure clients for credential theft or man-in-the-middle attacks.",
  },
  {
    q: "Which is a common source of 2.4 GHz interference?",
    options: [
      "Fiber cables",
      "Microwave ovens, cordless phones, and Bluetooth",
      "Ethernet switches",
      "DNS servers",
    ],
    answer: 1,
    explain: "The crowded 2.4 GHz band is shared with microwaves, cordless phones, Bluetooth, and other devices that cause interference.",
  },
  {
    q: "A wireless site survey is performed to...",
    options: [
      "Assign IP addresses",
      "Map coverage, interference, and optimal AP placement/channels",
      "Configure DNS",
      "Set firewall rules",
    ],
    answer: 1,
    explain: "A site survey measures RF conditions to plan AP locations, channels, and power, producing a coverage heat map.",
  },
  {
    q: "A Wi-Fi heat map visualizes...",
    options: [
      "AP CPU temperature",
      "Signal strength/coverage across a physical area",
      "Firewall rules",
      "DHCP leases",
    ],
    answer: 1,
    explain: "A heat map overlays measured signal strength (and interference) on a floor plan, revealing coverage gaps.",
  },
  {
    q: "An ESS (Extended Service Set) enables...",
    options: [
      "A single isolated AP",
      "Multiple APs with the same SSID so clients can roam",
      "Wired-only networking",
      "Disabling encryption",
    ],
    answer: 1,
    explain: "An ESS links multiple BSSs under one SSID over a distribution system, allowing seamless roaming between APs.",
  },
  {
    q: "In infrastructure mode, clients communicate...",
    options: [
      "Directly peer-to-peer",
      "Through a central access point",
      "Only over fiber",
      "Using tokens",
    ],
    answer: 1,
    explain: "Infrastructure mode routes client traffic through an AP (the norm); ad hoc mode is direct device-to-device without an AP.",
  },
  {
    q: "Band steering encourages capable clients to...",
    options: [
      "Use the less congested 5 GHz band",
      "Disconnect",
      "Switch to wired",
      "Use WEP",
    ],
    answer: 0,
    explain: "Band steering nudges dual-band clients onto 5 GHz to relieve congestion on the crowded 2.4 GHz band.",
  },
  {
    q: "A captive portal is commonly used to...",
    options: [
      "Encrypt the whole LAN",
      "Require users to authenticate or accept terms via a web page before granting access",
      "Assign VLANs to switches",
      "Route between subnets",
    ],
    answer: 1,
    explain: "A captive portal intercepts a new client's web traffic and redirects to a login/terms page, common for guest Wi-Fi.",
  },
  {
    q: "A low SNR (signal-to-noise ratio) at a client causes...",
    options: [
      "Higher throughput",
      "Lower data rates, retransmissions, and possible drops",
      "No effect",
      "Automatic encryption",
    ],
    answer: 1,
    explain: "Low SNR means the signal is barely above noise, forcing lower modulation/data rates and more retransmissions.",
  },
  {
    q: "Channel bonding (40/80/160 MHz) affects Wi-Fi by...",
    options: [
      "Reducing speed",
      "Increasing per-link throughput but consuming more spectrum",
      "Disabling encryption",
      "Powering more APs",
    ],
    answer: 1,
    explain: "Wider bonded channels raise throughput but use more of the band; practical mainly in 5/6 GHz, harmful in crowded 2.4 GHz.",
  },
  {
    q: "A wireless LAN controller (WLC) primarily provides...",
    options: [
      "Per-AP manual configuration",
      "Centralized config, channel/power management, roaming, and monitoring for many APs",
      "Internet access",
      "DNS resolution",
    ],
    answer: 1,
    explain: "A WLC centrally manages thin APs — pushing configs, coordinating RF (RRM), enabling fast roaming, and unifying monitoring.",
  },
  {
    q: "Does hiding the SSID make a network secure?",
    options: [
      "Yes, it is as strong as encryption",
      "No, it is minor obscurity; the SSID is still discoverable",
      "Yes, it disables all attacks",
      "Only on 5 GHz",
    ],
    answer: 1,
    explain: "SSID hiding offers negligible security — the name appears in client probes and can be captured. Encryption (WPA2/WPA3) is the real control.",
  },
  {
    q: "A deauthentication attack does what?",
    options: [
      "Encrypts the AP",
      "Forces clients to disconnect from the AP",
      "Assigns rogue IPs",
      "Boosts signal",
    ],
    answer: 1,
    explain: "A deauth attack spoofs management frames to disconnect clients, enabling denial of service or evil-twin capture (mitigated by 802.11w).",
  },
  {
    q: "Which improvement does WPA3-Personal provide over WPA2-Personal?",
    options: [
      "Removes all encryption",
      "SAE handshake resisting offline password-guessing and adding forward secrecy",
      "Uses WEP keys",
      "Requires no password",
    ],
    answer: 1,
    explain: "WPA3-Personal's SAE (Dragonfly) resists offline dictionary attacks and provides forward secrecy even with weak passwords.",
  },
  {
    q: "802.11n (Wi-Fi 4) introduced which capabilities?",
    options: [
      "MIMO and dual-band (2.4 and 5 GHz) operation",
      "Operation only at 900 MHz",
      "Removal of encryption",
      "Single-antenna only",
    ],
    answer: 0,
    explain: "802.11n added MIMO, channel bonding, and dual-band operation, greatly increasing throughput over 802.11g/a.",
  },
  {
    q: "Which tool identifies which channels neighboring APs occupy so you can pick a clean one?",
    options: ["Wi-Fi/spectrum analyzer", "Cable certifier", "Punch-down tool", "OTDR"],
    answer: 0,
    explain: "A Wi-Fi or spectrum analyzer shows channel usage and interference, guiding channel selection.",
  },
  {
    q: "In a dense deployment, lowering AP transmit power (and adding APs) helps by...",
    options: [
      "Increasing coverage overlap",
      "Shrinking cells to reduce co-channel interference and raise capacity",
      "Disabling roaming",
      "Removing encryption",
    ],
    answer: 1,
    explain: "Smaller cells reduce co-channel interference and let more clients associate with nearer APs, improving overall capacity.",
  },
  {
    q: "A wireless bridge is used to...",
    options: [
      "Connect wireless clients to an AP",
      "Link two wired segments/buildings over a point-to-point RF link",
      "Assign VLANs",
      "Provide DHCP",
    ],
    answer: 1,
    explain: "A wireless bridge connects two wired networks over RF (often with directional antennas), effectively replacing a cable between sites.",
  },
  {
    q: "Beamforming improves wireless by...",
    options: [
      "Broadcasting equally in all directions",
      "Focusing the signal toward a specific client to improve range/throughput",
      "Encrypting frames",
      "Disabling MIMO",
    ],
    answer: 1,
    explain: "Beamforming shapes the transmit pattern toward a client, improving received signal strength and throughput.",
  },
  {
    q: "Which factor most reduces Wi-Fi signal as distance increases?",
    options: [
      "DNS latency",
      "Free-space path loss plus absorption/reflection by obstacles",
      "MAC address length",
      "VLAN tagging",
    ],
    answer: 1,
    explain: "RF weakens with distance (path loss) and is absorbed/reflected by walls and objects, which is why AP placement matters.",
  },
  {
    q: "EIRP describes...",
    options: [
      "The number of SSIDs",
      "The effective radiated power (transmitter power plus antenna gain)",
      "The channel width",
      "The encryption strength",
    ],
    answer: 1,
    explain: "EIRP (Effective Isotropic Radiated Power) combines transmit power and antenna gain, and is often limited by regulations.",
  },
  {
    q: "A BSS consists of...",
    options: [
      "Multiple APs on one SSID",
      "A single AP and its associated clients",
      "Two wired switches",
      "A VLAN trunk",
    ],
    answer: 1,
    explain: "A Basic Service Set is one AP plus its associated stations, identified by the BSSID (the AP's MAC).",
  },
  {
    q: "Which control best detects and contains unauthorized (rogue) APs over the air?",
    options: ["WIPS", "DHCP", "STP", "NTP"],
    answer: 0,
    explain: "A Wireless Intrusion Prevention System (WIPS) detects rogue/evil-twin APs and can contain them; wired 802.1X stops rogue APs plugged into ports.",
  },
  {
    q: "Which describes fast roaming (e.g., 802.11r)?",
    options: [
      "It slows down handoffs",
      "It speeds client handoff between APs in an ESS, reducing disruption for voice/video",
      "It disables encryption",
      "It merges VLANs",
    ],
    answer: 1,
    explain: "802.11r (Fast BSS Transition) accelerates re-authentication as a client roams between APs, keeping latency-sensitive sessions smooth.",
  },
  {
    q: "Which is TRUE about ad hoc mode?",
    options: [
      "It requires a WLC",
      "Devices connect directly without an access point",
      "It is the enterprise standard",
      "It only works at 6 GHz",
    ],
    answer: 1,
    explain: "Ad hoc (IBSS) mode connects devices directly peer-to-peer without an AP; it doesn't scale and is uncommon in business networks.",
  },
  {
    q: "Which frequency band offers the most non-overlapping channels for high-density Wi-Fi?",
    options: ["2.4 GHz", "5 GHz (and 6 GHz)", "900 MHz", "60 MHz"],
    answer: 1,
    explain: "5 GHz (and 6 GHz with Wi-Fi 6E) provide many non-overlapping channels, supporting more APs and wider channels than 2.4 GHz.",
  },
  {
    q: "A client shows strong signal (RSSI) but poor throughput in a busy area. The most likely cause is...",
    options: [
      "Low signal",
      "Channel congestion/co-channel interference (contention)",
      "A DNS error",
      "A bad cable",
    ],
    answer: 1,
    explain: "Strong signal but low throughput usually indicates congestion — many clients/APs contending for the same channel airtime.",
  },
  {
    q: "Which is the safest configuration for a guest wireless network?",
    options: [
      "Same VLAN as staff, open",
      "Separate VLAN, Internet-only, with client isolation and a captive portal",
      "WEP with a shared key",
      "No SSID and no encryption",
    ],
    answer: 1,
    explain: "Guests should be isolated on their own VLAN with Internet-only access, client isolation, and a captive portal to protect internal resources.",
  },
  {
    q: "Which management-frame protection standard mitigates deauth/disassociation attacks?",
    options: ["802.11w", "802.11n", "802.3af", "802.1Q"],
    answer: 0,
    explain: "802.11w (Protected Management Frames) protects management frames, reducing the impact of deauth/disassociation attacks.",
  },
  {
    q: "Which best describes co-channel vs adjacent-channel interference?",
    options: [
      "Co-channel: APs share the same channel (contend for airtime); adjacent: overlapping channels bleed noise",
      "They are identical",
      "Both only affect fiber",
      "Neither affects Wi-Fi",
    ],
    answer: 0,
    explain: "Co-channel APs contend for the same channel's airtime; adjacent-channel (overlapping) APs inject noise. Proper channel planning avoids both.",
  }
);
