// ── Module 08 — Subnets & VLANs · expansion pool ────────────────────────────
QUESTIONS["08"].push(
  {
    q: "How many usable hosts are in a /25 subnet?",
    options: ["128", "126", "254", "62"],
    answer: 1,
    explain: "/25 has 7 host bits: 2^7 = 128, minus 2 = 126 usable hosts.",
  },
  {
    q: "What is the subnet mask for a /25?",
    options: ["255.255.255.0", "255.255.255.128", "255.255.255.192", "255.255.255.224"],
    answer: 1,
    explain: "/25 = 25 network bits. The 4th octet is 10000000 = 128, so the mask is 255.255.255.128.",
  },
  {
    q: "How many /27 subnets can be created from a single /24?",
    options: ["4", "8", "16", "32"],
    answer: 1,
    explain: "From /24 to /27 borrows 3 bits: 2^3 = 8 subnets, each with 30 usable hosts.",
  },
  {
    q: "What is the block size of a /27 subnet?",
    options: ["8", "16", "32", "64"],
    answer: 2,
    explain: "/27 mask = 255.255.255.224; block size = 256 − 224 = 32. Subnets increment by 32 in the last octet.",
  },
  {
    q: "Which subnet does host 192.168.5.70/26 belong to?",
    options: ["192.168.5.0/26", "192.168.5.64/26", "192.168.5.32/26", "192.168.5.128/26"],
    answer: 1,
    explain: "/26 block size = 64: subnets .0, .64, .128, .192. 70 falls in the .64 subnet (range .64–.127).",
  },
  {
    q: "What is the broadcast address of 192.168.5.64/26?",
    options: ["192.168.5.63", "192.168.5.127", "192.168.5.128", "192.168.5.191"],
    answer: 1,
    explain: "Block size 64: the .64 subnet spans .64–.127, so its broadcast is 192.168.5.127.",
  },
  {
    q: "How many usable hosts does a /23 provide?",
    options: ["254", "510", "512", "1022"],
    answer: 1,
    explain: "/23 has 9 host bits: 2^9 = 512, minus 2 = 510 usable hosts (two /24s combined).",
  },
  {
    q: "Which prefix provides exactly 2 usable hosts, ideal for a router-to-router link?",
    options: ["/28", "/29", "/30", "/31"],
    answer: 2,
    explain: "/30 has 2 host bits: 4 addresses, minus 2 = 2 usable — perfect for a point-to-point link. (/31 uses both for P2P per RFC 3021.)",
  },
  {
    q: "The formula for usable hosts per subnet is...",
    options: ["2^n", "2^n − 2", "2^n + 2", "n^2"],
    answer: 1,
    explain: "With n host bits, total = 2^n; subtract 2 for the network ID and broadcast = 2^n − 2 usable.",
  },
  {
    q: "Borrowing s bits from the host portion creates how many subnets (classless)?",
    options: ["2^s", "2^s − 2", "s × 2", "2^s + 2"],
    answer: 0,
    explain: "Classless subnetting counts all 2^s subnets, including the all-zeros and all-ones subnets.",
  },
  {
    q: "What is the network ID of 10.10.10.100/28?",
    options: ["10.10.10.96", "10.10.10.80", "10.10.10.112", "10.10.10.100"],
    answer: 0,
    explain: "/28 block size = 16: subnets ...80, 96, 112. 100 falls in .96 (range .96–.111), so the network ID is 10.10.10.96.",
  },
  {
    q: "The mask 255.255.255.248 corresponds to which prefix?",
    options: ["/27", "/28", "/29", "/30"],
    answer: 2,
    explain: "248 = 11111000 (5 bits) in the last octet, so 24 + 5 = /29. Block size 8; 6 usable hosts.",
  },
  {
    q: "VLSM allows a network designer to...",
    options: [
      "Use one mask everywhere",
      "Use different mask lengths per subnet to fit varying host counts",
      "Avoid subnetting",
      "Remove broadcast addresses",
    ],
    answer: 1,
    explain: "Variable Length Subnet Masking sizes each subnet to its need (e.g., /30 links, /26 LANs), conserving address space.",
  },
  {
    q: "When designing with VLSM, you should allocate subnets in what order?",
    options: [
      "Smallest requirement first",
      "Largest host requirement first, then smaller",
      "Random order",
      "Only as /24s",
    ],
    answer: 1,
    explain: "Allocating the largest subnets first prevents fragmentation; smaller subnets are then carved from remaining space.",
  },
  {
    q: "Which four /24s can be summarized as 192.168.8.0/22?",
    options: [
      "192.168.8.0, .9.0, .10.0, .11.0",
      "192.168.0.0, .1.0, .2.0, .3.0",
      "192.168.8.0, .16.0, .24.0, .32.0",
      "192.168.4.0, .5.0, .6.0, .7.0",
    ],
    answer: 0,
    explain: "/22 covers 4 contiguous /24s aligned on a multiple of 4: 192.168.8.0–192.168.11.255.",
  },
  {
    q: "Route summarization (supernetting) helps by...",
    options: [
      "Increasing the number of routes",
      "Combining contiguous networks into one advertised route, shrinking routing tables",
      "Encrypting routes",
      "Assigning VLANs",
    ],
    answer: 1,
    explain: "Summarization aggregates contiguous prefixes into one, reducing routing-table size and update overhead.",
  },
  {
    q: "What is a VLAN?",
    options: [
      "A physical cable",
      "A logical broadcast domain on switches, grouping ports regardless of physical location",
      "A routing protocol",
      "A firewall",
    ],
    answer: 1,
    explain: "A VLAN logically segments a switch into separate broadcast domains, grouping hosts by function rather than location.",
  },
  {
    q: "Which IEEE standard tags frames for VLANs on trunk links?",
    options: ["802.1Q", "802.3af", "802.11ac", "802.1X"],
    answer: 0,
    explain: "802.1Q inserts a 4-byte tag (with a 12-bit VLAN ID) so multiple VLANs traverse one trunk link.",
  },
  {
    q: "The usable VLAN ID range under 802.1Q is...",
    options: ["1–255", "1–1024", "1–4094", "1–65535"],
    answer: 2,
    explain: "The 12-bit VID field allows 0–4095; VLANs 1–4094 are usable (0 and 4095 are reserved).",
  },
  {
    q: "An access port carries traffic for...",
    options: [
      "All VLANs, tagged",
      "A single VLAN, untagged to the end device",
      "No VLANs",
      "Only the native VLAN's tags",
    ],
    answer: 1,
    explain: "An access port belongs to one VLAN and passes untagged frames to/from an end device (PC, printer).",
  },
  {
    q: "A trunk port is used to...",
    options: [
      "Connect a single PC",
      "Carry multiple VLANs between switches/routers using tags",
      "Disable VLANs",
      "Provide PoE",
    ],
    answer: 1,
    explain: "A trunk carries many VLANs over one link, tagging frames (802.1Q) so the far end can separate them.",
  },
  {
    q: "The native VLAN on an 802.1Q trunk carries frames that are...",
    options: ["Double-tagged", "Sent untagged", "Dropped", "Encrypted"],
    answer: 1,
    explain: "Native-VLAN frames traverse the trunk untagged. For security, change it from the default (VLAN 1) and match both ends.",
  },
  {
    q: "To allow devices on different VLANs to communicate, you need...",
    options: [
      "Only a hub",
      "Inter-VLAN routing (a router or Layer 3 switch)",
      "A longer cable",
      "To disable the VLANs",
    ],
    answer: 1,
    explain: "VLANs are separate Layer 3 networks; a router or Layer 3 switch must route between them.",
  },
  {
    q: "'Router-on-a-stick' uses...",
    options: [
      "One router interface with 802.1Q subinterfaces, one per VLAN, over a trunk",
      "A wireless router",
      "A router with no ports",
      "A router used as a hub",
    ],
    answer: 0,
    explain: "Router-on-a-stick splits one interface into subinterfaces (one per VLAN) connected to a switch trunk to route between VLANs.",
  },
  {
    q: "An SVI on a Layer 3 switch provides...",
    options: [
      "A physical port for a PC",
      "A virtual Layer 3 gateway interface for a VLAN",
      "MAC address assignment",
      "Trunk encryption",
    ],
    answer: 1,
    explain: "A Switched Virtual Interface is a virtual routed interface for a VLAN, giving it a gateway on a multilayer switch.",
  },
  {
    q: "By default, all ports on a new Cisco switch belong to which VLAN?",
    options: ["VLAN 0", "VLAN 1", "VLAN 99", "VLAN 4094"],
    answer: 1,
    explain: "VLAN 1 is the default for all ports; best practice moves user/management traffic off VLAN 1 for security.",
  },
  {
    q: "DHCP for a VLAN whose server is on another subnet requires...",
    options: [
      "A second server per VLAN always",
      "A DHCP relay (ip helper-address) on the router/L3 switch",
      "A trunk to every client",
      "Static addressing only",
    ],
    answer: 1,
    explain: "Because DHCP Discover is a broadcast confined to its VLAN, a relay forwards it as unicast to a central server on another subnet.",
  },
  {
    q: "A voice VLAN is used to...",
    options: [
      "Carry only DNS",
      "Separate IP-phone traffic so it can be prioritized (QoS) and secured apart from data",
      "Replace the native VLAN",
      "Disable trunking",
    ],
    answer: 1,
    explain: "A voice VLAN segregates VoIP traffic from PC data on the same port, enabling QoS and separate policy for voice.",
  },
  {
    q: "VLAN hopping is best mitigated by...",
    options: [
      "Enabling DTP on all ports",
      "Disabling DTP/auto-trunk, using a non-default native VLAN, and shutting unused ports",
      "Putting everything in VLAN 1",
      "Removing all trunks",
    ],
    answer: 1,
    explain: "Prevent VLAN hopping by disabling dynamic trunking, setting an unused native VLAN, hardcoding access/trunk, and disabling unused ports.",
  },
  {
    q: "Each subnet (or VLAN) is its own...",
    options: ["Collision domain only", "Broadcast domain", "MAC address", "Cable"],
    answer: 1,
    explain: "Subnetting/VLANs create separate broadcast domains, containing broadcasts and improving performance and security.",
  },
  {
    q: "How many /64 subnets can be made from an IPv6 /56 allocation?",
    options: ["64", "128", "256", "1024"],
    answer: 2,
    explain: "From /56 to /64 gives 8 subnet bits: 2^8 = 256 possible /64 subnets.",
  },
  {
    q: "What is the standard subnet size for a single IPv6 LAN?",
    options: ["/48", "/56", "/64", "/128"],
    answer: 2,
    explain: "IPv6 LANs use /64: the first 64 bits are the network prefix and the last 64 the interface ID (needed for SLAAC/EUI-64).",
  },
  {
    q: "A Layer 3 switch differs from a Layer 2 switch by being able to...",
    options: [
      "Only forward frames",
      "Route between VLANs/subnets in hardware",
      "Not use VLANs",
      "Only connect to hubs",
    ],
    answer: 1,
    explain: "A Layer 3 (multilayer) switch adds IP routing to switching, forwarding between VLANs at wire speed via SVIs.",
  },
  {
    q: "Order these prefixes from most to fewest usable hosts: /26, /24, /30, /28.",
    options: [
      "/24, /26, /28, /30",
      "/30, /28, /26, /24",
      "/26, /24, /30, /28",
      "/28, /30, /24, /26",
    ],
    answer: 0,
    explain: "Fewer network bits = more hosts: /24 (254) > /26 (62) > /28 (14) > /30 (2).",
  },
  {
    q: "How many host bits are needed for at least 1000 hosts in a subnet?",
    options: ["9", "10", "11", "8"],
    answer: 1,
    explain: "2^10 − 2 = 1022 ≥ 1000, while 2^9 − 2 = 510 is too few. So 10 host bits (a /22).",
  },
  {
    q: "What is the valid host range of 172.16.20.32/28?",
    options: [
      "172.16.20.33 – 172.16.20.46",
      "172.16.20.32 – 172.16.20.47",
      "172.16.20.33 – 172.16.20.47",
      "172.16.20.32 – 172.16.20.46",
    ],
    answer: 0,
    explain: "/28 block size 16: subnet .32–.47, network .32, broadcast .47, so usable hosts are .33–.46.",
  },
  {
    q: "When a switch receives a frame for an unknown unicast MAC within a VLAN, it...",
    options: [
      "Drops it",
      "Floods it out all other ports in that VLAN only",
      "Sends it to every VLAN",
      "Routes it",
    ],
    answer: 1,
    explain: "Unknown-unicast frames are flooded only within the frame's VLAN (its broadcast domain), never crossing into other VLANs.",
  },
  {
    q: "The primary benefit of multiple VLANs over one flat network is...",
    options: [
      "More cabling",
      "Smaller broadcast domains and logical security separation between groups",
      "Slower switching",
      "Fewer IP addresses",
    ],
    answer: 1,
    explain: "VLANs shrink broadcast domains and separate groups (staff, guests, VoIP) for performance and security without rewiring.",
  },
  {
    q: "For 10.0.0.0/16 subnetted into /24s, how many subnets result?",
    options: ["128", "256", "512", "1024"],
    answer: 1,
    explain: "From /16 to /24 borrows 8 bits: 2^8 = 256 subnets, each a /24 (254 usable hosts).",
  },
  {
    q: "The mask 255.255.252.0 is which prefix, and how many usable hosts?",
    options: [
      "/22, 1022 hosts",
      "/21, 2046 hosts",
      "/23, 510 hosts",
      "/20, 4094 hosts",
    ],
    answer: 0,
    explain: "252 = 11111100 in the 3rd octet = /22. Host bits = 10 → 2^10 − 2 = 1022 usable.",
  },
  {
    q: "Which is NOT assignable to a host in a subnet?",
    options: [
      "The first usable address",
      "The network ID and the broadcast address",
      "Any middle address",
      "The default gateway",
    ],
    answer: 1,
    explain: "The network ID (all host bits 0) and broadcast (all host bits 1) are reserved; hosts use the addresses between them.",
  },
  {
    q: "CIDR notation /19 corresponds to which mask?",
    options: ["255.255.224.0", "255.255.240.0", "255.255.192.0", "255.255.248.0"],
    answer: 0,
    explain: "/19: the 3rd octet is 11100000 = 224, so the mask is 255.255.224.0 (block size 32 in the 3rd octet).",
  },
  {
    q: "STP BPDU Guard on an access port protects against...",
    options: [
      "A rogue switch injecting BPDUs",
      "DNS poisoning",
      "Wi-Fi deauth",
      "IP conflicts",
    ],
    answer: 0,
    explain: "BPDU Guard disables a PortFast access port that receives a BPDU, blocking an unauthorized switch from altering the spanning tree.",
  },
  {
    q: "Which describes 'private VLAN' isolation?",
    options: [
      "Merging all VLANs",
      "Subdividing a VLAN so ports can't talk to each other while sharing a subnet",
      "Removing VLAN tags",
      "Encrypting the trunk",
    ],
    answer: 1,
    explain: "Private VLANs subdivide a VLAN into isolated/community ports that share the subnet/gateway but restrict peer-to-peer traffic.",
  },
  {
    q: "A /30 point-to-point link uses which two usable addresses out of its four?",
    options: [
      "The network and broadcast",
      "The two middle addresses (e.g., .1 and .2 in a .0 block)",
      "All four",
      "Only one",
    ],
    answer: 1,
    explain: "In a /30 (block .0–.3), .0 is the network and .3 is broadcast, leaving .1 and .2 usable for the two router interfaces.",
  },
  {
    q: "Which is the correct network ID for 192.168.200.145/26?",
    options: ["192.168.200.128", "192.168.200.144", "192.168.200.160", "192.168.200.0"],
    answer: 0,
    explain: "/26 block size 64: subnets .0, .64, .128, .192. 145 falls in .128 (range .128–.191), so the network ID is 192.168.200.128.",
  },
  {
    q: "Which best describes why VLAN 1 should be avoided for user/management traffic?",
    options: [
      "It is faster",
      "It is the default and a common target for VLAN-hopping and misconfiguration",
      "It cannot carry data",
      "It is encrypted",
    ],
    answer: 1,
    explain: "Because VLAN 1 is the default (and the default native VLAN), it's a frequent attack target; move user/management traffic to other VLANs.",
  },
  {
    q: "Micro-segmentation places workloads in...",
    options: [
      "One large VLAN",
      "Fine-grained isolated segments with tight policy between them",
      "The same broadcast domain",
      "A single subnet with no rules",
    ],
    answer: 1,
    explain: "Micro-segmentation isolates workloads into small segments with strict inter-segment policy, limiting lateral movement.",
  },
  {
    q: "How many addresses (total, not usable) are in a /27?",
    options: ["16", "32", "64", "8"],
    answer: 1,
    explain: "/27 has 5 host bits: 2^5 = 32 total addresses (30 usable after removing network and broadcast).",
  }
);
