// ── Module 12 — Wide Area Networks · expansion pool ─────────────────────────
QUESTIONS["12"].push(
  {
    q: "A WAN differs from a LAN primarily in that a WAN...",
    options: [
      "Is always wireless",
      "Spans a large geographic area and is usually provided by a telco",
      "Cannot use IP",
      "Is faster than any LAN",
    ],
    answer: 1,
    explain: "WANs cross wide geographic distances and are typically owned/operated by service providers, unlike locally owned LANs.",
  },
  {
    q: "LANs and WANs mostly differ at which OSI layers?",
    options: ["Layers 1 and 2", "Layers 5 and 6", "Only Layer 7", "They never differ"],
    answer: 0,
    explain: "They differ at Layers 1–2 (media, access methods, framing) but share Layer 3+ protocols like IP and TCP/UDP.",
  },
  {
    q: "The 'last mile' refers to...",
    options: [
      "The core Internet backbone",
      "The connection from the provider's network to the customer premises",
      "A routing protocol",
      "A backup site",
    ],
    answer: 1,
    explain: "The last mile is the final link from the provider to the customer — often the most costly/constrained part of the circuit.",
  },
  {
    q: "MPLS forwards traffic based on...",
    options: [
      "Full IP lookups at every hop",
      "Labels, enabling fast, traffic-engineered paths and QoS",
      "MAC addresses only",
      "SSIDs",
    ],
    answer: 1,
    explain: "MPLS tags packets with labels so provider routers forward by label swap rather than full IP lookups, enabling QoS and traffic engineering.",
  },
  {
    q: "A T1 line provides approximately what bandwidth?",
    options: ["1.544 Mbps", "10 Mbps", "44.736 Mbps", "100 Mbps"],
    answer: 0,
    explain: "A T1 (DS1) delivers 1.544 Mbps over 24 channels; a T3 (DS3) provides ~44.736 Mbps.",
  },
  {
    q: "A CSU/DSU is used to...",
    options: [
      "Assign IP addresses",
      "Connect a router to a digital leased line (T1/T3), converting signaling",
      "Provide Wi-Fi",
      "Filter packets",
    ],
    answer: 1,
    explain: "A CSU/DSU terminates a digital circuit like a T1, converting between the router's signals and the WAN line's format.",
  },
  {
    q: "DSL delivers broadband over...",
    options: [
      "Cable TV coax",
      "Existing telephone (copper) lines",
      "Fiber only",
      "Cellular towers",
    ],
    answer: 1,
    explain: "DSL uses existing copper phone wiring; speed decreases as distance from the provider's DSLAM increases.",
  },
  {
    q: "Cable Internet uses which standard over coax/HFC infrastructure?",
    options: ["PPP", "DOCSIS", "SONET", "LTE"],
    answer: 1,
    explain: "Cable broadband rides the coax/hybrid-fiber-coax plant and uses DOCSIS, sharing bandwidth among neighborhood subscribers.",
  },
  {
    q: "Which last-mile technology typically offers the highest bandwidth and lowest latency?",
    options: ["Dial-up", "Satellite", "Fiber (FTTH/PON)", "ISDN"],
    answer: 2,
    explain: "Fiber to the home/premises offers very high bandwidth and low latency, outclassing DSL, cable, satellite, and legacy dial-up.",
  },
  {
    q: "Satellite Internet's main drawback vs terrestrial links is...",
    options: [
      "No coverage anywhere",
      "High latency (especially geostationary)",
      "It cannot carry IP",
      "It is always fastest",
    ],
    answer: 1,
    explain: "Geostationary satellites are ~36,000 km up, adding significant round-trip latency; LEO constellations reduce this but latency still matters.",
  },
  {
    q: "Which cellular generation offers much higher speed and lower latency, enabling fixed-wireless WAN?",
    options: ["2G", "3G", "5G", "1G"],
    answer: 2,
    explain: "5G provides far higher throughput and lower latency than 4G/LTE, supporting fixed-wireless access and IoT.",
  },
  {
    q: "Static routing is best suited for...",
    options: [
      "Large, frequently changing networks",
      "Small or stub networks with few, stable paths",
      "Every enterprise core",
      "Wireless only",
    ],
    answer: 1,
    explain: "Static routes are manual and don't adapt automatically; ideal for small/stub networks or a single default route.",
  },
  {
    q: "A key advantage of dynamic routing over static is that it...",
    options: [
      "Requires no CPU",
      "Automatically adapts to topology changes and shares route info",
      "Never fails",
      "Removes routers",
    ],
    answer: 1,
    explain: "Dynamic protocols exchange routes and reroute around failures automatically, scaling far better than manual static routing.",
  },
  {
    q: "Which routing protocol is a link-state IGP using cost (bandwidth)?",
    options: ["RIP", "OSPF", "BGP", "ARP"],
    answer: 1,
    explain: "OSPF builds a topology map and uses Dijkstra's algorithm with cost metrics for fast, scalable convergence within an organization.",
  },
  {
    q: "RIP's metric and hop limit are...",
    options: [
      "Bandwidth; unlimited",
      "Hop count; maximum 15 (16 = unreachable)",
      "Delay; no limit",
      "Cost; 255",
    ],
    answer: 1,
    explain: "RIP uses hop count and caps usable paths at 15 hops (16 = unreachable), limiting it to small networks.",
  },
  {
    q: "Which protocol exchanges routes between autonomous systems on the Internet?",
    options: ["OSPF", "RIP", "BGP", "EIGRP"],
    answer: 2,
    explain: "BGP is the path-vector protocol that exchanges reachability between autonomous systems, making global Internet routing possible.",
  },
  {
    q: "EIGRP's default metric is based mainly on...",
    options: [
      "Hop count only",
      "Bandwidth and delay (a composite metric)",
      "SSID strength",
      "MAC address",
    ],
    answer: 1,
    explain: "EIGRP (Cisco advanced distance-vector) uses a composite metric (default: bandwidth and delay) and converges quickly via DUAL.",
  },
  {
    q: "Administrative distance is used to...",
    options: [
      "Measure cable length",
      "Choose between routes from different sources (lower AD = more trusted)",
      "Encrypt routes",
      "Assign VLANs",
    ],
    answer: 1,
    explain: "When multiple protocols offer a route to the same destination, the router prefers the lowest administrative distance.",
  },
  {
    q: "Which has the lowest administrative distance?",
    options: ["OSPF (110)", "RIP (120)", "Static (1)", "EIGRP (90)"],
    answer: 2,
    explain: "A static route (AD 1) is more trusted than EIGRP (90), OSPF (110), or RIP (120); connected routes are 0.",
  },
  {
    q: "A default route (0.0.0.0/0) is used to...",
    options: [
      "Block all traffic",
      "Forward packets not matched by any other route (gateway of last resort)",
      "Assign IPs",
      "Encrypt traffic",
    ],
    answer: 1,
    explain: "The default route matches any destination not otherwise listed, sending it toward the ISP/Internet from a stub site.",
  },
  {
    q: "In a hub-and-spoke WAN topology...",
    options: [
      "Every site connects directly to every other",
      "Remote sites (spokes) connect through a central hub",
      "There is no central site",
      "Only wireless is used",
    ],
    answer: 1,
    explain: "Hub-and-spoke routes spoke traffic through a central hub — cost-effective but the hub is a SPOF and spoke-to-spoke takes two hops.",
  },
  {
    q: "A full-mesh WAN provides ___ at ___.",
    options: [
      "least redundancy; lowest cost",
      "maximum redundancy (direct links between all sites); highest cost",
      "no redundancy; high cost",
      "wireless only; low cost",
    ],
    answer: 1,
    explain: "Full mesh links every site to every other for maximum redundancy/optimal paths, but the number of links and cost grow rapidly.",
  },
  {
    q: "SD-WAN improves traditional WANs by...",
    options: [
      "Requiring a single MPLS circuit",
      "Centrally steering traffic across multiple transports by application policy",
      "Removing encryption",
      "Eliminating routers",
    ],
    answer: 1,
    explain: "SD-WAN uses software-defined control to combine and route across diverse links (MPLS, broadband, LTE) by policy and link quality.",
  },
  {
    q: "The demarcation point (demarc) is...",
    options: [
      "The core router",
      "Where provider responsibility ends and customer responsibility begins",
      "The DNS server",
      "A backup generator",
    ],
    answer: 1,
    explain: "The demarc marks the boundary between the provider's network and the customer premises — key for troubleshooting responsibility.",
  },
  {
    q: "Metro Ethernet provides WAN connectivity by...",
    options: [
      "Using dial-up modems",
      "Extending Ethernet across a provider metro network (E-Line, E-LAN)",
      "Requiring satellite",
      "Using token ring",
    ],
    answer: 1,
    explain: "Metro Ethernet delivers Ethernet-based services (point-to-point E-Line, multipoint E-LAN) across a provider's metro network.",
  },
  {
    q: "Frame Relay and ATM are examples of...",
    options: [
      "Modern preferred WAN technologies",
      "Legacy packet/cell-switched WAN technologies largely replaced by MPLS/Metro Ethernet",
      "Wireless standards",
      "Routing protocols",
    ],
    answer: 1,
    explain: "Frame Relay (variable frames) and ATM (fixed 53-byte cells) are now legacy, superseded by MPLS, Metro Ethernet, and IP VPNs.",
  },
  {
    q: "A leased line differs from shared broadband by providing...",
    options: [
      "Always slower speed",
      "Dedicated, guaranteed bandwidth between two points",
      "No data capability",
      "Wireless only",
    ],
    answer: 1,
    explain: "A leased line is a private, always-on circuit with guaranteed symmetric bandwidth and SLA-backed performance, unlike best-effort broadband.",
  },
  {
    q: "PPP on a WAN link provides...",
    options: [
      "Framing, authentication (PAP/CHAP), and multilink over point-to-point connections",
      "VLAN assignment",
      "DNS resolution",
      "Wi-Fi",
    ],
    answer: 0,
    explain: "PPP encapsulates traffic on point-to-point links, supporting authentication, error detection, and multilink (common on serial/DSL via PPPoE).",
  },
  {
    q: "Which PPP authentication method never sends the password in clear text?",
    options: ["PAP", "CHAP", "None", "Telnet"],
    answer: 1,
    explain: "CHAP uses a challenge-response hash so the password isn't transmitted and re-authenticates periodically; PAP sends credentials in plaintext.",
  },
  {
    q: "A site with one ISP and one link is...",
    options: ["Multihomed", "Single-homed", "Full mesh", "Anycast"],
    answer: 1,
    explain: "Single-homed means one ISP and one link — simple but no redundancy; multihoming uses multiple ISPs/links for resilience.",
  },
  {
    q: "Multihoming with two ISPs improves...",
    options: [
      "Nothing",
      "WAN redundancy and potentially load balancing/path optimization (often via BGP)",
      "Only Wi-Fi",
      "Cable length",
    ],
    answer: 1,
    explain: "Two ISPs (often with BGP) provide failover if one goes down and can balance/optimize traffic across both links.",
  },
  {
    q: "SONET/SDH is used for...",
    options: [
      "Wireless LANs",
      "High-speed synchronous optical transport over fiber in provider backbones",
      "Home Wi-Fi",
      "Assigning IPs",
    ],
    answer: 1,
    explain: "SONET (SDH internationally) defines synchronous optical transport with standardized OC-x rates and resilient ring topologies.",
  },
  {
    q: "A VPN over the public Internet can serve as a WAN by...",
    options: [
      "Providing an encrypted tunnel connecting sites at lower cost than a private circuit",
      "Removing encryption",
      "Guaranteeing zero latency",
      "Replacing routers",
    ],
    answer: 0,
    explain: "Site-to-site VPNs create secure tunnels over ordinary Internet links, delivering WAN connectivity far cheaper than dedicated circuits.",
  },
  {
    q: "IGP vs EGP: which protocol is an EGP?",
    options: ["OSPF", "EIGRP", "RIP", "BGP"],
    answer: 3,
    explain: "BGP is an EGP (exterior gateway protocol) used between autonomous systems; RIP/OSPF/EIGRP are IGPs used within an organization.",
  },
  {
    q: "Convergence in routing refers to...",
    options: [
      "Merging VLANs",
      "All routers reaching a consistent view of the topology after a change",
      "Encrypting routes",
      "Combining cables",
    ],
    answer: 1,
    explain: "Convergence is when all routers agree on the topology after a change; faster convergence (OSPF/EIGRP over RIP) means less disruption.",
  },
  {
    q: "A router's primary function in a WAN is to...",
    options: [
      "Forward frames within one LAN by MAC",
      "Forward packets between different networks using IP and choose paths",
      "Amplify Wi-Fi",
      "Assign MAC addresses",
    ],
    answer: 1,
    explain: "Routers operate at Layer 3, connecting separate networks and forwarding packets by destination IP — tying LANs into the WAN/Internet.",
  },
  {
    q: "Which factor should MOST influence WAN technology choice for a new branch?",
    options: [
      "Router color",
      "Required bandwidth, budget, availability at the site, latency needs, and SLA",
      "Employee birthdays",
      "Coffee machine brand",
    ],
    answer: 1,
    explain: "WAN selection balances throughput, cost, local availability, latency/reliability, and SLA guarantees.",
  },
  {
    q: "A floating static route is used to...",
    options: [
      "Be the primary route always",
      "Serve as a backup by having a higher administrative distance than the primary",
      "Encrypt traffic",
      "Assign VLANs",
    ],
    answer: 1,
    explain: "A floating static route has a higher AD, so it stays inactive until the preferred (dynamic or lower-AD) route fails, then takes over.",
  },
  {
    q: "Which describes a PON (Passive Optical Network)?",
    options: [
      "A copper backbone",
      "A fiber access network using passive splitters to serve multiple subscribers (e.g., FTTH)",
      "A wireless mesh",
      "A routing protocol",
    ],
    answer: 1,
    explain: "A PON uses unpowered optical splitters to share fiber among many subscribers, common in fiber-to-the-home deployments.",
  },
  {
    q: "Which is TRUE about a T3 line?",
    options: [
      "It is slower than a T1",
      "It provides ~44.7 Mbps (equivalent to 28 T1s)",
      "It is wireless",
      "It carries no data",
    ],
    answer: 1,
    explain: "A T3 (DS3) delivers about 44.736 Mbps — roughly 28 T1 circuits — for higher-capacity dedicated WAN links.",
  },
  {
    q: "Which routing protocol type builds a full topology map of the network?",
    options: [
      "Distance-vector (RIP)",
      "Link-state (OSPF)",
      "Static",
      "Default only",
    ],
    answer: 1,
    explain: "Link-state protocols (OSPF, IS-IS) build a complete map of the topology and compute shortest paths, converging quickly.",
  },
  {
    q: "Distance-vector protocols like RIP make routing decisions based on...",
    options: [
      "A full topology map",
      "Direction and distance (metric) advertised by neighbors ('routing by rumor')",
      "Encryption keys",
      "MAC addresses",
    ],
    answer: 1,
    explain: "Distance-vector protocols share their routing tables with neighbors and pick routes by metric/direction, without a full topology view.",
  },
  {
    q: "Which WAN option is best when a branch needs cheap redundancy alongside a primary MPLS link?",
    options: [
      "A second identical MPLS only",
      "SD-WAN combining MPLS with broadband/LTE for failover and load sharing",
      "Dial-up",
      "No redundancy",
    ],
    answer: 1,
    explain: "SD-WAN can add inexpensive broadband/LTE links for failover and load sharing, reducing reliance on costly MPLS.",
  },
  {
    q: "PPPoE is commonly used on which access technology?",
    options: ["Fiber backbone", "DSL", "Satellite only", "Token Ring"],
    answer: 1,
    explain: "PPPoE (PPP over Ethernet) is widely used on DSL to carry PPP sessions (authentication, addressing) over the Ethernet-based link.",
  },
  {
    q: "Which is a benefit of route summarization on a WAN router?",
    options: [
      "Larger routing tables",
      "Smaller routing tables and reduced update overhead",
      "More broadcasts",
      "Slower convergence always",
    ],
    answer: 1,
    explain: "Summarizing contiguous prefixes into one advertisement shrinks routing tables and reduces update churn across the WAN.",
  },
  {
    q: "Which best describes an autonomous system (AS)?",
    options: [
      "A single switch",
      "A collection of networks under one administrative/routing policy (identified by an AS number)",
      "A VLAN",
      "A DNS zone",
    ],
    answer: 1,
    explain: "An AS is a set of IP networks under a single administrative control/policy; BGP exchanges routes between ASes using AS numbers.",
  },
  {
    q: "Which technology would BEST connect 20 branch offices to HQ with centralized policy and mixed links?",
    options: ["A single dial-up modem", "SD-WAN", "One crossover cable", "A hub"],
    answer: 1,
    explain: "SD-WAN centrally manages many sites across mixed transports with policy-based routing — ideal for multi-branch WANs.",
  },
  {
    q: "Which is the correct order of typical last-mile options from lowest to highest latency?",
    options: [
      "Fiber, DSL, cable, geostationary satellite",
      "Geostationary satellite, dial-up, DSL, fiber",
      "Dial-up, satellite, DSL, fiber",
      "Fiber, cable, DSL, dial-up only",
    ],
    answer: 0,
    explain: "Fiber generally has the lowest latency, then DSL/cable, with geostationary satellite the highest due to the long signal path.",
  }
);
