// ── Module 12 — Wide Area Networks (35) ─────────────────────────────────────
QUESTIONS["12"] = [
  {
    q: "A WAN differs from a LAN primarily in that a WAN...",
    options: [
      "Is always wireless",
      "Spans a large geographic area and is usually provided by telcos/service providers",
      "Cannot use IP",
      "Is faster than any LAN",
    ],
    answer: 1,
    explain: "WANs connect networks across wide geographic distances and are typically owned/operated by service providers (telcos), whereas LANs are local and usually privately owned.",
  },
  {
    q: "LANs and WANs differ mostly at which OSI layers?",
    options: [
      "Layers 1 and 2 (physical/data link access methods)",
      "Layers 5 and 6",
      "Only Layer 7",
      "They never differ",
    ],
    answer: 0,
    explain: "LANs and WANs use different Layer 1/2 technologies (media, access methods, framing) but share the same Layer 3+ protocols (IP, TCP/UDP) above.",
  },
  {
    q: "Which device manages internetwork communication by forwarding packets between different networks?",
    options: ["Switch", "Router", "Hub", "Access point"],
    answer: 1,
    explain: "Routers operate at Layer 3, choosing paths and forwarding packets between separate networks — the core function that ties LANs into WANs and the Internet.",
  },
  {
    q: "The 'last mile' in WAN service refers to...",
    options: [
      "The core Internet backbone",
      "The connection from the provider's network to the customer premises",
      "A routing protocol",
      "A backup site",
    ],
    answer: 1,
    explain: "The last mile is the final link from the service provider's infrastructure to the customer's location — often the most costly/constrained part of the connection.",
  },
  {
    q: "MPLS forwards traffic based on...",
    options: [
      "Full routing lookups at every hop",
      "Labels assigned to packets, enabling fast, traffic-engineered paths",
      "MAC addresses only",
      "SSIDs",
    ],
    answer: 1,
    explain: "MPLS (Multiprotocol Label Switching) tags packets with labels so provider routers forward by label swap rather than full IP lookups — enabling QoS and traffic engineering across the WAN.",
  },
  {
    q: "A T1 line provides approximately what bandwidth?",
    options: ["1.544 Mbps", "10 Mbps", "44.736 Mbps", "100 Mbps"],
    answer: 0,
    explain: "A T1 (DS1) leased line delivers 1.544 Mbps over 24 channels. A T3 (DS3) provides ~44.736 Mbps. These are classic dedicated digital circuits.",
  },
  {
    q: "A CSU/DSU is used to...",
    options: [
      "Assign IP addresses",
      "Connect a router to a digital leased line (T1/T3), converting between the LAN and WAN signaling",
      "Provide Wi-Fi",
      "Filter packets",
    ],
    answer: 1,
    explain: "A CSU/DSU (Channel Service Unit/Data Service Unit) terminates a digital circuit like a T1, converting the router's signals to/from the format the WAN line requires.",
  },
  {
    q: "DSL delivers broadband over...",
    options: [
      "Cable TV coax",
      "Existing telephone (copper) lines",
      "Fiber only",
      "Cellular towers",
    ],
    answer: 1,
    explain: "DSL (Digital Subscriber Line) uses existing copper telephone wiring, with speed decreasing as distance from the provider's DSLAM increases. ADSL is asymmetric (faster down).",
  },
  {
    q: "Cable Internet delivers broadband over ___ and uses the ___ standard.",
    options: [
      "phone lines; PPP",
      "coaxial/HFC cable TV infrastructure; DOCSIS",
      "fiber; SONET",
      "cellular; LTE",
    ],
    answer: 1,
    explain: "Cable broadband rides the coax/hybrid-fiber-coax cable-TV plant and uses the DOCSIS standard, sharing bandwidth among neighborhood subscribers.",
  },
  {
    q: "Which WAN access technology typically offers the highest bandwidth and lowest latency to the premises?",
    options: ["Dial-up", "Satellite", "Fiber (e.g., FTTH/PON)", "ISDN"],
    answer: 2,
    explain: "Fiber to the home/premises (FTTH, via passive optical networks) offers very high bandwidth and low latency, outclassing DSL, cable, satellite, and legacy dial-up/ISDN.",
  },
  {
    q: "Satellite Internet's main drawback compared to terrestrial links is...",
    options: [
      "It has no coverage anywhere",
      "High latency (especially geostationary) due to long signal distance",
      "It cannot carry IP",
      "It is always the fastest",
    ],
    answer: 1,
    explain: "Geostationary satellites sit ~36,000 km up, adding significant round-trip latency. It provides coverage where terrestrial options don't, but latency hurts real-time apps. LEO constellations reduce this.",
  },
  {
    q: "Which cellular generation introduced dramatically higher speeds and lower latency, enabling advanced mobile broadband?",
    options: ["2G", "3G", "5G", "1G"],
    answer: 2,
    explain: "5G offers much higher throughput and lower latency than 4G/LTE, supporting fixed-wireless WAN access and IoT. 4G/LTE remains widely used for mobile broadband.",
  },
  {
    q: "Static routing is best suited for...",
    options: [
      "Large, frequently changing networks",
      "Small or stub networks with few, stable paths",
      "Every enterprise core",
      "Wireless only",
    ],
    answer: 1,
    explain: "Static routes are manually configured and don't adapt automatically — ideal for small/stub networks or a single default route, but unmanageable and non-adaptive at large scale.",
  },
  {
    q: "A key advantage of dynamic routing protocols over static routes is...",
    options: [
      "They require no CPU",
      "They automatically adapt to topology changes and share route information",
      "They never fail",
      "They eliminate the need for routers",
    ],
    answer: 1,
    explain: "Dynamic protocols (RIP, OSPF, EIGRP, BGP) exchange routes and recalculate around failures automatically — scaling far better than manual static routing in changing networks.",
  },
  {
    q: "Which routing protocol is a link-state IGP that uses cost (bandwidth) and converges quickly?",
    options: ["RIP", "OSPF", "BGP", "ARP"],
    answer: 1,
    explain: "OSPF (Open Shortest Path First) is a link-state interior gateway protocol that builds a topology map and uses Dijkstra's algorithm with cost metrics for fast, scalable convergence.",
  },
  {
    q: "RIP is a distance-vector protocol whose main metric and limitation are...",
    options: [
      "Bandwidth; unlimited hops",
      "Hop count; a maximum of 15 hops (16 = unreachable)",
      "Delay; no limit",
      "Cost; 255 hops",
    ],
    answer: 1,
    explain: "RIP uses hop count as its metric and caps usable paths at 15 hops (16 means unreachable), limiting it to small networks. It's simple but slow to converge and non-scalable.",
  },
  {
    q: "Which protocol is the routing protocol of the Internet, exchanging routes between autonomous systems?",
    options: ["OSPF", "RIP", "BGP", "EIGRP"],
    answer: 2,
    explain: "BGP (Border Gateway Protocol) is the path-vector protocol that exchanges routing/reachability information between autonomous systems, making the global Internet routing possible.",
  },
  {
    q: "In a hub-and-spoke WAN topology...",
    options: [
      "Every site connects directly to every other site",
      "Remote sites (spokes) connect through a central site (hub)",
      "There is no central site",
      "Only wireless is used",
    ],
    answer: 1,
    explain: "Hub-and-spoke routes all spoke traffic through a central hub — cost-effective and simple, but the hub is a single point of failure and spoke-to-spoke traffic makes two hops.",
  },
  {
    q: "A full-mesh WAN topology provides ___ but at ___.",
    options: [
      "least redundancy; lowest cost",
      "maximum redundancy (direct links between all sites); highest cost/complexity",
      "no redundancy; high cost",
      "wireless only; low cost",
    ],
    answer: 1,
    explain: "Full mesh links every site to every other site for maximum redundancy and optimal paths, but the number of links (and cost) grows rapidly with each added site.",
  },
  {
    q: "SD-WAN improves traditional WANs by...",
    options: [
      "Requiring a single MPLS circuit",
      "Centrally managing and dynamically steering traffic across multiple transports (MPLS, broadband, LTE) by policy",
      "Removing encryption",
      "Eliminating routers entirely",
    ],
    answer: 1,
    explain: "SD-WAN uses software-defined control to combine and intelligently route across diverse links based on application policy and link quality — improving performance and reducing reliance on costly MPLS.",
  },
  {
    q: "The demarcation point (demarc) in WAN service is...",
    options: [
      "The core router",
      "Where the provider's responsibility ends and the customer's begins",
      "The DNS server",
      "A backup generator",
    ],
    answer: 1,
    explain: "The demarc marks the boundary between the service provider's network and the customer premises equipment — important for troubleshooting responsibility.",
  },
  {
    q: "Metro Ethernet provides WAN connectivity by...",
    options: [
      "Using dial-up modems",
      "Extending familiar Ethernet across a metropolitan/provider network (e.g., E-Line, E-LAN)",
      "Requiring satellite links",
      "Using token ring",
    ],
    answer: 1,
    explain: "Metro Ethernet delivers Ethernet-based services (point-to-point E-Line, multipoint E-LAN) across a provider's metro network, offering scalable, familiar connectivity between sites.",
  },
  {
    q: "Frame Relay and ATM are examples of...",
    options: [
      "Modern preferred WAN technologies",
      "Legacy packet/cell-switched WAN technologies largely replaced by MPLS/Metro Ethernet",
      "Wireless standards",
      "Routing protocols",
    ],
    answer: 1,
    explain: "Frame Relay (variable frames) and ATM (fixed 53-byte cells) were widely used WAN technologies but are now largely legacy, superseded by MPLS, Metro Ethernet, and IP VPNs.",
  },
  {
    q: "A leased line (dedicated circuit) differs from a shared broadband link in that it...",
    options: [
      "Is always slower",
      "Provides dedicated, guaranteed bandwidth between two points",
      "Cannot carry data",
      "Is only wireless",
    ],
    answer: 1,
    explain: "A leased line offers a private, always-on circuit with guaranteed symmetric bandwidth and predictable performance (backed by SLAs), unlike best-effort shared broadband.",
  },
  {
    q: "Administrative distance is used by a router to...",
    options: [
      "Measure cable length",
      "Choose between routes learned from different sources (lower AD = more trusted)",
      "Encrypt routes",
      "Assign VLANs",
    ],
    answer: 1,
    explain: "When multiple protocols offer a route to the same destination, the router prefers the one with the lowest administrative distance (e.g., static 1, EIGRP 90, OSPF 110, RIP 120).",
  },
  {
    q: "A default route (0.0.0.0/0) is used to...",
    options: [
      "Block all traffic",
      "Forward packets whose destination isn't in the routing table (the gateway of last resort)",
      "Assign IPs",
      "Encrypt traffic",
    ],
    answer: 1,
    explain: "The default route matches any destination not otherwise listed, sending it to the 'gateway of last resort' — commonly the route toward the ISP/Internet from a stub site.",
  },
  {
    q: "Which metric does EIGRP primarily use by default?",
    options: [
      "Hop count only",
      "A composite metric based mainly on bandwidth and delay",
      "SSID strength",
      "MAC address",
    ],
    answer: 1,
    explain: "EIGRP (Cisco advanced distance-vector) uses a composite metric (by default bandwidth and delay) and converges quickly using its DUAL algorithm and feasible successors.",
  },
  {
    q: "PPP (Point-to-Point Protocol) is used on WAN links to...",
    options: [
      "Provide framing, authentication (PAP/CHAP), and multilink over serial/point-to-point connections",
      "Assign VLANs",
      "Resolve DNS",
      "Provide Wi-Fi",
    ],
    answer: 0,
    explain: "PPP encapsulates traffic on point-to-point WAN links, supporting authentication (PAP/CHAP), error detection, and multilink — historically common on serial and DSL (PPPoE) connections.",
  },
  {
    q: "Which authentication method for PPP is more secure because it never sends the password in clear text?",
    options: ["PAP", "CHAP", "None", "Telnet"],
    answer: 1,
    explain: "CHAP uses a challenge-response hash so the password isn't transmitted, and it re-authenticates periodically. PAP sends credentials in clear text and is insecure.",
  },
  {
    q: "A site connecting to the Internet through a single ISP with one link is called...",
    options: ["Multihomed", "Single-homed", "Full mesh", "Anycast"],
    answer: 1,
    explain: "Single-homed means one ISP and one link — simple but no redundancy. Multihoming uses multiple ISPs/links (often with BGP) for redundancy and load sharing.",
  },
  {
    q: "Multihoming with two ISPs improves...",
    options: [
      "Nothing",
      "WAN redundancy and potentially load balancing/path optimization",
      "Only Wi-Fi",
      "Cable length",
    ],
    answer: 1,
    explain: "Connecting to two ISPs (often via BGP) provides failover if one provider goes down and can balance/optimize outbound and inbound traffic across both links.",
  },
  {
    q: "SONET/SDH is a WAN technology used for...",
    options: [
      "Wireless LANs",
      "High-speed synchronous optical transport over fiber in provider/backbone networks",
      "Home Wi-Fi",
      "Assigning IPs",
    ],
    answer: 1,
    explain: "SONET (and SDH internationally) defines synchronous optical transport with standardized rates (OC-x) used in carrier fiber backbones, offering resilient ring topologies.",
  },
  {
    q: "A VPN over the public Internet can serve as a WAN by...",
    options: [
      "Providing an encrypted tunnel that connects sites at lower cost than a private circuit",
      "Removing the need for encryption",
      "Guaranteeing zero latency",
      "Replacing all routers",
    ],
    answer: 0,
    explain: "Site-to-site VPNs create secure tunnels over ordinary Internet links, delivering WAN connectivity between offices at far lower cost than dedicated circuits — though performance depends on the Internet.",
  },
  {
    q: "Which factor should MOST influence the choice of WAN technology for a new branch?",
    options: [
      "The color of the router",
      "Required bandwidth, budget, availability at the location, latency needs, and SLA",
      "The number of employees' birthdays",
      "The brand of coffee machine",
    ],
    answer: 1,
    explain: "WAN selection balances needed throughput, cost/budget, what's available at the site, latency/reliability requirements, and SLA guarantees — as emphasized for WAN service planning.",
  },
  {
    q: "Convergence in routing refers to...",
    options: [
      "Merging VLANs",
      "The process of all routers reaching a consistent view of the topology after a change",
      "Encrypting routes",
      "Combining cables",
    ],
    answer: 1,
    explain: "Convergence is when all routers have updated and agreed on the network topology after a change. Faster convergence (e.g., OSPF/EIGRP over RIP) means less disruption during failures.",
  },
];
