// ── Module 02 — Infrastructure & Documentation (30) ─────────────────────────
QUESTIONS["02"] = [
  {
    q: "Which standard defines structured cabling for commercial buildings?",
    options: ["IEEE 802.11", "ANSI/TIA-568", "RFC 1918", "IEEE 802.3af"],
    answer: 1,
    explain: "ANSI/TIA-568 is the Commercial Building Wiring Standard (structured cabling). It describes how to install media to maximize performance and assumes a hierarchical star topology.",
  },
  {
    q: "What is the MDF (Main Distribution Frame)?",
    options: [
      "A backup power supply",
      "The central point of a building's structured cabling where the main equipment and cross-connects live",
      "A type of fiber connector",
      "A firewall appliance",
    ],
    answer: 1,
    explain: "The MDF is the centralized point of interconnection for an organization's LAN/WAN — it houses the main routers, switches, and cross-connects. IDFs branch out from it.",
  },
  {
    q: "What is the role of an IDF (Intermediate Distribution Frame)?",
    options: [
      "It replaces the MDF entirely",
      "It is a smaller wiring closet that connects work-area cabling back to the MDF",
      "It is the ISP's demarcation point",
      "It stores backup tapes",
    ],
    answer: 1,
    explain: "An IDF is a remote/intermediate wiring closet (often per floor) that aggregates horizontal cabling from work areas and links back to the MDF via backbone cabling.",
  },
  {
    q: "The point where the ISP's responsibility ends and the customer's begins is called the...",
    options: ["Patch panel", "Demarcation point (demarc)", "MDF", "Rack unit"],
    answer: 1,
    explain: "The demarcation point (demarc) is where the service provider's network ends and the customer's premises wiring begins — the boundary of responsibility.",
  },
  {
    q: "What does a patch panel provide?",
    options: [
      "Wireless access to clients",
      "A termination point where horizontal cabling is punched down and connected to switches via patch cables",
      "Automatic IP addressing",
      "Malware scanning",
    ],
    answer: 1,
    explain: "A patch panel terminates permanent horizontal runs. Short patch cables then connect panel ports to switch ports, keeping cabling organized and easy to re-patch.",
  },
  {
    q: "Rack-mounted equipment height is measured in units abbreviated as...",
    options: ["dB", "U (rack units, 1U = 1.75 in)", "AWG", "MHz"],
    answer: 1,
    explain: "A rack unit (U or RU) equals 1.75 inches. A standard equipment rack is 42U tall. Devices are described as 1U, 2U, etc.",
  },
  {
    q: "Which wiring standard for terminating an RJ-45 jack is most common in the U.S. for new installs?",
    options: ["T568A", "T568B", "RS-232", "BNC"],
    answer: 1,
    explain: "T568A and T568B are the two pin/pair color schemes in TIA-568. T568B is widely used for new commercial installs in the U.S.; the key is to be consistent on both ends.",
  },
  {
    q: "A cable terminated with T568A on one end and T568B on the other creates a...",
    options: ["Straight-through cable", "Crossover cable", "Rollover cable", "Loopback cable"],
    answer: 1,
    explain: "Mixing T568A and T568B ends swaps the transmit/receive pairs, producing a crossover cable (historically used to connect like devices such as switch-to-switch).",
  },
  {
    q: "Why is a network diagram important documentation?",
    options: [
      "It replaces the need for any configuration",
      "It shows how devices connect and helps with troubleshooting, planning, and audits",
      "It automatically fixes outages",
      "It is only useful to the ISP",
    ],
    answer: 1,
    explain: "Network diagrams (physical and logical) document topology, addressing, and connections — essential for troubleshooting, capacity planning, onboarding, and audits.",
  },
  {
    q: "A wiring/labeling scheme's main purpose is to...",
    options: [
      "Increase bandwidth",
      "Make it fast and unambiguous to identify cables, ports, and equipment",
      "Encrypt traffic",
      "Assign IP addresses",
    ],
    answer: 1,
    explain: "Consistent labeling of cables, patch panels, jacks, and racks lets technicians trace connections quickly and reduces errors during changes and troubleshooting.",
  },
  {
    q: "What is the primary goal of a change-management process?",
    options: [
      "To stop all changes permanently",
      "To ensure changes are documented, reviewed, approved, and reversible to minimize risk",
      "To speed up changes by skipping approvals",
      "To hide changes from the team",
    ],
    answer: 1,
    explain: "Change management controls how changes are proposed, reviewed, approved, implemented, and documented — including rollback plans — to reduce the risk of outages.",
  },
  {
    q: "A rollback plan in change management is used to...",
    options: [
      "Permanently delete old configs",
      "Restore the previous working state if a change fails",
      "Upgrade firmware automatically",
      "Add new VLANs",
    ],
    answer: 1,
    explain: "A rollback (back-out) plan documents how to revert to the last known-good state if a change causes problems, limiting downtime.",
  },
  {
    q: "Horizontal cabling refers to the cabling that...",
    options: [
      "Connects buildings across a campus",
      "Runs from the telecommunications closet (IDF) to the work-area wall jacks",
      "Connects the ISP to the demarc",
      "Is used only for fiber backbones",
    ],
    answer: 1,
    explain: "Horizontal cabling connects the telecommunications room/IDF to the individual work-area outlets. TIA-568 limits horizontal copper runs to 100 meters total.",
  },
  {
    q: "Backbone (vertical) cabling connects...",
    options: [
      "A single PC to a wall jack",
      "MDF to IDFs and floor-to-floor / building-to-building runs",
      "A keyboard to a computer",
      "Two ports on the same switch",
    ],
    answer: 1,
    explain: "Backbone cabling interconnects MDF, IDFs, equipment rooms, and entrance facilities — the vertical/riser runs between floors and buildings, often fiber.",
  },
  {
    q: "What is the maximum recommended length for a horizontal copper (UTP) cable run under TIA-568?",
    options: ["55 meters", "100 meters", "500 meters", "1 kilometer"],
    answer: 1,
    explain: "The standard limits a horizontal channel to 100 m: up to 90 m of solid-core permanent link plus about 10 m of stranded patch cords at the ends.",
  },
  {
    q: "A 'baseline' in network documentation is...",
    options: [
      "The floor of a server rack",
      "A record of normal performance/metrics used to detect future deviations",
      "The lowest cable in a bundle",
      "The default gateway",
    ],
    answer: 1,
    explain: "A performance baseline captures normal traffic, utilization, and behavior so that anomalies (spikes, slowdowns, breaches) can be recognized by comparison later.",
  },
  {
    q: "An SLA (Service Level Agreement) primarily defines...",
    options: [
      "Cable color codes",
      "The agreed level of service, uptime, and response expectations between provider and customer",
      "The OSI layers",
      "How to crimp RJ-45 connectors",
    ],
    answer: 1,
    explain: "An SLA is a contract specifying measurable service expectations — such as uptime percentage, response/repair times, and penalties — between a provider and customer.",
  },
  {
    q: "Which document describes acceptable use of network resources by employees?",
    options: ["AUP (Acceptable Use Policy)", "MSDS", "MTBF", "SNMP"],
    answer: 0,
    explain: "An Acceptable Use Policy (AUP) defines how employees may use organizational network and computing resources, and the consequences of misuse.",
  },
  {
    q: "A 'logical network diagram' primarily shows...",
    options: [
      "The exact physical location of each cable",
      "IP addressing, VLANs, subnets, and how data flows logically",
      "The color of each patch cable",
      "Rack elevations only",
    ],
    answer: 1,
    explain: "A logical diagram depicts addressing, subnets/VLANs, routing, and logical data flow. A physical diagram shows the actual devices, ports, and cable runs.",
  },
  {
    q: "Cable management (ties, trays, labels) primarily improves...",
    options: [
      "Encryption strength",
      "Airflow, serviceability, and reduced accidental disconnects",
      "IP address availability",
      "Wireless coverage",
    ],
    answer: 1,
    explain: "Good cable management improves airflow/cooling, makes tracing and servicing cables easier, and reduces the chance of accidentally unplugging the wrong cable.",
  },
  {
    q: "An IDF connecting to the MDF over fiber typically does so because fiber...",
    options: [
      "Is cheaper than copper for short runs",
      "Supports longer distances and higher bandwidth than copper for backbone runs",
      "Requires no connectors",
      "Cannot be tapped",
    ],
    answer: 1,
    explain: "Backbone runs between MDF and IDFs often exceed copper's 100 m limit and demand high bandwidth, so fiber (with its long reach and capacity) is preferred.",
  },
  {
    q: "The 'entrance facility' in structured cabling is where...",
    options: [
      "Employees badge in",
      "External cabling (ISP/WAN) enters the building and meets the demarc",
      "The break room is located",
      "Wireless APs are stored",
    ],
    answer: 1,
    explain: "The entrance facility is the location where the service provider's cabling enters the building and connects to the internal structured cabling, often at the demarc.",
  },
  {
    q: "What is a 'punch-down' tool used for?",
    options: [
      "Crimping RJ-45 plugs",
      "Terminating wires into a 66/110 block or patch panel and trimming the excess",
      "Testing signal strength",
      "Splicing fiber",
    ],
    answer: 1,
    explain: "A punch-down tool seats individual conductors into insulation-displacement contacts on a 110/66 block or patch panel and can trim the excess wire in one motion.",
  },
  {
    q: "Which of the following would be recorded in an IP address management (IPAM) system?",
    options: [
      "The physical weight of a switch",
      "Assigned IP addresses, subnets, hostnames, and DHCP/DNS records",
      "Employee salaries",
      "Cable colors only",
    ],
    answer: 1,
    explain: "IPAM tracks address allocation — which IPs/subnets are assigned, reserved, or free — along with DNS/DHCP data, preventing conflicts and easing audits.",
  },
  {
    q: "MTBF (Mean Time Between Failures) is a metric that estimates...",
    options: [
      "How long to repair a device",
      "The average time a device operates before it fails",
      "Cable length",
      "Bandwidth in Mbps",
    ],
    answer: 1,
    explain: "MTBF estimates a component's average operational lifetime before failure — useful for reliability planning. MTTR (Mean Time To Repair) estimates repair time.",
  },
  {
    q: "Why maintain up-to-date documentation after every change?",
    options: [
      "It is legally forbidden to change documentation",
      "Stale documentation misleads troubleshooters and causes errors during future changes",
      "Documentation slows the network",
      "It only matters for wireless",
    ],
    answer: 1,
    explain: "Documentation is only valuable if accurate. Updating diagrams, labels, and records after each change prevents costly mistakes during future troubleshooting and modifications.",
  },
  {
    q: "A 'rack diagram' (rack elevation) documents...",
    options: [
      "The IP subnet plan",
      "The physical position of each device within a rack, U by U",
      "The firewall rule set",
      "The DNS zone file",
    ],
    answer: 1,
    explain: "A rack elevation shows exactly where each device is mounted in a rack (by U position), aiding installation, capacity planning, and physical troubleshooting.",
  },
  {
    q: "Plenum-rated cable is required in air-handling spaces because it...",
    options: [
      "Is faster than regular cable",
      "Produces less toxic smoke and is more fire-resistant",
      "Is cheaper",
      "Needs no connectors",
    ],
    answer: 1,
    explain: "Plenum spaces circulate building air. Plenum-rated (CMP) cable uses fire-resistant jacketing that emits less toxic smoke when burning, meeting fire codes.",
  },
  {
    q: "A change request typically must include all of the following EXCEPT...",
    options: [
      "The reason and scope of the change",
      "A rollback plan",
      "An approval/sign-off",
      "The personal social media passwords of the requester",
    ],
    answer: 3,
    explain: "Change requests document reason, scope, risk, implementation and rollback plans, and approvals. Personal credentials are never part of a change request.",
  },
  {
    q: "A 'site survey' document for a building would most directly support which task?",
    options: [
      "Planning wireless AP placement and cabling runs",
      "Configuring a DNS server",
      "Writing a firewall ACL",
      "Choosing a routing protocol",
    ],
    answer: 0,
    explain: "A site survey records the physical environment — walls, distances, interference, power — informing where to place APs, IDFs, and cable runs during design.",
  },
];
