// ── Module 05 — Cabling (35) ────────────────────────────────────────────────
QUESTIONS["05"] = [
  {
    q: "What does UTP stand for?",
    options: ["Universal Transport Protocol", "Unshielded Twisted Pair", "Unified Transmission Path", "Uniform Terminal Port"],
    answer: 1,
    explain: "UTP (Unshielded Twisted Pair) is the most common copper LAN cable. Twisting the pairs reduces crosstalk and EMI without a shield.",
  },
  {
    q: "Why are the wire pairs in twisted-pair cable twisted?",
    options: [
      "To make them cheaper",
      "To reduce electromagnetic interference and crosstalk",
      "To increase weight",
      "To allow PoE",
    ],
    answer: 1,
    explain: "Twisting causes interference to affect both wires equally so it cancels out (common-mode rejection), reducing crosstalk between pairs and susceptibility to EMI.",
  },
  {
    q: "Which copper category supports 10 Gbps up to 100 m and is the common modern choice?",
    options: ["Cat 3", "Cat 5", "Cat 6a", "Cat 1"],
    answer: 2,
    explain: "Cat 6a supports 10GBASE-T (10 Gbps) over the full 100 m. Cat 6 can do 10 Gbps only to ~55 m; Cat 5e tops out at 1 Gbps for general use.",
  },
  {
    q: "What is the maximum data rate of Cat 5e over 100 m?",
    options: ["10 Mbps", "100 Mbps", "1 Gbps", "10 Gbps"],
    answer: 2,
    explain: "Cat 5e supports 1000BASE-T (1 Gbps) at up to 100 m and is still widely deployed for gigabit connections.",
  },
  {
    q: "Which connector is standard for twisted-pair Ethernet?",
    options: ["BNC", "RJ-45", "LC", "SC"],
    answer: 1,
    explain: "RJ-45 (8P8C) is the modular connector used on UTP/STP Ethernet cables. LC/SC are fiber connectors; BNC is legacy coax.",
  },
  {
    q: "Which cable type carries data as pulses of light and is immune to EMI?",
    options: ["UTP copper", "Coaxial", "Fiber optic", "STP copper"],
    answer: 2,
    explain: "Fiber-optic cable transmits light through glass/plastic cores. Because it carries no electrical signal, it is immune to EMI and supports long distances and high bandwidth.",
  },
  {
    q: "Single-mode fiber (SMF) differs from multimode fiber (MMF) in that SMF...",
    options: [
      "Has a larger core and shorter range",
      "Has a very small core, uses laser light, and supports much longer distances",
      "Is made of copper",
      "Cannot carry data",
    ],
    answer: 1,
    explain: "SMF has a ~9 µm core and uses laser sources for long-haul, high-bandwidth links (kilometers). MMF has a larger core (50/62.5 µm), uses LEDs/VCSELs, and suits shorter runs.",
  },
  {
    q: "Which is a common fiber connector with a small form factor, often in duplex pairs?",
    options: ["RJ-45", "LC", "RJ-11", "F-type"],
    answer: 1,
    explain: "LC (Lucent Connector) is a small-form-factor fiber connector, frequently used in duplex configurations in high-density equipment. SC and ST are larger, older types.",
  },
  {
    q: "What is 'attenuation' in cabling?",
    options: [
      "Signal interference from adjacent pairs",
      "The loss of signal strength over distance",
      "A type of connector",
      "Excess cable length",
    ],
    answer: 1,
    explain: "Attenuation is the weakening of a signal as it travels along the medium. Exceeding length limits increases attenuation until the signal is unusable.",
  },
  {
    q: "'Crosstalk' refers to...",
    options: [
      "Signal from one wire pair interfering with another",
      "Loss of signal over distance",
      "Fiber light leakage",
      "A grounding fault",
    ],
    answer: 0,
    explain: "Crosstalk is unwanted coupling of a signal from one pair into an adjacent pair. NEXT (near-end) and FEXT (far-end) crosstalk are measured during certification.",
  },
  {
    q: "Which cabling is most resistant to electromagnetic interference (EMI)?",
    options: ["UTP", "Fiber optic", "Cat 3", "Coax"],
    answer: 1,
    explain: "Fiber carries light, not electricity, so it is entirely immune to EMI/RFI — ideal for noisy industrial environments or long runs near power lines.",
  },
  {
    q: "STP (Shielded Twisted Pair) adds what over UTP?",
    options: [
      "A light source",
      "Metallic shielding to further reduce EMI",
      "More conductors",
      "Fiber strands",
    ],
    answer: 1,
    explain: "STP adds foil/braid shielding around pairs and/or the whole cable to reduce EMI in electrically noisy environments, at higher cost and stiffness. Proper grounding is required.",
  },
  {
    q: "PoE (Power over Ethernet) allows...",
    options: [
      "Data to travel over power lines",
      "Electrical power and data to travel over the same Ethernet cable",
      "Fiber to carry power",
      "Wireless charging",
    ],
    answer: 1,
    explain: "PoE (IEEE 802.3af/at/bt) delivers DC power alongside data on twisted-pair cabling, powering APs, IP phones, and cameras without separate power supplies.",
  },
  {
    q: "Which IEEE standard is the original PoE providing up to ~15.4 W?",
    options: ["802.3af", "802.3at", "802.3bt", "802.11ac"],
    answer: 0,
    explain: "802.3af (PoE) supplies up to 15.4 W at the source. 802.3at (PoE+) provides ~30 W, and 802.3bt (PoE++/4PPoE) up to 60–100 W.",
  },
  {
    q: "A straight-through UTP cable is used to connect...",
    options: [
      "Two PCs directly (older gear)",
      "A PC or router to a switch/hub (unlike devices)",
      "Two switches only",
      "Fiber to copper",
    ],
    answer: 1,
    explain: "Straight-through cables (same standard on both ends) connect unlike devices — e.g., host-to-switch. Crossover cables historically connected like devices. Auto-MDIX now makes this mostly automatic.",
  },
  {
    q: "Which tool verifies that a cable's wires are correctly terminated and identifies opens/shorts/miswires?",
    options: ["Cable tester", "Multimeter only", "Loopback plug", "Toner probe"],
    answer: 0,
    explain: "A cable tester (continuity/wiremap tester) checks each conductor for opens, shorts, and correct pin-to-pin mapping. Certifiers also measure crosstalk and attenuation.",
  },
  {
    q: "A toner probe (tone generator + probe) is used to...",
    options: [
      "Measure bandwidth",
      "Locate/trace a specific cable within a bundle",
      "Terminate fiber",
      "Configure a switch",
    ],
    answer: 1,
    explain: "A tone generator injects an audible signal onto a wire; the probe detects it, letting you identify which cable in a bundle or patch panel is which.",
  },
  {
    q: "Which Ethernet standard describes 1 Gbps over twisted-pair copper?",
    options: ["10BASE-T", "100BASE-TX", "1000BASE-T", "10GBASE-SR"],
    answer: 2,
    explain: "1000BASE-T is Gigabit Ethernet over Cat 5e/6 copper (all four pairs). 10BASE-T=10 Mbps, 100BASE-TX=100 Mbps, 10GBASE-SR is 10 Gbps over MMF.",
  },
  {
    q: "In Ethernet naming like 1000BASE-T, what does 'BASE' indicate?",
    options: ["The base station", "Baseband signaling (whole medium carries one signal)", "The cable base color", "The building basement"],
    answer: 1,
    explain: "'BASE' means baseband — the entire bandwidth of the medium carries a single digital signal (vs broadband, which multiplexes multiple channels).",
  },
  {
    q: "A transceiver module like an SFP or SFP+ is used to...",
    options: [
      "Provide a modular fiber/copper port on a switch or router",
      "Store configuration",
      "Assign IP addresses",
      "Filter packets",
    ],
    answer: 0,
    explain: "SFP/SFP+/QSFP transceivers are hot-swappable modules that plug into a switch/router cage to provide a specific media/speed interface (e.g., 1G SX fiber, 10G copper).",
  },
  {
    q: "A media converter is used to...",
    options: [
      "Convert between two media types, e.g., copper Ethernet to fiber",
      "Change IP addresses",
      "Encrypt traffic",
      "Assign VLANs",
    ],
    answer: 0,
    explain: "A media converter bridges different physical media — commonly converting copper (UTP) to fiber to extend a link's distance.",
  },
  {
    q: "Coaxial cable is most associated today with...",
    options: [
      "Backbone fiber runs",
      "Cable Internet/TV (e.g., RG-6) and some legacy networks",
      "PoE only",
      "Wireless bridging",
    ],
    answer: 1,
    explain: "Coax (e.g., RG-6, RG-59) is used for cable TV/broadband and older 10BASE2/10BASE5 Ethernet. F-type and BNC are common coax connectors.",
  },
  {
    q: "The maximum distance for standard 1000BASE-T over copper is...",
    options: ["55 m", "100 m", "550 m", "2 km"],
    answer: 1,
    explain: "Like other twisted-pair Ethernet, 1000BASE-T is limited to 100 m per segment. Longer distances require fiber or repeaters/switches.",
  },
  {
    q: "Which fiber type would you choose to connect two buildings 2 km apart at 10 Gbps?",
    options: ["Cat 6 UTP", "Single-mode fiber", "Coax RG-6", "Cat 5e"],
    answer: 1,
    explain: "Copper can't span 2 km. Single-mode fiber supports long distances (many kilometers) at high speeds and is the right choice for building-to-building backbones.",
  },
  {
    q: "Auto-MDIX on a switch port...",
    options: [
      "Automatically detects and adjusts for straight-through vs crossover cabling",
      "Assigns VLANs automatically",
      "Provides PoE",
      "Encrypts the link",
    ],
    answer: 0,
    explain: "Auto-MDIX automatically senses the cable type and swaps transmit/receive pairs as needed, so either straight-through or crossover cables work — making crossover cables largely obsolete.",
  },
  {
    q: "Which certification-grade measurement checks total signal loss end to end on fiber?",
    options: ["dB loss / insertion loss (using an OTDR or power meter)", "Wiremap", "PoE budget", "MAC table size"],
    answer: 0,
    explain: "Fiber links are validated by measuring insertion loss (dB) with a light source/power meter, and characterized with an OTDR to locate splices, bends, and breaks.",
  },
  {
    q: "EMI/RFI on a copper run is BEST mitigated by...",
    options: [
      "Running cable parallel to power lines",
      "Using shielded cable (STP) or switching to fiber, and keeping distance from noise sources",
      "Increasing cable length",
      "Removing the twists",
    ],
    answer: 1,
    explain: "To fight EMI: use STP or fiber, route away from motors/fluorescent lights/power lines, and keep proper twists. Fiber eliminates the problem entirely.",
  },
  {
    q: "A 'patch cable' (patch cord) is typically...",
    options: [
      "Solid-core cable for in-wall runs",
      "Short stranded-core cable used to connect devices to jacks/patch panels",
      "Fiber only",
      "Coaxial only",
    ],
    answer: 1,
    explain: "Patch cords are short, flexible, stranded-conductor cables for connecting equipment to wall jacks or patch panels. Solid-core cable is used for longer permanent in-wall runs.",
  },
  {
    q: "Which of the following BEST describes plenum vs riser cable rating?",
    options: [
      "Plenum is for air spaces and is more fire-resistant; riser is for vertical shafts between floors",
      "They are identical",
      "Riser is only for fiber",
      "Plenum is cheaper and less safe",
    ],
    answer: 0,
    explain: "Plenum-rated (CMP) cable is required in HVAC air-handling spaces (less toxic smoke). Riser-rated (CMR) cable is for vertical runs between floors. Plenum exceeds riser fire requirements.",
  },
  {
    q: "10GBASE-SR runs over which medium?",
    options: ["Single-mode fiber", "Multimode fiber (short reach)", "Cat 3 copper", "Coax"],
    answer: 1,
    explain: "10GBASE-SR ('short reach') runs 10 Gbps over multimode fiber for distances up to a few hundred meters. 10GBASE-LR uses single-mode for long reach.",
  },
  {
    q: "Which problem is indicated by a wiremap showing pins 1&2 crossed with 3&6?",
    options: [
      "Correct T568B termination",
      "A miswire/split-pair or crossover situation to investigate",
      "Fiber attenuation",
      "PoE overload",
    ],
    answer: 1,
    explain: "A wiremap that shows swapped pairs indicates a termination error (or an intentional crossover). For a straight-through link it must be corrected for reliable operation.",
  },
  {
    q: "The core diameter of typical multimode fiber is...",
    options: ["9 µm", "50 or 62.5 µm", "1 mm", "0.5 µm"],
    answer: 1,
    explain: "Multimode fiber has a larger core (50 or 62.5 µm) allowing multiple light paths (modes). Single-mode's ~9 µm core permits one mode, reducing dispersion over distance.",
  },
  {
    q: "Why is fiber preferred for backbone links over copper?",
    options: [
      "It is always cheaper",
      "Greater bandwidth, longer distance, and immunity to EMI",
      "It requires no connectors",
      "It supplies power to devices",
    ],
    answer: 1,
    explain: "Fiber backbones carry more bandwidth over far greater distances than copper's 100 m limit and are immune to EMI — ideal for MDF-to-IDF and inter-building runs.",
  },
  {
    q: "A bad or dirty fiber connector end-face most directly causes...",
    options: [
      "Higher insertion loss and link errors",
      "A VLAN mismatch",
      "An IP conflict",
      "A DHCP failure",
    ],
    answer: 0,
    explain: "Contamination or damage on a fiber end-face scatters light, raising insertion loss and causing errors or link failure. Fiber ends should be inspected and cleaned before mating.",
  },
  {
    q: "Which best describes 'bend radius' for fiber?",
    options: [
      "The maximum data rate",
      "The minimum radius a cable can be bent before signal loss or damage occurs",
      "The connector size",
      "The color code",
    ],
    answer: 1,
    explain: "Every cable has a minimum bend radius; bending fiber tighter than this causes macrobend loss (light escaping the core) or physical damage. Respect it during installation.",
  },
];
