// ── Module 02 — Infrastructure & Documentation · expansion pool ─────────────
QUESTIONS["02"].push(
  {
    q: "What is a cross-connect in structured cabling?",
    options: [
      "A crossover cable",
      "A facility where cabling is terminated and interconnected via patch cords",
      "A type of fiber connector",
      "A wireless bridge",
    ],
    answer: 1,
    explain: "A cross-connect is a location (in the MDF/IDF) where cables terminate on panels and are joined with patch cords, allowing flexible reconfiguration.",
  },
  {
    q: "Which cabling connects the telecommunications room to individual work-area outlets?",
    options: ["Backbone cabling", "Horizontal cabling", "Riser cabling", "Entrance cabling"],
    answer: 1,
    explain: "Horizontal cabling runs from the IDF/telecom room to the wall jacks in the work area, limited to a 100 m channel.",
  },
  {
    q: "Which cabling interconnects the MDF, IDFs, and equipment rooms, often between floors?",
    options: ["Horizontal cabling", "Backbone (vertical) cabling", "Patch cords", "Work-area cabling"],
    answer: 1,
    explain: "Backbone (vertical/riser) cabling links distribution frames and floors, frequently using fiber for distance and bandwidth.",
  },
  {
    q: "A standard equipment rack is how many rack units (U) tall?",
    options: ["19U", "24U", "42U", "50U"],
    answer: 2,
    explain: "A full-height rack is typically 42U tall (each U = 1.75 in). Rack width is 19 inches.",
  },
  {
    q: "Which document shows the exact U-position of each device in a rack?",
    options: ["Logical diagram", "Rack elevation (rack diagram)", "IPAM sheet", "Change log"],
    answer: 1,
    explain: "A rack elevation/rack diagram maps each device's mounting position (by U) to aid installation and physical troubleshooting.",
  },
  {
    q: "What is the purpose of a keystone jack?",
    options: [
      "To power a device",
      "To terminate a cable at a wall plate or patch panel with a snap-in modular connector",
      "To convert copper to fiber",
      "To test cables",
    ],
    answer: 1,
    explain: "A keystone jack is a modular snap-in connector (e.g., RJ-45) used in wall plates and patch panels to terminate cabling.",
  },
  {
    q: "Which TIA-568 termination standard is functionally identical in performance to the other, differing only in pair colors?",
    options: ["T568A and T568B", "RS-232 and RS-485", "SC and LC", "CAT5 and CAT6"],
    answer: 0,
    explain: "T568A and T568B perform identically; they only differ in the color order of pairs 2 and 3. Consistency on both ends is what matters.",
  },
  {
    q: "What primarily determines whether a UTP cable is straight-through or crossover?",
    options: [
      "The cable length",
      "Whether both ends use the same standard (straight) or different standards (crossover)",
      "The jacket color",
      "The connector brand",
    ],
    answer: 1,
    explain: "Same standard on both ends = straight-through; T568A on one end and T568B on the other = crossover (swaps TX/RX pairs).",
  },
  {
    q: "A patch panel is best described as...",
    options: [
      "An active switching device",
      "A passive termination point connecting permanent cabling to patch cords",
      "A router",
      "A firewall",
    ],
    answer: 1,
    explain: "A patch panel is passive — permanent runs are punched down on the back, and patch cords connect the front ports to switches.",
  },
  {
    q: "Which is a benefit of good cable management in a rack?",
    options: [
      "Higher IP address capacity",
      "Improved airflow, easier servicing, and fewer accidental disconnects",
      "Stronger encryption",
      "Faster CPU",
    ],
    answer: 1,
    explain: "Neat cabling (trays, ties, labels) improves cooling/airflow, makes tracing and servicing easier, and reduces the risk of unplugging the wrong cable.",
  },
  {
    q: "What does an SLA define?",
    options: [
      "Cable color codes",
      "Agreed service levels such as uptime, response, and repair times",
      "The OSI layers",
      "The DNS hierarchy",
    ],
    answer: 1,
    explain: "A Service Level Agreement specifies measurable service commitments (uptime %, response/repair times, penalties) between provider and customer.",
  },
  {
    q: "Which policy defines how employees may use company network resources?",
    options: ["AUP", "SLA", "MOU", "SOW"],
    answer: 0,
    explain: "An Acceptable Use Policy (AUP) sets the rules for using organizational computing/network resources and the consequences of misuse.",
  },
  {
    q: "A change request should always include which of the following?",
    options: [
      "A rollback (back-out) plan",
      "The requester's home address",
      "The switch serial numbers of every device",
      "A marketing plan",
    ],
    answer: 0,
    explain: "A rollback plan is essential so the change can be reversed if it fails, minimizing downtime.",
  },
  {
    q: "Why should network documentation be updated immediately after a change?",
    options: [
      "To increase bandwidth",
      "Because stale documentation misleads future troubleshooting and changes",
      "It is legally required to never change docs",
      "To slow down attackers",
    ],
    answer: 1,
    explain: "Documentation is only useful if accurate; updating diagrams, labels, and records after each change prevents costly mistakes later.",
  },
  {
    q: "Which is captured by a performance baseline?",
    options: [
      "The lowest cable in a bundle",
      "Normal utilization, latency, and error rates for later comparison",
      "The firewall rule set",
      "The DNS zone file",
    ],
    answer: 1,
    explain: "A baseline records normal operating metrics so anomalies (spikes, slowdowns, breaches) can be recognized by deviation.",
  },
  {
    q: "Where does the ISP's cabling typically enter a building and meet the customer wiring?",
    options: ["Work area", "Entrance facility (near the demarc)", "IDF on the top floor", "Server rack front"],
    answer: 1,
    explain: "The entrance facility is where external service-provider cabling enters the building and connects to the internal structured cabling at the demarc.",
  },
  {
    q: "The point separating provider responsibility from customer responsibility is the...",
    options: ["Patch panel", "Demarcation point (demarc)", "Core switch", "Keystone jack"],
    answer: 1,
    explain: "The demarc marks the boundary of ownership/responsibility between the service provider and the customer premises.",
  },
  {
    q: "Which tool seats wires into a 110 block or patch panel and trims the excess?",
    options: ["Crimper", "Punch-down tool", "Toner probe", "Cable certifier"],
    answer: 1,
    explain: "A punch-down tool pushes each conductor into an insulation-displacement contact and can cut the excess wire in one motion.",
  },
  {
    q: "Which tool attaches an RJ-45 plug to the end of a patch cable?",
    options: ["Punch-down tool", "Crimper", "OTDR", "Multimeter"],
    answer: 1,
    explain: "A crimping tool secures an RJ-45 connector onto a stranded patch cable by pressing the pins onto the conductors.",
  },
  {
    q: "Which cable rating is required in HVAC air-handling (plenum) spaces?",
    options: ["Riser (CMR)", "Plenum (CMP)", "General purpose (CM)", "Direct burial"],
    answer: 1,
    explain: "Plenum-rated (CMP) cable uses fire-resistant, low-smoke jacketing required where building air circulates, meeting fire code.",
  },
  {
    q: "Riser-rated (CMR) cable is intended for...",
    options: [
      "Air-handling plenums",
      "Vertical shafts running between floors",
      "Outdoor burial",
      "Undersea use",
    ],
    answer: 1,
    explain: "Riser cable is rated for vertical runs between floors. Plenum exceeds riser fire requirements and can substitute for it, but not vice versa.",
  },
  {
    q: "An IPAM system primarily tracks...",
    options: [
      "Employee payroll",
      "IP address, subnet, hostname, and DHCP/DNS allocations",
      "Cable colors",
      "Rack temperatures",
    ],
    answer: 1,
    explain: "IP Address Management tracks which addresses/subnets are assigned, reserved, or free, plus DNS/DHCP data — preventing conflicts.",
  },
  {
    q: "MTTR measures...",
    options: [
      "Mean time between failures",
      "Mean time to repair/restore a failed device or service",
      "Maximum transmission rate",
      "Media transfer ratio",
    ],
    answer: 1,
    explain: "MTTR (Mean Time To Repair) is the average time to restore service after a failure; lower is better.",
  },
  {
    q: "MTBF estimates...",
    options: [
      "How long repairs take",
      "The average operating time before a device fails",
      "The bandwidth of a link",
      "The number of ports",
    ],
    answer: 1,
    explain: "MTBF (Mean Time Between Failures) estimates average operational lifetime before failure — used in reliability planning.",
  },
  {
    q: "A logical network diagram would MOST likely show...",
    options: [
      "Exact cable lengths and rack positions",
      "IP subnets, VLANs, and how traffic flows",
      "The building's floor tiles",
      "Employee seating chart",
    ],
    answer: 1,
    explain: "Logical diagrams depict addressing, VLANs/subnets, and data flow; physical diagrams show devices, ports, and cable runs.",
  },
  {
    q: "A physical network diagram would MOST likely show...",
    options: [
      "IP routing metrics",
      "Actual devices, ports, cable runs, and locations",
      "DNS records",
      "Firewall rule order",
    ],
    answer: 1,
    explain: "Physical diagrams document the tangible layout — devices, port connections, and cable paths — while logical diagrams show addressing/flow.",
  },
  {
    q: "The main goal of a consistent labeling scheme is to...",
    options: [
      "Improve encryption",
      "Let technicians quickly and unambiguously identify cables, ports, and equipment",
      "Increase bandwidth",
      "Reduce power draw",
    ],
    answer: 1,
    explain: "Standard labels on cables, jacks, panels, and racks speed up tracing connections and reduce errors during changes/troubleshooting.",
  },
  {
    q: "Which is a valid reason to use fiber for a backbone run between two IDFs 300 m apart?",
    options: [
      "Copper is cheaper for that distance",
      "The distance exceeds copper's 100 m limit; fiber handles the length and bandwidth",
      "Fiber needs no connectors",
      "Copper is immune to EMI",
    ],
    answer: 1,
    explain: "Copper Ethernet is limited to 100 m, so a 300 m backbone requires fiber, which also offers higher bandwidth and EMI immunity.",
  },
  {
    q: "What is the maximum horizontal channel length under TIA-568?",
    options: ["55 m", "90 m", "100 m", "150 m"],
    answer: 2,
    explain: "The horizontal channel is limited to 100 m: up to ~90 m permanent link plus ~10 m of patch cords at the ends.",
  },
  {
    q: "A change advisory board (CAB) is responsible for...",
    options: [
      "Crimping cables",
      "Reviewing and approving proposed changes",
      "Assigning IP addresses",
      "Monitoring temperature",
    ],
    answer: 1,
    explain: "A CAB reviews change requests, assesses risk, and approves/schedules changes as part of change management.",
  },
  {
    q: "Which document formally records details of a proposed change and its approval?",
    options: ["Change request / RFC", "MSDS", "DNS zone", "ARP table"],
    answer: 0,
    explain: "A change request (a.k.a. RFC — Request for Change) documents the reason, scope, risk, plan, rollback, and approval for a change.",
  },
  {
    q: "Which safety document accompanies hazardous materials like toner or batteries?",
    options: ["SLA", "MSDS/SDS", "RFC", "AUP"],
    answer: 1,
    explain: "An MSDS/SDS (Material/Safety Data Sheet) provides safe handling, storage, and disposal information for hazardous materials.",
  },
  {
    q: "In structured cabling, what does the work area typically include?",
    options: [
      "The core routers",
      "The end-user's wall jack, patch cord, and connected device",
      "The ISP's equipment",
      "The generator",
    ],
    answer: 1,
    explain: "The work area is where users connect — the wall outlet, the patch cord, and the end device (PC, phone, printer).",
  },
  {
    q: "Which is TRUE about an MDF and IDF relationship?",
    options: [
      "IDFs replace the MDF",
      "IDFs branch out from the MDF and connect back to it via backbone cabling",
      "They are the same room",
      "The MDF connects to the work area directly",
    ],
    answer: 1,
    explain: "The MDF is the central hub; IDFs (often per floor) aggregate local cabling and link back to the MDF over the backbone.",
  },
  {
    q: "Which practice helps maintain airflow and prevent overheating in a server room?",
    options: [
      "Blocking all vents",
      "Hot-aisle/cold-aisle layout and blanking panels in empty rack slots",
      "Removing all fans",
      "Stacking devices without gaps",
    ],
    answer: 1,
    explain: "Hot-aisle/cold-aisle containment and blanking panels direct cooling efficiently and prevent hot air recirculation.",
  },
  {
    q: "A wiring diagram that assigns a code like IDF2-PP1-P14 is an example of...",
    options: [
      "An IP addressing plan",
      "A labeling/identification scheme",
      "A routing table",
      "A firewall policy",
    ],
    answer: 1,
    explain: "Such codes are a labeling scheme identifying a specific port (IDF 2, patch panel 1, port 14) for fast tracing.",
  },
  {
    q: "The purpose of a demarc extension is to...",
    options: [
      "Extend the provider's circuit from the demarc to the equipment room inside the building",
      "Add more VLANs",
      "Increase Wi-Fi range",
      "Encrypt the WAN link",
    ],
    answer: 0,
    explain: "A demarc extension carries the provider's circuit from the demarcation point to the customer's internal equipment location.",
  },
  {
    q: "Which is an asset/inventory record most likely to contain?",
    options: [
      "Device model, serial number, firmware, warranty, and location",
      "The CEO's calendar",
      "The DNS TTL",
      "The cable jacket color only",
    ],
    answer: 0,
    explain: "An inventory tracks each asset's model, serial, firmware/version, warranty, and location for support and lifecycle management.",
  },
  {
    q: "Which best describes 'MDF' in one phrase?",
    options: [
      "Multi-Density Fiber",
      "Main Distribution Frame — the central interconnect point",
      "Managed Device Firmware",
      "Metro Data Facility",
    ],
    answer: 1,
    explain: "The MDF (Main Distribution Frame) is the central point of a building's structured cabling where core equipment and cross-connects reside.",
  },
  {
    q: "Which of these is a preventive maintenance task for cabling infrastructure?",
    options: [
      "Ignoring loose cables",
      "Periodically inspecting, re-securing, and labeling cables; verifying documentation",
      "Removing all labels",
      "Disabling monitoring",
    ],
    answer: 1,
    explain: "Routine inspection, tidy re-securing, accurate labels, and up-to-date documentation prevent faults and speed future work.",
  },
  {
    q: "A 66 block and a 110 block are types of...",
    options: [
      "Fiber connectors",
      "Punch-down termination blocks",
      "Routers",
      "Wireless antennas",
    ],
    answer: 1,
    explain: "66 and 110 blocks are punch-down termination blocks; 110 blocks are common for modern data cabling, 66 blocks for legacy voice.",
  },
  {
    q: "Which factor most justifies scheduling a change during a maintenance window?",
    options: [
      "To maximize user disruption",
      "To minimize impact by making changes during low-usage periods with a rollback ready",
      "To avoid documentation",
      "To skip approvals",
    ],
    answer: 1,
    explain: "Maintenance windows during off-peak times reduce user impact, and a rollback plan limits risk if the change fails.",
  },
  {
    q: "Which best describes an 'as-built' diagram?",
    options: [
      "A proposed future design",
      "Documentation reflecting the network exactly as it was actually installed",
      "A marketing brochure",
      "A budget spreadsheet",
    ],
    answer: 1,
    explain: "An as-built diagram documents the real, installed state (which may differ from the original plan) — essential for accurate troubleshooting.",
  },
  {
    q: "Which measurement unit describes rack-mounted device height?",
    options: ["AWG", "Rack unit (U)", "dBm", "MHz"],
    answer: 1,
    explain: "Device height is measured in rack units (U), where 1U = 1.75 inches. A '2U server' occupies two rack units.",
  },
  {
    q: "Which is a benefit of centralized documentation stored in a shared, version-controlled location?",
    options: [
      "Only one person can ever see it",
      "The whole team works from the same current information, with change history",
      "It prevents any updates",
      "It removes the need for backups",
    ],
    answer: 1,
    explain: "Shared, versioned documentation keeps everyone aligned on current state and preserves a history of changes for auditing.",
  },
  {
    q: "A patch cord differs from horizontal cable in that a patch cord is usually...",
    options: [
      "Solid-core for in-wall runs",
      "Stranded and flexible for short device-to-jack connections",
      "Fiber only",
      "Coaxial only",
    ],
    answer: 1,
    explain: "Patch cords use flexible stranded conductors for short connections; horizontal runs use solid-core cable for longer in-wall permanence.",
  },
  {
    q: "Which is the correct order of remediation priority when a change causes an outage?",
    options: [
      "Blame the user, then wait",
      "Execute the rollback plan to restore service, then investigate root cause",
      "Delete the documentation",
      "Ignore it until the next window",
    ],
    answer: 1,
    explain: "Restore service first via the rollback/back-out plan, then investigate the root cause once users are back online.",
  },
  {
    q: "Environmental monitoring in a server room typically tracks...",
    options: [
      "IP addresses",
      "Temperature, humidity, and sometimes water/smoke",
      "DNS records",
      "VLAN tags",
    ],
    answer: 1,
    explain: "Environmental sensors watch temperature, humidity, airflow, and leaks/smoke to protect equipment and trigger alerts before damage.",
  },
  {
    q: "Which is the BEST reason to keep spare patch cords and transceivers on hand?",
    options: [
      "To reduce MTTR by replacing failed components quickly",
      "To increase bandwidth automatically",
      "To avoid documentation",
      "To raise the rack height",
    ],
    answer: 0,
    explain: "On-hand spares shorten repair time (lower MTTR) because a failed cable/transceiver can be swapped immediately.",
  },
  {
    q: "Which item belongs in a network's standard operating procedures (SOPs)?",
    options: [
      "Step-by-step instructions for common tasks like onboarding a switch",
      "The CEO's salary",
      "Random cable colors",
      "Unrelated marketing copy",
    ],
    answer: 0,
    explain: "SOPs document repeatable procedures (e.g., provisioning a switch, adding a VLAN) so tasks are done consistently and correctly.",
  },
  {
    q: "The main risk of undocumented 'temporary' cabling is that it...",
    options: [
      "Improves airflow",
      "Becomes permanent, untraceable, and a source of outages",
      "Increases security",
      "Reduces cost forever",
    ],
    answer: 1,
    explain: "Undocumented temporary runs often persist, creating a tangle no one can trace — a frequent cause of hard-to-diagnose outages.",
  },
  {
    q: "Which describes 'zero U' (0U) rack space?",
    options: [
      "Space that doesn't consume rack-unit height, e.g., vertical PDUs mounted on the side",
      "The top of the rack only",
      "A rack with no devices",
      "A fiber patch panel",
    ],
    answer: 0,
    explain: "0U accessories (like vertical PDUs or cable managers) mount in the rack without occupying the front-facing U positions.",
  },
  {
    q: "Which is a key advantage of modular patch panels over fixed ones?",
    options: [
      "They cannot be changed",
      "Keystone jacks can be added/replaced individually to mix media types",
      "They require no termination",
      "They only support fiber",
    ],
    answer: 1,
    explain: "Modular panels accept individual keystone jacks, letting you mix connector/media types and replace a single port without rewiring the panel.",
  },
  {
    q: "A well-formed change record improves future troubleshooting because it...",
    options: [
      "Hides what changed",
      "Provides a searchable history linking symptoms to recent changes",
      "Deletes old configs",
      "Prevents rollbacks",
    ],
    answer: 1,
    explain: "Change history lets troubleshooters correlate a new problem with a recent change — often the fastest path to root cause.",
  }
);
