// ── Module 08 — Subnets & VLANs (50) ────────────────────────────────────────
QUESTIONS["08"] = [
  {
    q: "What is the primary purpose of network segmentation?",
    options: [
      "To slow the network down",
      "To separate traffic for better security, performance, and easier troubleshooting",
      "To remove the need for routers",
      "To eliminate IP addresses",
    ],
    answer: 1,
    explain: "Segmenting a network into smaller pieces isolates traffic (separate broadcast domains), enhancing security, improving performance, and simplifying troubleshooting.",
  },
  {
    q: "Each subnet is its own...",
    options: ["Collision domain only", "Broadcast domain", "MAC address", "VLAN trunk"],
    answer: 1,
    explain: "Subnetting divides a network into separate broadcast domains, so broadcasts in one subnet don't propagate to others — reducing overhead and containing issues.",
  },
  {
    q: "How many usable hosts are in a /24 network?",
    options: ["254", "256", "252", "128"],
    answer: 0,
    explain: "A /24 has 8 host bits: 2^8 = 256 addresses, minus 2 (network and broadcast) = 254 usable host addresses.",
  },
  {
    q: "The subnet mask for a /26 is...",
    options: ["255.255.255.0", "255.255.255.192", "255.255.255.224", "255.255.255.128"],
    answer: 1,
    explain: "/26 = 26 network bits. The 4th octet is 11000000 = 192, so the mask is 255.255.255.192. Block size = 256 − 192 = 64.",
  },
  {
    q: "How many usable hosts are in a /26 subnet?",
    options: ["64", "62", "30", "126"],
    answer: 1,
    explain: "/26 has 6 host bits: 2^6 = 64, minus 2 = 62 usable hosts per subnet.",
  },
  {
    q: "How many /26 subnets can you create from a single /24?",
    options: ["2", "4", "8", "16"],
    answer: 1,
    explain: "Going from /24 to /26 borrows 2 bits: 2^2 = 4 subnets, each with 62 usable hosts.",
  },
  {
    q: "For the network 192.168.1.0/26, what is the broadcast address of the FIRST subnet?",
    options: ["192.168.1.63", "192.168.1.64", "192.168.1.127", "192.168.1.255"],
    answer: 0,
    explain: "Block size is 64. First subnet = 192.168.1.0–192.168.1.63, so its broadcast is 192.168.1.63 and usable hosts are .1–.62.",
  },
  {
    q: "What is the block size for a /28 subnet?",
    options: ["4", "8", "16", "32"],
    answer: 2,
    explain: "/28 mask is 255.255.255.240. Block size = 256 − 240 = 16. Each /28 has 16 addresses (14 usable).",
  },
  {
    q: "How many usable hosts are in a /28?",
    options: ["16", "14", "30", "12"],
    answer: 1,
    explain: "/28 has 4 host bits: 2^4 = 16, minus 2 = 14 usable hosts. Common for small point-to-point or device subnets.",
  },
  {
    q: "A /30 subnet mask is 255.255.255.252 and provides how many usable hosts?",
    options: ["4", "2", "6", "0"],
    answer: 1,
    explain: "/30 has 2 host bits: 2^2 = 4 addresses, minus 2 = 2 usable — ideal for point-to-point router links (two endpoints).",
  },
  {
    q: "The formula for the number of usable hosts per subnet is...",
    options: ["2^n", "2^n − 2", "2^n + 2", "n^2"],
    answer: 1,
    explain: "With n host bits, total addresses = 2^n; subtract 2 (network ID and broadcast) for usable hosts = 2^n − 2.",
  },
  {
    q: "The formula for the number of subnets created by borrowing s bits is...",
    options: ["2^s", "2^s − 2", "s × 2", "2^s + 2"],
    answer: 0,
    explain: "Borrowing s bits from the host portion yields 2^s subnets (classless/CIDR counts all of them, including all-zeros and all-ones subnets).",
  },
  {
    q: "Which address in a subnet cannot be assigned to a host?",
    options: [
      "The first usable address",
      "The network ID (all host bits 0) and the broadcast (all host bits 1)",
      "Any odd-numbered address",
      "The default gateway",
    ],
    answer: 1,
    explain: "The network ID (host bits all 0) and the broadcast (host bits all 1) are reserved; hosts use the addresses between them.",
  },
  {
    q: "CIDR (Classless Inter-Domain Routing) allows...",
    options: [
      "Only fixed class boundaries",
      "Flexible network sizes using variable prefix lengths",
      "Removal of subnet masks",
      "Only Class A networks",
    ],
    answer: 1,
    explain: "CIDR abandons rigid class boundaries, letting networks be defined by any prefix length (/8 to /30+), enabling efficient allocation and route summarization.",
  },
  {
    q: "The CIDR notation /22 corresponds to which subnet mask?",
    options: ["255.255.252.0", "255.255.254.0", "255.255.255.0", "255.255.248.0"],
    answer: 0,
    explain: "/22 = 22 network bits. Third octet = 11111100 = 252, so mask = 255.255.252.0. Block size in the 3rd octet = 4; 1024 addresses (1022 usable).",
  },
  {
    q: "What is VLSM?",
    options: [
      "A routing protocol",
      "Variable Length Subnet Masking — using different mask lengths within the same network to fit varying host counts",
      "A cabling standard",
      "A VLAN type",
    ],
    answer: 1,
    explain: "VLSM lets you subnet a network with different prefix lengths, sizing each subnet to its need (e.g., /30 for links, /26 for LANs) to conserve addresses.",
  },
  {
    q: "When designing with VLSM, you should allocate subnets...",
    options: [
      "Smallest requirement first",
      "Largest host requirement first, then progressively smaller",
      "In random order",
      "Only as /24s",
    ],
    answer: 1,
    explain: "Allocate the largest subnets first so big blocks aren't fragmented; then carve smaller subnets (down to /30 links) from the remaining space, avoiding overlap.",
  },
  {
    q: "A point-to-point link between two routers is most efficiently addressed with a...",
    options: ["/24", "/28", "/30 (or /31)", "/16"],
    answer: 2,
    explain: "A /30 gives exactly 2 usable hosts — perfect for a two-router link. A /31 (RFC 3021) uses both addresses for point-to-point, saving even more.",
  },
  {
    q: "What is a VLAN?",
    options: [
      "A physical cable",
      "A logical broadcast domain created on switches, grouping ports/hosts regardless of physical location",
      "A routing protocol",
      "A type of firewall",
    ],
    answer: 1,
    explain: "A VLAN (Virtual LAN) logically segments a switch into separate broadcast domains, so hosts can be grouped by function/security rather than physical location.",
  },
  {
    q: "Which IEEE standard defines VLAN tagging on trunk links?",
    options: ["802.1Q", "802.3af", "802.11ac", "802.1X"],
    answer: 0,
    explain: "IEEE 802.1Q inserts a 4-byte tag (including a 12-bit VLAN ID) into Ethernet frames so multiple VLANs can traverse a single trunk link.",
  },
  {
    q: "How many bits is the VLAN ID field in an 802.1Q tag, and what is the usable VLAN range?",
    options: [
      "8 bits, 1–255",
      "12 bits, 1–4094 usable",
      "16 bits, 1–65535",
      "10 bits, 1–1023",
    ],
    answer: 1,
    explain: "The 802.1Q VID is 12 bits (0–4095). VLANs 1–4094 are usable (0 and 4095 are reserved), giving 4094 possible VLANs.",
  },
  {
    q: "A switch port configured as an 'access port' carries traffic for...",
    options: [
      "All VLANs, tagged",
      "A single VLAN, untagged to the end device",
      "No VLANs",
      "Only the native VLAN's tags",
    ],
    answer: 1,
    explain: "An access port belongs to one VLAN and passes untagged frames to/from an end device (PC, printer). Trunk ports carry multiple VLANs with tags.",
  },
  {
    q: "A 'trunk' port is used to...",
    options: [
      "Connect a single PC",
      "Carry traffic for multiple VLANs between switches (or to a router), using tags",
      "Disable VLANs",
      "Provide PoE",
    ],
    answer: 1,
    explain: "A trunk carries many VLANs over one link between switches/routers, tagging frames (802.1Q) so the far end can separate them back into their VLANs.",
  },
  {
    q: "The 'native VLAN' on an 802.1Q trunk is the VLAN whose frames are...",
    options: ["Double-tagged", "Sent untagged across the trunk", "Dropped", "Encrypted"],
    answer: 1,
    explain: "Frames in the native VLAN traverse the trunk untagged. For security, the native VLAN should be changed from the default (VLAN 1) and match on both ends.",
  },
  {
    q: "To allow devices on different VLANs to communicate, you need...",
    options: [
      "Only a hub",
      "Inter-VLAN routing (a router or Layer 3 switch)",
      "A longer cable",
      "To disable the VLANs",
    ],
    answer: 1,
    explain: "VLANs are separate Layer 3 networks; traffic between them must be routed by a router or Layer 3 switch (via SVIs or router-on-a-stick).",
  },
  {
    q: "'Router-on-a-stick' refers to...",
    options: [
      "A single physical router interface with subinterfaces handling multiple VLANs over one trunk",
      "A wireless router",
      "A router with no ports",
      "A router used as a switch",
    ],
    answer: 0,
    explain: "Router-on-a-stick uses one router interface split into 802.1Q subinterfaces (one per VLAN) connected to a switch trunk, routing between VLANs over a single link.",
  },
  {
    q: "An SVI (Switched Virtual Interface) on a Layer 3 switch is used to...",
    options: [
      "Provide a Layer 3 gateway interface for a VLAN",
      "Physically connect two PCs",
      "Assign MAC addresses",
      "Encrypt trunks",
    ],
    answer: 0,
    explain: "An SVI is a virtual Layer 3 interface associated with a VLAN, giving that VLAN a routed gateway on a multilayer switch for fast inter-VLAN routing.",
  },
  {
    q: "By default, all ports on a new Cisco switch belong to which VLAN?",
    options: ["VLAN 0", "VLAN 1", "VLAN 99", "VLAN 4094"],
    answer: 1,
    explain: "VLAN 1 is the default VLAN for all switch ports. Best practice is to move user traffic and the native/management VLANs off VLAN 1 for security.",
  },
  {
    q: "A common security best practice regarding VLAN 1 is to...",
    options: [
      "Put all users in VLAN 1",
      "Avoid using VLAN 1 for user/management traffic and change the native VLAN",
      "Disable all other VLANs",
      "Use VLAN 1 for the trunk native VLAN",
    ],
    answer: 1,
    explain: "Because VLAN 1 is the default (and a target for VLAN-hopping), move management and user traffic to other VLANs and set a non-default native VLAN on trunks.",
  },
  {
    q: "For the address 172.16.0.0/19, what is the block size in the third octet?",
    options: ["16", "32", "8", "64"],
    answer: 1,
    explain: "/19 mask = 255.255.224.0. Third octet = 224, block size = 256 − 224 = 32. Subnets increment by 32 in the third octet (0, 32, 64, ...).",
  },
  {
    q: "How many usable hosts are in a /19 network?",
    options: ["8190", "8192", "16382", "2046"],
    answer: 0,
    explain: "/19 has 13 host bits: 2^13 = 8192, minus 2 = 8190 usable hosts.",
  },
  {
    q: "Which subnet does host 192.168.10.100/27 belong to?",
    options: [
      "192.168.10.96/27",
      "192.168.10.64/27",
      "192.168.10.100/27",
      "192.168.10.128/27",
    ],
    answer: 0,
    explain: "/27 block size = 32. Subnets: .0, .32, .64, .96, .128. 100 falls between 96 and 127, so the subnet is 192.168.10.96/27 (broadcast .127).",
  },
  {
    q: "The number of host bits needed to support at least 500 hosts is...",
    options: ["8 bits", "9 bits", "10 bits", "7 bits"],
    answer: 1,
    explain: "2^9 − 2 = 510 ≥ 500, while 2^8 − 2 = 254 is too few. So 9 host bits (a /23) are required.",
  },
  {
    q: "In IPv6, the standard subnet size for a single LAN is...",
    options: ["/48", "/56", "/64", "/128"],
    answer: 2,
    explain: "IPv6 LAN subnets are almost always /64 — the first 64 bits are the network prefix and the last 64 bits are the interface ID (used by SLAAC/EUI-64).",
  },
  {
    q: "An organization assigned 2001:db8:abcd::/48 can create how many /64 subnets?",
    options: ["256", "1024", "65,536", "4,294,967,296"],
    answer: 2,
    explain: "From /48 to /64 gives 16 subnet bits: 2^16 = 65,536 possible /64 subnets.",
  },
  {
    q: "Route summarization (supernetting) helps by...",
    options: [
      "Increasing the number of routes",
      "Combining multiple contiguous networks into one advertised route, shrinking routing tables",
      "Encrypting routes",
      "Assigning VLANs",
    ],
    answer: 1,
    explain: "Summarization aggregates contiguous subnets into a single prefix (e.g., four /24s into a /22), reducing routing-table size and update overhead.",
  },
  {
    q: "Which four /24 networks can be summarized as 192.168.4.0/22?",
    options: [
      "192.168.4.0, .5.0, .6.0, .7.0",
      "192.168.0.0, .1.0, .2.0, .3.0",
      "192.168.4.0, .8.0, .12.0, .16.0",
      "192.168.1.0, .2.0, .3.0, .4.0",
    ],
    answer: 0,
    explain: "/22 covers a block of 4 contiguous /24s aligned on a multiple of 4: 192.168.4.0 through 192.168.7.255 = .4.0, .5.0, .6.0, .7.0.",
  },
  {
    q: "VLAN hopping attacks are mitigated by...",
    options: [
      "Enabling DTP on all ports",
      "Disabling unused ports, turning off auto-trunking (DTP), and setting a dedicated native VLAN",
      "Using VLAN 1 for everything",
      "Removing all trunks",
    ],
    answer: 1,
    explain: "Prevent VLAN hopping by disabling DTP/auto-trunk negotiation, hardcoding access vs trunk, shutting unused ports, and using a non-default, unused native VLAN.",
  },
  {
    q: "The subnet mask 255.255.255.248 is which prefix length?",
    options: ["/27", "/28", "/29", "/30"],
    answer: 2,
    explain: "248 = 11111000 (5 bits) in the 4th octet, so 24 + 5 = /29. Block size = 8; 6 usable hosts.",
  },
  {
    q: "How many usable hosts does a /29 provide?",
    options: ["8", "6", "14", "2"],
    answer: 1,
    explain: "/29 has 3 host bits: 2^3 = 8, minus 2 = 6 usable hosts — good for small groups of servers or devices.",
  },
  {
    q: "The primary benefit of using multiple VLANs instead of one flat network is...",
    options: [
      "More cabling required",
      "Smaller broadcast domains and logical security separation between groups",
      "Slower switching",
      "Fewer IP addresses needed",
    ],
    answer: 1,
    explain: "VLANs shrink broadcast domains and logically separate groups (e.g., staff, guests, VoIP) for security and performance, without rewiring the physical network.",
  },
  {
    q: "For 10.0.0.0/16 subnetted into /24s, how many subnets result?",
    options: ["128", "256", "512", "1024"],
    answer: 1,
    explain: "From /16 to /24 borrows 8 bits: 2^8 = 256 subnets, each a /24 with 254 usable hosts.",
  },
  {
    q: "A 'voice VLAN' is used to...",
    options: [
      "Carry only DNS traffic",
      "Separate IP phone traffic so it can be prioritized (QoS) and secured apart from data",
      "Replace the native VLAN",
      "Disable trunking",
    ],
    answer: 1,
    explain: "A voice VLAN segregates VoIP phone traffic from PC data on the same port, enabling QoS prioritization and separate policy for voice.",
  },
  {
    q: "Which is TRUE about the network and broadcast addresses as you make the prefix longer (more subnets)?",
    options: [
      "You gain usable hosts per subnet",
      "You lose 2 addresses (network + broadcast) in every additional subnet, reducing total usable hosts",
      "There is no impact",
      "Broadcasts are eliminated",
    ],
    answer: 1,
    explain: "Every subnet reserves a network and broadcast address, so more (smaller) subnets means more overhead addresses and fewer total usable hosts.",
  },
  {
    q: "In the subnet 192.168.20.32/28, what is the valid host range?",
    options: [
      "192.168.20.33 – 192.168.20.46",
      "192.168.20.32 – 192.168.20.47",
      "192.168.20.33 – 192.168.20.47",
      "192.168.20.32 – 192.168.20.46",
    ],
    answer: 0,
    explain: "/28 block size = 16: subnet .32–.47, network = .32, broadcast = .47, so usable hosts are .33 through .46.",
  },
  {
    q: "A Layer 3 switch differs from a Layer 2 switch in that it can...",
    options: [
      "Only forward frames",
      "Route between VLANs/subnets in hardware (has IP routing capability)",
      "Not use VLANs",
      "Only connect to hubs",
    ],
    answer: 1,
    explain: "A Layer 3 (multilayer) switch adds routing to switching, forwarding between VLANs/subnets at wire speed using SVIs — replacing router-on-a-stick in larger networks.",
  },
  {
    q: "Which of these correctly orders subnet sizes from most hosts to fewest?",
    options: [
      "/30, /28, /26, /24",
      "/24, /26, /28, /30",
      "/26, /24, /30, /28",
      "/28, /30, /24, /26",
    ],
    answer: 1,
    explain: "A smaller prefix number = more host bits = more hosts. So /24 (254) > /26 (62) > /28 (14) > /30 (2).",
  },
  {
    q: "When a switch receives a frame for an unknown destination MAC in a VLAN, it...",
    options: [
      "Drops it",
      "Floods it out all other ports in that VLAN only",
      "Sends it to every VLAN",
      "Routes it",
    ],
    answer: 1,
    explain: "Unknown-unicast frames are flooded only within the frame's VLAN (its broadcast domain), never crossing into other VLANs — reinforcing VLAN isolation.",
  },
  {
    q: "DHCP across VLANs (when the DHCP server is in another subnet) requires a...",
    options: [
      "Second DHCP server per VLAN always",
      "DHCP relay (ip helper-address) on the router/L3 switch",
      "Trunk to the DHCP server only",
      "Static addressing only",
    ],
    answer: 1,
    explain: "Because DHCP Discover is a broadcast confined to its VLAN, a DHCP relay (ip helper-address) forwards requests as unicast to a central DHCP server on another subnet.",
  },
  {
    q: "What is the network ID of the host 172.16.35.200 with a /21 mask?",
    options: ["172.16.32.0", "172.16.35.0", "172.16.34.0", "172.16.40.0"],
    answer: 0,
    explain: "/21 mask = 255.255.248.0, block size 8 in the 3rd octet: subnets are .0, .8, .16, .24, .32, .40. The 3rd octet 35 falls in the .32 block, so the network ID is 172.16.32.0 (range .32.0–.39.255).",
  },
];
